#!/usr/bin/env python3
"""W3-02-U7 — clean-install discovery test (directive 2.1, 2.4, 30).

Discovers, against a CLEAN ONBOARDING COPY:

  factory  — entrypoint present; intake + preflight CLIs run and emit the
             pinned envelope (schema_version, outcome/exit-code agreement);
             the 7 core modules import from the copy; contracts and the
             acceptance profile parse.
  helpers  — the nine onboarding helper skills named by DEPENDENCY-MANIFEST.md
             section 2 (provider skills 66/67/68/74 per directive 2.4, plus
             install-path skills 07/46/30/25/27) each exist with a non-empty
             SKILL.md; the shipped preflight passes over them with approval
             recorded (rc 0, preflight-pass).
  packaging— directive-2.1 top-level allowlist, required file set, version
             stamp agreement (SKILL.md frontmatter vs skill-version.txt),
             zero media binaries, zero files >5 MB, zero operator paths in
             code (.py/.sh/.js/.json — .md evidence docs are exempt: they
             cite scan paths by design), no repo-pollution dirs at skill root.
             Runtime caches (__pycache__/*.pyc) are excluded: they are
             generated by running this test, not shipped.

Acceptance (fails when a helper skill is removed) is proved twice:

  1. in place — a helper removed from the resolved clean copy makes both
     helper discovery and preflight fail, naming the helper (exit 1);
  2. hermetic negative controls — this test always builds its own temp copy
     of all nine helper SKILL.md files, proves discovery + preflight PASS on
     it, then repeats with ONE helper removed and proves discovery + preflight
     FAIL naming it. A control that does not discriminate fails the test.

Clean-copy resolution, first match wins:
  DSAF_ONBOARDING_ROOT=<path>   explicit copy (always wins)
  parents[2] of this file       the checkout this test ships in, when it
                                looks like an onboarding root (>=5 numbered
                                NN-* skill dirs)
  ~/openclaw-onboarding         the operator's clean clone
A staging tree that is not a full onboarding root is never treated as the
clean copy. No root found at all = exit 2 (tooling), never a silent pass.

stdlib only, no network, no provider calls, no repo writes (subprocesses run
with PYTHONDONTWRITEBYTECODE=1). Exit 0 = every row pass, 1 = any row FAIL,
2 = resolve failure (nothing checked). Never writes a verdict file.
"""
from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

SELF = Path(__file__).resolve()
ENVELOPE = "blackceo.intake-preflight/envelope/v1"
SKILL_DIR_NAME = "75-drama-song-ad-factory"
BOX = os.environ.get("BOX_SLUG", "local")

# DEPENDENCY-MANIFEST.md section 2: provider helpers resolved by source —
# never by bare reference (directive 2.4).
PROVIDER_HELPERS = ["66-kie-image", "67-kie-video", "68-kie-audio",
                    "74-kie-live-adapter"]
# Same table: helpers on the existing install path.
INSTALL_PATH_HELPERS = ["07-kie-setup", "46-kie-callback-relay",
                        "30-fish-audio-api-reference", "25-video-creator",
                        "27-video-editor"]
REQUIRED_HELPERS = PROVIDER_HELPERS + INSTALL_PATH_HELPERS
# The helper removed by the hermetic negative control.
CONTROL_REMOVED = "68-kie-audio"

REQUIRED_FILES = [
    "DEPENDENCY-MANIFEST.md", "THIRD_PARTY_NOTICES.md",
    "SKILL.md", "skill-version.txt",
    "scripts/core/intake_preflight/__init__.py",
    "scripts/core/intake_preflight/factory.py",
    "scripts/core/intake_preflight/intake.py",
    "scripts/core/intake_preflight/preflight.py",
    "scripts/core/contracts/campaign-schema.json",
    "scripts/core/contracts/artifact-schema.json",
    "scripts/core/contracts/qc-schema.json",
    "scripts/core/acceptance-profile.json",
]

# Directive 2.1 package shape + PACKAGING-DECISION.md (W3-02-U3 deliverable).
ALLOWED_TOP = {
    "SKILL.md", "INSTRUCTIONS.md", "INSTALL.md", "EXAMPLES.md", "QC.md",
    "CORE_UPDATES.md", "CHANGELOG.md", "PREREQS.json",
    "DEPENDENCY-MANIFEST.md", "THIRD_PARTY_NOTICES.md", "skill-version.txt",
    "PACKAGING-DECISION.md", "drama-song-ad-factory.skill",
    "references", "scripts", "tests", "test-fixtures",
    "universal-sops", "department-wiring",
}
MEDIA_SUFFIXES = {".mp4", ".mov", ".png", ".jpg", ".jpeg", ".wav", ".mp3",
                  ".webp", ".gif", ".m4a", ".avi", ".mkv"}
CODE_SUFFIXES = {".py", ".sh", ".js", ".json"}
POLLUTION_DIRS = {"qualification", "integration", "evidence", "run", ".git"}
MAX_FILE_BYTES = 5 * 1024 * 1024
# assembled from parts so this scanner — which ships inside the skill folder —
# never trips its own packaging scan in any copy of the tree
OPERATOR_PATH = "/Users/" + "blackceomacmini"
SKIP_PARTS = {"__pycache__"}
CORE_MODULES = ("state_store spend_ledger artifact_graph qc_gate "
                "timing_guard job_recovery cc_sync").split()

ROWS = []          # (status, name, detail)
FAILS = []


def row(status, name, detail=""):
    ROWS.append((status, name, detail))
    if status == "FAIL":
        FAILS.append(name)
    line = f"{status}: {name}"
    if detail and status != "ok":
        line += f" ({detail})"
    print(line, flush=True)


def check(name, ok, detail=""):
    row("ok" if ok else "FAIL", name, detail)


# --------------------------------------------------------------------------- #
# resolve the clean onboarding copy
def looks_like_onboarding_root(p: Path) -> bool:
    if not p.is_dir():
        return False
    try:
        n = sum(1 for e in p.iterdir()
                if e.is_dir() and re.match(r"^\d{2}-", e.name))
    except OSError:
        return False
    return n >= 5


def resolve_root():
    env = os.environ.get("DSAF_ONBOARDING_ROOT")
    if env:
        return Path(env).expanduser().resolve(), "env:DSAF_ONBOARDING_ROOT"
    local = SELF.parents[2]          # root containing this test when shipped
    if looks_like_onboarding_root(local):
        return local, "checkout:parents[2]"
    home = Path.home() / "openclaw-onboarding"
    if looks_like_onboarding_root(home):
        return home, "clone:~/openclaw-onboarding"
    if (local / SKILL_DIR_NAME).is_dir():
        return local, "fallback:parents[2]-partial"
    if (home / SKILL_DIR_NAME).is_dir():
        return home, "fallback:clone-partial"
    return None, ""


# --------------------------------------------------------------------------- #
# subprocess helpers (never write into the copy under test)
def run(args, env_extra=None):
    env = dict(os.environ)
    env["PYTHONDONTWRITEBYTECODE"] = "1"
    if env_extra:
        env.update(env_extra)
    p = subprocess.run(args, capture_output=True, text=True, env=env)
    return p.returncode, p.stdout, p.stderr


def factory_cli(factory: Path, args):
    rc, out, err = run([sys.executable, str(factory)] + args)
    try:
        env = json.loads(out)
    except Exception:
        env = None
    return rc, env, (err or out).strip()[-400:]


def write_auth(tmp: Path) -> Path:
    auth = tmp / "auth.json"
    auth.write_text(json.dumps(
        {"scope": "campaign", "expires_unix": int(time.time()) + 3600}))
    return auth


def run_preflight(factory: Path, root: Path, storage: Path, auth: Path,
                  refs):
    args = ["preflight", "--root", str(root), "--storage-dir", str(storage),
            "--auth-file", str(auth), "--run-id", "w302u7"]
    for r in refs:
        args += ["--ref", str(r)]
    return factory_cli(factory, args)


def missing_helpers(root: Path):
    """Return SKILL.md paths under root that a clean copy must carry but does not."""
    out = []
    for h in REQUIRED_HELPERS:
        sm = root / h / "SKILL.md"
        if not (sm.is_file() and sm.stat().st_size > 0):
            out.append(str(sm))
    return out


# --------------------------------------------------------------------------- #
def factory_checks(root: Path, tmp: Path):
    skill = root / SKILL_DIR_NAME
    factory = skill / "scripts" / "core" / "intake_preflight" / "factory.py"
    check("factory: skill dir discovered", skill.is_dir(), str(skill))
    entry = factory.is_file()
    check("factory: entrypoint discovered", entry, str(factory))
    if not entry:
        for n in ("factory: intake CLI envelope", "factory: preflight CLI rejects without approval",
                  "factory: 7 core modules import from copy",
                  "factory: contracts + acceptance profile parse"):
            row("FAIL", n, "entrypoint missing")
        return factory

    # intake: empty brief must normalize to waiting/missing-essentials
    rc, env, tail = factory_cli(factory, ["intake", "--brief", "{}",
                                          "--run-id", "w302u7"])
    got = env.get("outcome") if isinstance(env, dict) else None
    ok = (rc == 2 and isinstance(env, dict)
          and got == "waiting"
          and env.get("reason_code") == "missing-essentials"
          and env.get("schema_version") == ENVELOPE)
    check("factory: intake CLI envelope", ok, f"rc={rc} outcome={got} {tail}")

    # preflight without approval must stop fail-closed (names only, no exec)
    rc, env, tail = factory_cli(factory, ["preflight", "--root", str(tmp),
                                          "--run-id", "w302u7"])
    ok = (rc == 4 and isinstance(env, dict)
          and env.get("outcome") == "rejected"
          and env.get("reason_code") == "approval-missing")
    check("factory: preflight CLI rejects without approval",
          ok, f"rc={rc} {tail}")

    # 7 core modules import from the copy under test
    mods = " ".join(CORE_MODULES)
    code = (f"import importlib;mods='{mods}'.split();"
            f"[importlib.import_module(m) for m in mods];"
            f"print('imported:%d' % len(mods))")
    rc, out, err = run([sys.executable, "-c", code],
                       env_extra={"PYTHONPATH": str(skill / "scripts" / "core")})
    check("factory: 7 core modules import from copy",
          rc == 0 and "imported:7" in out, (err or out).strip()[-300:])

    # contracts + acceptance profile parse and carry their version markers
    detail, parsed_ok = [], True
    for rel, marker in (("scripts/core/contracts/campaign-schema.json", "schema_version"),
                        ("scripts/core/contracts/artifact-schema.json", "schema_version"),
                        ("scripts/core/contracts/qc-schema.json", "schema_version"),
                        ("scripts/core/acceptance-profile.json", "profile_version")):
        p = skill / rel
        try:
            text = p.read_text(encoding="utf-8")
            obj = json.loads(text)
            if not isinstance(obj, dict) or marker not in text:
                parsed_ok = False
                detail.append(f"{rel}: missing {marker}")
        except Exception as e:
            parsed_ok = False
            detail.append(f"{rel}: {e}")
    check("factory: contracts + acceptance profile parse", parsed_ok,
          "; ".join(detail))
    return factory


def helper_checks(root: Path, tmp: Path, factory: Path):
    manifest = root / SKILL_DIR_NAME / "DEPENDENCY-MANIFEST.md"
    try:
        text = manifest.read_text(encoding="utf-8")
        absent = [h for h in PROVIDER_HELPERS if h not in text]
        check("helpers: DEPENDENCY-MANIFEST names provider helpers",
              not absent, "missing from manifest: " + ",".join(absent))
    except Exception as e:
        check("helpers: DEPENDENCY-MANIFEST names provider helpers",
              False, str(e))

    for h in REQUIRED_HELPERS:
        sm = root / h / "SKILL.md"
        ok = sm.is_file() and sm.stat().st_size > 0
        check(f"helpers: {h} discovered", ok, str(sm))

    # shipped preflight over the real helpers, approval recorded -> rc 0.
    # A removed helper makes this fail with reference-missing-or-truncated.
    if factory and factory.is_file():
        refs = [root / h / "SKILL.md" for h in REQUIRED_HELPERS]
        rc, env, tail = run_preflight(factory, root, tmp, write_auth(tmp), refs)
        ok = (rc == 0 and isinstance(env, dict)
              and env.get("outcome") == "ok"
              and env.get("reason_code") == "preflight-pass")
        miss = (env or {}).get("data", {}).get("missing") if isinstance(env, dict) else None
        check("helpers: preflight passes with approval (rc 0)", ok,
              f"rc={rc} reason={(env or {}).get('reason_code') if isinstance(env, dict) else None} missing={miss} {tail}")
    else:
        row("FAIL", "helpers: preflight passes with approval (rc 0)",
            "entrypoint missing")


def packaging_checks(root: Path):
    skill = root / SKILL_DIR_NAME
    if not skill.is_dir():
        row("FAIL", "packaging: skill dir present", str(skill))
        return
    missing = [rel for rel in REQUIRED_FILES if not (skill / rel).is_file()]
    check("packaging: required file set present", not missing,
          "missing: " + ",".join(missing))

    # version stamp agreement (SKILL.md frontmatter vs skill-version.txt)
    try:
        sk = (skill / "SKILL.md").read_text(encoding="utf-8")
        fm = sk.split("---")[1] if sk.startswith("---") and sk.count("---") >= 2 else ""
        m = re.search(r"^version:\s*(\S+)", fm, re.M)
        stamp = (skill / "skill-version.txt").read_text(encoding="utf-8").strip()
        check("packaging: SKILL.md version == skill-version.txt",
              bool(m) and m.group(1) == stamp,
              f"frontmatter={m.group(1) if m else None} stamp={stamp}")
    except Exception as e:
        check("packaging: SKILL.md version == skill-version.txt", False, str(e))

    top = {e.name for e in skill.iterdir()}
    unexpected = sorted(top - ALLOWED_TOP)
    check("packaging: top-level allowlist (directive 2.1)", not unexpected,
          "unexpected: " + ",".join(unexpected))

    media, oversize, opaths = [], [], []
    for dirpath, dirnames, filenames in os.walk(skill):
        dirnames[:] = [d for d in dirnames if d not in SKIP_PARTS]
        for fn in filenames:
            p = Path(dirpath) / fn
            if fn.endswith(".pyc"):
                continue
            try:
                size = p.stat().st_size
            except OSError:
                continue
            if p.suffix.lower() in MEDIA_SUFFIXES:
                media.append(str(p.relative_to(skill)))
            if size > MAX_FILE_BYTES:
                oversize.append(f"{p.relative_to(skill)} ({size}B)")
            if p.suffix.lower() in CODE_SUFFIXES:
                try:
                    if OPERATOR_PATH in p.read_text(encoding="utf-8",
                                                    errors="ignore"):
                        opaths.append(str(p.relative_to(skill)))
                except OSError:
                    pass
    check("packaging: zero media binaries", not media, ",".join(media[:5]))
    check("packaging: zero files over 5MB", not oversize, ",".join(oversize[:5]))
    check("packaging: zero operator paths in code", not opaths,
          ",".join(opaths[:5]))
    polluted = sorted(d for d in POLLUTION_DIRS if (skill / d).exists())
    check("packaging: no repo-pollution dirs at skill root", not polluted,
          ",".join(polluted))


def negative_controls(root: Path, tmp: Path, factory: Path):
    """Hermetic proof that discovery+preflight discriminate on a missing helper."""
    auth = write_auth(tmp)
    # full temp copy: every required helper's SKILL.md present
    full = tmp / "copy-full"
    miss_root = tmp / "copy-missing-helper"
    for root_dir in (full, miss_root):
        root_dir.mkdir(parents=True, exist_ok=True)
        for h in REQUIRED_HELPERS:
            if root_dir is miss_root and h == CONTROL_REMOVED:
                continue
            src = root / h / "SKILL.md"
            if not src.is_file():
                continue          # helper_checks already fails this row
            d = root_dir / h
            d.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, d / "SKILL.md")

    m_full = missing_helpers(full)
    check("control: clean temp copy discovers all helpers", not m_full,
          ",".join(m_full))
    rc, env, tail = run_preflight(factory, full, tmp, auth,
                                  [full / h / "SKILL.md" for h in REQUIRED_HELPERS])
    check("control: preflight passes on clean temp copy",
          rc == 0 and isinstance(env, dict) and env.get("outcome") == "ok",
          f"rc={rc} {tail}")

    m_miss = missing_helpers(miss_root)
    expected = str(miss_root / CONTROL_REMOVED / "SKILL.md")
    check("control: discovery FAILS naming the removed helper",
          m_miss == [expected], f"missing={m_miss}")
    rc, env, tail = run_preflight(
        factory, miss_root, tmp, auth,
        [miss_root / h / "SKILL.md" for h in REQUIRED_HELPERS])
    got = (env or {}).get("data", {}).get("missing") if isinstance(env, dict) else None
    # preflight realpaths its report; compare on the helper path suffix so a
    # symlinked temp dir (/var vs /private/var) cannot flip the control.
    named = (isinstance(got, list) and len(got) == 1
             and str(got[0]).endswith(f"{CONTROL_REMOVED}/SKILL.md"))
    ok = (rc == 1 and isinstance(env, dict)
          and env.get("reason_code") == "reference-missing-or-truncated"
          and named)
    check("control: preflight fails clearly naming the removed helper", ok,
          f"rc={rc} reason={(env or {}).get('reason_code') if isinstance(env, dict) else None} missing={got}")


def main() -> int:
    root, source = resolve_root()
    if root is None:
        print(f"resolve-failure: no clean onboarding root "
              f"(checked env, {SELF.parents[2]}, ~/openclaw-onboarding)",
              file=sys.stderr)
        return 2
    print(f"clean onboarding copy: {root}  (via {source})", flush=True)
    tmp = Path(tempfile.mkdtemp(prefix=f"{BOX}-W3-02-U7-"))
    try:
        factory = factory_checks(root, tmp)
        helper_checks(root, tmp, factory)
        packaging_checks(root)
        if factory and factory.is_file():
            negative_controls(root, tmp, factory)
        else:
            row("FAIL", "control: hermetic helper-removal controls",
                "entrypoint missing")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
    npass = sum(1 for s, _, _ in ROWS if s == "ok")
    print(f"SUMMARY: {npass} ok, {len(FAILS)} FAIL, {len(ROWS)} rows")
    if FAILS:
        print("RESULT: FAIL\nfailed rows:\n  - " + "\n  - ".join(FAILS))
        return 1
    print("RESULT: PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
