#!/usr/bin/env python3
"""ghl_media.py — T2 REAL IMAGE PIPELINE for the Skill-06 funnel/website builder.

WHAT THIS IS
------------
The build path the spec assumes is: the page copy drives REAL, on-brand raster
images (generated by the repo's verified KIE.ai tooling), those PNGs are uploaded
to the GoHighLevel media library (which returns a PUBLIC, login-free GCS object
URL), and the in-page custom-code element is rewritten to reference that CDN URL
via the proven token-id autosave (``ghl_rest_canvas.edit_element_customcode`` +
``page_autosave``). This module owns the deterministic, mechanical halves of that
pipeline so they are never improvised:

  1. ``build_prompts_json(copy_specs, ...)`` — mechanically derive the KIE
     ``prompts.json`` (one entry per image) from the page copy, with the
     mandatory English/Latin-only pin appended to EVERY prompt verbatim.
  2. ``generate_images(prompts_path, out_dir, ...)`` — a thin wrapper that shells
     the canonical ``kie_generate.py`` (REUSED AS-IS — never forked). It submits,
     polls, downloads, and PNG-magic-byte-verifies; this wrapper only locates the
     tool, runs it, and reports which ``<slide>.png`` files landed (+ re-asserts
     the PNG magic bytes itself, so a non-PNG can never be passed downstream).
  3. ``upload_media(png_path, location_id, name, pit, ...)`` — ports the PROVEN
     ``POST services.leadconnectorhq.com/medias/upload-file`` Bearer-PIT call from
     ``37-zhc-closeout/scripts/upload-ghl-media.sh`` to Python, returning
     ``{fileId, url}`` where ``url`` is the PUBLIC ``storage.googleapis.com/msgsndr/...``
     GCS object URL (openable with NO login — that is the real ``cdn_url``).
  4. ``image_tag(cdn_url, alt)`` + ``build_image_manifest(...)`` — the in-page
     ``<img>`` snippet and the ``images/manifest.json`` output contract.

AUTH-MODEL SPLIT (LOAD-BEARING — this module sits ENTIRELY on the bare-Python side)
-----------------------------------------------------------------------------------
  * KIE.ai (``api.kie.ai``) and the GHL MEDIA upload (``services.leadconnectorhq.com``
    + ``Authorization: Bearer <LOCATION PIT>``) are NOT behind the funnels-builder
    Cloudflare interstitial, so they run from bare Python. This module makes those
    calls directly (KIE via the reused subprocess; media via ``urllib``).
  * The IN-PAGE write that references the CDN URL (``/funnels/builder/autosave``)
    IS Cloudflare-WAF-gated (1010 from bare Python) and MUST run inside the
    agent-browser eval. This module does NOT make that call — it only produces the
    edited blob + the ``<img>`` snippet; ``ghl_rest_canvas.page_autosave`` (driven
    by ``ghl_builder.emit_rest_save_plan``) executes it in-browser.

KEYS — OPERATOR'S OWN, NEVER A CLIENT'S
---------------------------------------
``KIE_API_KEY`` is read by the reused ``kie_generate.py`` from the environment or
the standard env stores. The GHL LOCATION Private Integration Token (PIT) is read
by ``resolve_location_pit`` from the same canonical env names the closeout script
uses (``GOHIGHLEVEL_API_KEY``/``GHL_API_KEY``). In THIS phase the keys are the
operator's own fixture keys (the configured GHL location id, env
``GHL_LOCATION_ID``/``GOHIGHLEVEL_LOCATION_ID``); a client key must never appear
here.

NO-FABRICATION / FAIL-LOUD
--------------------------
Every step fails LOUD rather than substitute a placeholder: a non-PNG download
raises (never an SVG stub); a missing key raises (never a ``file://`` cdn_url); an
upload that returns no ``fileId``/``url`` raises (never a fake CDN URL). The
``images/manifest.json`` contract therefore can only ever carry real ``https``
``cdn_url`` values with a verified HTTP status.
"""

from __future__ import annotations

import json
import mimetypes
import os
import subprocess
import sys
import urllib.error
import urllib.request
import uuid
from pathlib import Path
from typing import Any, Callable

# ── Constants (ported from the PROVEN upload-ghl-media.sh + kie_generate.py) ──

# Media upload lives on the services.* origin (Bearer PIT) — NOT WAF-gated, so
# this runs from bare Python. (The funnels/builder autosave that REFERENCES the
# returned URL is WAF-gated and runs in-browser; that is NOT this module.)
GHL_SERVICES_ORIGIN = "https://services.leadconnectorhq.com"
GHL_MEDIA_UPLOAD_PATH = "/medias/upload-file"
GHL_MEDIA_FOLDER_PATH = "/medias/folder"   # Skill 48 addition: per-run media folder
GHL_MEDIA_VERSION = "2021-07-28"

# The mandatory English/Latin-only pin — appended VERBATIM to every prompt that
# renders copy (carried verbatim from kie_generate.py's module docstring so the
# generator and this builder agree on the exact text).
ENGLISH_LATIN_PIN = (
    "All text rendered in the image MUST be in English, Latin alphabet ONLY. NO "
    "Chinese/CJK or non-Latin characters anywhere. Render the copy spelled "
    "correctly, letter-for-letter. No garbled, misspelled, or invented text."
)

# PNG magic bytes — a real raster starts with these. A non-PNG download is a hard
# FAIL (never stubbed). Mirrors the verify in kie_generate.py.
PNG_MAGIC = b"\x89PNG\r\n\x1a\n"

# Canonical location of the REUSED (never forked) KIE generator, relative to this
# file (.../06-ghl-install-pages/tools/ -> repo root -> 23-.../kie_generate.py).
_KIE_GENERATE_RELPATH = os.path.join(
    "..", "..", "23-ai-workforce-blueprint", "templates",
    "presentation-render", "kie_generate.py",
)

# Canonical env names for the GHL LOCATION PIT (matches upload-ghl-media.sh).
# Media uploads REQUIRE the LOCATION PIT (the Agency PIT 401s for media ops).
_PIT_ENV_NAMES = ("GOHIGHLEVEL_API_KEY", "GHL_API_KEY")
_LOCATION_ENV_NAMES = ("GOHIGHLEVEL_LOCATION_ID", "GHL_LOCATION_ID")


# ── small helpers ─────────────────────────────────────────────────────────────

def _require(value: Any, name: str) -> None:
    """Reject empty / whitespace-only required values (fail loud, never silently
    proceed with a blank that would target the wrong resource)."""
    if value is None or (isinstance(value, str) and not value.strip()):
        raise ValueError(f"{name} is required and must be non-empty")


def kie_generate_path() -> str:
    """Absolute path to the canonical ``kie_generate.py`` (REUSED AS-IS).

    Resolved relative to this module so the wrapper works regardless of the
    caller's working directory. Raises if the reused tool is not where the repo
    layout puts it (fail loud rather than silently skip image generation)."""
    path = os.path.normpath(os.path.join(os.path.dirname(__file__), _KIE_GENERATE_RELPATH))
    if not os.path.isfile(path):
        raise FileNotFoundError(
            f"reused KIE generator not found at {path!r} — expected the repo's "
            "23-ai-workforce-blueprint/templates/presentation-render/kie_generate.py"
        )
    return path


def resolve_location_pit(env: dict | None = None) -> str:
    """Resolve the GHL LOCATION PIT from the canonical env names.

    Reads ``GOHIGHLEVEL_API_KEY`` (preferred) then the legacy ``GHL_API_KEY``
    alias, mirroring ``upload-ghl-media.sh``. Strips surrounding quotes. Raises
    if neither is set — media upload cannot proceed without the LOCATION PIT, and
    we never fabricate a public URL, so a missing key is a hard, honest FAIL."""
    env = env if env is not None else os.environ
    for name in _PIT_ENV_NAMES:
        val = str(env.get(name, "")).strip().strip("'\"")
        if val:
            return val
    raise RuntimeError(
        "GHL LOCATION PIT not found — set one of "
        f"{', '.join(_PIT_ENV_NAMES)} (the LOCATION Private Integration Token). "
        "Media uploads require the LOCATION PIT (the Agency PIT 401s for media)."
    )


def resolve_location_id(env: dict | None = None) -> str:
    """Resolve the GHL location id from the canonical env names (the configured
    fixture supplies it via ``GHL_LOCATION_ID``/``GOHIGHLEVEL_LOCATION_ID``).
    Raises if unset (fail loud)."""
    env = env if env is not None else os.environ
    for name in _LOCATION_ENV_NAMES:
        val = str(env.get(name, "")).strip().strip("'\"")
        if val:
            return val
    raise RuntimeError(
        f"GHL location id not found — set one of {', '.join(_LOCATION_ENV_NAMES)}."
    )


# ── 1) build_prompts_json — derive the KIE prompts from the page copy ─────────

def build_prompts_json(
    copy_specs: list[dict],
    out_path: str | None = None,
    *,
    default_mode: str = "t2i",
) -> list[dict]:
    """Mechanically build the KIE ``prompts.json`` array from page-copy specs.

    Each ``copy_specs`` entry describes ONE image the page needs and is shaped::

        {
            "id": "hero-soap-trio",          # the slide id (becomes <id>.png)
            "prompt": "<copy-derived scene>", # the visual brief from the page copy
            "mode": "t2i",                    # optional; default_mode otherwise
            "input_urls": ["https://..."],    # required ONLY when mode == "i2i"
            "used_on_page_id": "PAGEID...",   # optional provenance (carried through)
            "alt": "...",                     # optional <img> alt text
            "locator": {"section_idx": 0, "element_idx": 2}  # optional splice target
        }

    The output array matches what ``kie_generate.py`` consumes
    (``[{"slide", "prompt", "mode", ["input_urls"]}]``) and appends the mandatory
    ``ENGLISH_LATIN_PIN`` to EVERY prompt verbatim (idempotent — never doubled).
    ``t2i`` (``gpt-image-2-text-to-image``) is the default because the fictional
    brand has no logo to seed image-to-image; an ``i2i`` entry MUST carry
    ``input_urls`` (the generator enforces this too).

    The build-time fields the generator ignores (``used_on_page_id``, ``alt``,
    ``locator``) are preserved on the returned objects so the caller can map each
    rendered PNG back to its page element after generation, but they are stripped
    before the file is written (the file is exactly what ``kie_generate.py`` wants).

    Args:
        copy_specs: The list of per-image copy specs (above).
        out_path: When given, the generator-shaped array is written there as JSON
            (the file ``kie_generate.py`` is then pointed at).
        default_mode: Fallback mode for entries that omit ``mode`` (default
            ``"t2i"``).

    Returns:
        The list of ENRICHED prompt dicts (generator fields + carried-through
        build-time fields). The on-disk file (when ``out_path`` is given) carries
        only the generator fields.

    Raises:
        ValueError: empty specs, a missing/blank ``id`` or ``prompt``, a duplicate
            ``id``, an unknown ``mode``, or an ``i2i`` entry without ``input_urls``.
    """
    if not isinstance(copy_specs, list) or not copy_specs:
        raise ValueError("copy_specs must be a non-empty list of image specs")

    enriched: list[dict] = []
    file_entries: list[dict] = []
    seen_ids: set[str] = set()

    for i, spec in enumerate(copy_specs):
        if not isinstance(spec, dict):
            raise ValueError(f"copy_specs[{i}] must be a dict")
        slide_id = str(spec.get("id", "")).strip()
        _require(slide_id, f"copy_specs[{i}].id")
        if slide_id in seen_ids:
            raise ValueError(f"duplicate image id {slide_id!r} in copy_specs")
        seen_ids.add(slide_id)

        prompt = str(spec.get("prompt", "")).strip()
        _require(prompt, f"copy_specs[{i}].prompt ({slide_id})")

        mode = str(spec.get("mode", default_mode)).strip().lower()
        if mode not in ("t2i", "i2i"):
            raise ValueError(
                f"copy_specs[{i}] ({slide_id}): mode must be 't2i' or 'i2i' (got {mode!r})"
            )

        # Append the English/Latin pin verbatim — idempotent (never double-append).
        if ENGLISH_LATIN_PIN not in prompt:
            prompt = f"{prompt} {ENGLISH_LATIN_PIN}"

        # Generator-shaped entry (exactly what kie_generate.py consumes).
        gen_entry: dict[str, Any] = {"slide": slide_id, "prompt": prompt, "mode": mode}
        if mode == "i2i":
            input_urls = spec.get("input_urls") or []
            if not isinstance(input_urls, list) or not input_urls:
                raise ValueError(
                    f"copy_specs[{i}] ({slide_id}): mode=i2i requires a non-empty "
                    "input_urls list (set mode=t2i if there is no reference image)"
                )
            gen_entry["input_urls"] = list(input_urls)
        file_entries.append(gen_entry)

        # Enriched object the caller keeps for post-gen mapping.
        out_obj = dict(gen_entry)
        if "used_on_page_id" in spec:
            out_obj["used_on_page_id"] = spec["used_on_page_id"]
        if "alt" in spec:
            out_obj["alt"] = spec["alt"]
        if "locator" in spec:
            out_obj["locator"] = spec["locator"]
        enriched.append(out_obj)

    if out_path:
        Path(out_path).parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(file_entries, f, indent=2)

    return enriched


# ── 2) generate_images — thin wrapper over the REUSED kie_generate.py ─────────

def verify_png(path: str) -> bool:
    """True iff ``path`` exists and starts with the PNG magic bytes.

    Re-asserted here (independently of the generator's own check) so a non-PNG
    can never be passed downstream into the manifest / page splice."""
    p = Path(path)
    if not p.is_file() or p.stat().st_size < len(PNG_MAGIC):
        return False
    with open(p, "rb") as f:
        return f.read(len(PNG_MAGIC)) == PNG_MAGIC


def generate_images(
    prompts_path: str,
    out_dir: str,
    *,
    expected_ids: list[str] | None = None,
    runner: Callable[[list[str]], int] | None = None,
    python_exe: str | None = None,
) -> dict:
    """Shell the canonical ``kie_generate.py`` (REUSED AS-IS) to generate + verify
    the rasters, then confirm each expected ``<id>.png`` landed and is a real PNG.

    This wrapper does NOT re-implement KIE submit/poll/download — it locates the
    proven tool, runs ``python3 kie_generate.py <prompts_path> <out_dir>`` (which
    handles waves/rate-cap, polling, the CDN download, and its own PNG-magic-byte
    verify, exiting 0 only when ALL slides downloaded), then independently
    re-verifies the PNG magic bytes of each output. Injectable ``runner`` keeps it
    unit-testable WITHOUT any live KIE call (the live run is a later phase).

    Args:
        prompts_path: The generator ``prompts.json`` (from ``build_prompts_json``).
        out_dir: Directory where ``<slide>.png`` files are written.
        expected_ids: The slide ids that MUST be present as ``<id>.png`` after the
            run (defaults to the ids parsed from ``prompts_path``).
        runner: Optional callable taking the argv list and returning the process
            exit code (default = real ``subprocess.run``). Tests inject a fake that
            writes PNG fixtures + returns 0 — NO live network.
        python_exe: Python interpreter for the subprocess (default ``sys.executable``).

    Returns:
        ``{ok, exit_code, out_dir, images: [{id, file, png_verified, bytes}], missing}``.
        ``ok`` is True iff the generator exited 0 AND every expected PNG verified.

    Raises:
        ValueError: empty/missing ``prompts_path``.
        FileNotFoundError: the reused generator is absent.
    """
    _require(prompts_path, "prompts_path")
    if not os.path.isfile(prompts_path):
        raise ValueError(f"prompts_path does not exist: {prompts_path}")
    Path(out_dir).mkdir(parents=True, exist_ok=True)

    if expected_ids is None:
        entries = json.load(open(prompts_path))
        expected_ids = [str(e.get("slide", "")).strip() for e in entries if e.get("slide")]

    gen = kie_generate_path()  # raises if the reused tool is missing
    argv = [python_exe or sys.executable, gen, prompts_path, out_dir]

    if runner is None:
        proc = subprocess.run(argv, capture_output=True, text=True)
        exit_code = proc.returncode
    else:
        exit_code = int(runner(argv))

    images: list[dict] = []
    missing: list[str] = []
    for sid in expected_ids:
        png = os.path.join(out_dir, f"{sid}.png")
        ok_png = verify_png(png)
        if ok_png:
            images.append({
                "id": sid,
                "file": png,
                "png_verified": True,
                "bytes": os.path.getsize(png),
            })
        else:
            missing.append(sid)

    return {
        "ok": exit_code == 0 and not missing,
        "exit_code": exit_code,
        "out_dir": out_dir,
        "images": images,
        "missing": missing,
    }


# ── 3) upload_media — PROVEN services.* Bearer-PIT media upload (bare Python) ──

def _multipart_encode(fields: dict[str, str], file_field: str, file_path: str) -> tuple[bytes, str]:
    """Encode ``multipart/form-data`` for the media upload (one file + text fields).

    Returns ``(body_bytes, content_type)``. Mirrors the curl ``-F`` form the proven
    shell script sends: ``file=@<path>``, ``locationId``, ``name``, ``hosted`` (and
    optional ``parentId``). A small, dependency-free encoder so the upload runs on
    stock Python (no ``requests``)."""
    boundary = f"----ghlmedia{uuid.uuid4().hex}"
    crlf = b"\r\n"
    out: list[bytes] = []
    for key, val in fields.items():
        out.append(b"--" + boundary.encode())
        out.append(f'Content-Disposition: form-data; name="{key}"'.encode())
        out.append(b"")
        out.append(str(val).encode("utf-8"))
    # The file part.
    fname = os.path.basename(file_path)
    ctype = mimetypes.guess_type(fname)[0] or "application/octet-stream"
    with open(file_path, "rb") as f:
        file_bytes = f.read()
    out.append(b"--" + boundary.encode())
    out.append(
        f'Content-Disposition: form-data; name="{file_field}"; filename="{fname}"'.encode()
    )
    out.append(f"Content-Type: {ctype}".encode())
    out.append(b"")
    body = crlf.join(out) + crlf + file_bytes + crlf
    body += b"--" + boundary.encode() + b"--" + crlf
    return body, f"multipart/form-data; boundary={boundary}"


def upload_media(
    png_path: str,
    location_id: str,
    name: str,
    pit: str,
    *,
    hosted: bool = False,
    parent_id: str | None = None,
    timeout: int = 300,
    opener: Callable[[urllib.request.Request, int], Any] | None = None,
    require_png: bool = True,
) -> dict:
    """Upload one media file to the GHL media library and return ``{fileId, url}``.

    Ports the PROVEN call from ``37-zhc-closeout/scripts/upload-ghl-media.sh``:
    ``POST services.leadconnectorhq.com/medias/upload-file`` with
    ``Authorization: Bearer <LOCATION PIT>`` + ``Version: 2021-07-28`` and the
    multipart fields ``file`` / ``locationId`` / ``name`` / ``hosted`` (+ optional
    ``parentId`` FOLDER id — the field is ``parentId``, NOT ``folderId``). The
    response ``url`` is a PUBLIC ``storage.googleapis.com/msgsndr/...`` GCS object
    URL — openable with NO login. THAT public URL is the real ``cdn_url`` the page
    references.

    This is on the bare-Python side of the auth split (services.* + Bearer PIT is
    NOT Cloudflare-WAF-gated). FAIL-LOUD: a non-2xx response, or a 2xx with no
    ``fileId``/``url``, raises (we never fabricate a CDN URL).

    Args:
        png_path: Local PNG to upload (must be a real PNG — re-verified).
        location_id: The GHL sub-account location id (fixture ``Mct54...``).
        name: Human-friendly media-library name.
        pit: The LOCATION Private Integration Token (Bearer).
        hosted: The ``hosted`` form field (default False).
        parent_id: Optional FOLDER id (``parentId``); files land in the media root
            when omitted (still fully shareable).
        timeout: HTTP timeout seconds (uploads can be large).
        opener: Optional callable ``(Request, timeout) -> response-like`` for tests
            (mock the HTTP). Default = ``urllib.request.urlopen`` (real call).
        require_png: When True (DEFAULT — the Skill-06 / Skill-48 image pipelines),
            the file MUST pass the PNG magic-byte check (only real generated rasters
            are hosted, never a stub). When False, the PNG-only restriction is lifted
            so a NON-IMAGE media artifact (e.g. a final ``.pptx``/``.pdf`` deck) can be
            hosted through this SAME proven REST call instead of forking it — the file
            must still exist. The default keeps every existing caller's behavior
            byte-for-byte; ONLY a caller that has already proven the artifact is a
            legitimate non-image deliverable passes ``require_png=False`` (in the
            Presentations dept that is the gated ``ghl_media.upload_media`` wrapper,
            which runs the fail-closed delivery boundary gate BEFORE it does so).

    Returns:
        ``{fileId, url, name, local_path, http}`` — ``url`` is the public GCS URL.

    Raises:
        ValueError: missing args, a non-PNG file when ``require_png`` (default), or a
            non-existent file when ``require_png=False``.
        RuntimeError: non-2xx HTTP, or a 2xx response missing ``fileId``/``url``.
    """
    _require(png_path, "png_path")
    _require(location_id, "location_id")
    _require(name, "name")
    _require(pit, "pit")
    if require_png:
        if not verify_png(png_path):
            raise ValueError(
                f"refusing to upload {png_path!r}: not a valid PNG (magic-byte check "
                "failed) — only real generated rasters are uploaded, never a stub"
            )
    elif not os.path.isfile(png_path):
        # require_png=False lifts the image-only restriction (a deck deliverable), but
        # a missing file is still a hard FAIL — we never POST a phantom artifact.
        raise ValueError(
            f"refusing to upload {png_path!r}: file does not exist (require_png=False "
            "lifts the PNG-only check for non-image deliverables, not the existence check)"
        )

    fields: dict[str, str] = {
        "locationId": location_id,
        "name": name,
        "hosted": "true" if hosted else "false",
    }
    if parent_id:
        fields["parentId"] = parent_id  # documented folder field is parentId

    body, content_type = _multipart_encode(fields, "file", png_path)
    url = GHL_SERVICES_ORIGIN.rstrip("/") + GHL_MEDIA_UPLOAD_PATH
    req = urllib.request.Request(url, data=body, method="POST")
    req.add_header("Authorization", f"Bearer {pit}")
    req.add_header("Version", GHL_MEDIA_VERSION)
    req.add_header("Content-Type", content_type)

    _opener = opener or (lambda r, t: urllib.request.urlopen(r, timeout=t))
    try:
        resp = _opener(req, timeout)
        code = resp.getcode()
        raw = resp.read()
        if isinstance(raw, bytes):
            raw = raw.decode("utf-8", "replace")
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", "replace") if hasattr(exc, "read") else ""
        raise RuntimeError(
            f"media upload HTTP {exc.code} for {name!r}: {detail[:300]} "
            "(media uploads REQUIRE the LOCATION PIT with medias.write scope; "
            "the Agency PIT 401s)"
        ) from exc

    if not (200 <= int(code) < 300):
        raise RuntimeError(f"media upload returned HTTP {code} for {name!r}: {raw[:300]}")

    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise RuntimeError(
            f"media upload {code} but body is not JSON for {name!r}: {raw[:300]}"
        ) from exc

    file_id = data.get("fileId") or data.get("id")
    public_url = data.get("url") or data.get("fileUrl")
    if not file_id or not public_url:
        raise RuntimeError(
            f"media upload {code} but response missing fileId/url for {name!r}: "
            f"{json.dumps(data)[:300]} — refusing to fabricate a CDN URL"
        )

    return {
        "fileId": file_id,
        "url": public_url,
        "name": name,
        "local_path": png_path,
        "http": int(code),
    }


# ── 3b) create_media_folder — NET-NEW for Skill 48 (per-run media folder) ─────

def create_media_folder(
    name: str,
    location_id: str,
    pit: str,
    *,
    parent_id: str | None = None,
    timeout: int = 60,
    opener: "Callable[[urllib.request.Request, int], Any] | None" = None,
) -> dict:
    """Create a named media-library FOLDER and return ``{folderId, name}``.

    NET-NEW for Skill 48 (it does NOT exist in the Skill-06 module). Each ad run gets
    its own named folder so the 10 hosted images are grouped under the run-id, never
    scattered in the media root. Calls
    ``POST services.leadconnectorhq.com/medias/folder`` with
    ``Authorization: Bearer <LOCATION PIT>`` + ``Version: 2021-07-28`` and a JSON body
    ``{name, locationId[, parentId]}`` — the same auth model as ``upload_media`` (the
    LOCATION PIT with ``medias.write``; the Agency PIT 401s for media ops).

    FALLBACK (the caller's contract, not an exception here): if folder creation is not
    available on the box / location, the caller uploads to the media ROOT with a
    ``name`` PREFIX (e.g. ``"<run-id> — ad 3"``) so the images are still grouped by name.
    This function returns ``{"folderId": None, "fallback": "name-prefix", ...}`` on a
    non-2xx response WITHOUT a folder id, so the caller can take the prefix path; it
    raises only on a hard transport error (never fabricates a folder id).

    Returns:
        ``{folderId, name, http}`` on success, or
        ``{folderId: None, name, http, fallback: "name-prefix"}`` when the API declines
        (the caller then uses the name-prefix fallback).
    """
    _require(name, "name")
    _require(location_id, "location_id")
    _require(pit, "pit")

    body_obj: dict[str, Any] = {"name": name, "locationId": location_id}
    if parent_id:
        body_obj["parentId"] = parent_id
    body = json.dumps(body_obj).encode("utf-8")

    url = GHL_SERVICES_ORIGIN.rstrip("/") + GHL_MEDIA_FOLDER_PATH
    req = urllib.request.Request(url, data=body, method="POST")
    req.add_header("Authorization", f"Bearer {pit}")
    req.add_header("Version", GHL_MEDIA_VERSION)
    req.add_header("Content-Type", "application/json")

    _opener = opener or (lambda r, t: urllib.request.urlopen(r, timeout=t))
    try:
        resp = _opener(req, timeout)
        code = resp.getcode()
        raw = resp.read()
        if isinstance(raw, bytes):
            raw = raw.decode("utf-8", "replace")
    except urllib.error.HTTPError as exc:
        # API declined (e.g. folders unsupported on this location) -> name-prefix fallback.
        return {"folderId": None, "name": name, "http": int(getattr(exc, "code", 0)),
                "fallback": "name-prefix"}
    except (urllib.error.URLError, OSError) as exc:
        raise RuntimeError(
            f"media folder create transport error for {name!r}: {exc} "
            "(LOCATION PIT with medias.write required)"
        ) from exc

    if not (200 <= int(code) < 300):
        return {"folderId": None, "name": name, "http": int(code), "fallback": "name-prefix"}
    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        return {"folderId": None, "name": name, "http": int(code), "fallback": "name-prefix"}
    folder_id = (data.get("id") or data.get("folderId")
                 or (data.get("folder") or {}).get("id")
                 or (data.get("data") or {}).get("id"))
    if not folder_id:
        return {"folderId": None, "name": name, "http": int(code), "fallback": "name-prefix"}
    return {"folderId": folder_id, "name": name, "http": int(code)}


# ── 4) in-page <img> snippet + the images/manifest.json output contract ───────

def image_tag(cdn_url: str, alt: str = "") -> str:
    """Return the ``<img>`` snippet that references the PUBLIC CDN URL in-page.

    The ``cdn_url`` MUST be an ``http(s)`` URL (the public GCS object URL from
    ``upload_media``) — a ``file://`` or SVG-data placeholder is REFUSED, so a
    stub can never be spliced into the page. The caller passes the returned HTML
    to ``ghl_rest_canvas.edit_element_customcode`` (the in-browser autosave then
    lands it)."""
    _require(cdn_url, "cdn_url")
    low = cdn_url.strip().lower()
    if not (low.startswith("http://") or low.startswith("https://")):
        raise ValueError(
            f"cdn_url must be an http(s) URL (got {cdn_url!r}) — file:// / data: "
            "placeholders are refused; only the public GCS media URL is allowed"
        )
    alt_attr = alt.replace('"', "&quot;") if alt else ""
    return f'<img src="{cdn_url}" alt="{alt_attr}" loading="lazy">'


def build_image_manifest(records: list[dict], out_path: str | None = None) -> list[dict]:
    """Assemble + (optionally) write ``images/manifest.json``.

    Each input record maps one generated+uploaded image::

        {
            "id": "hero-soap-trio",
            "prompt": "<the full prompt incl. the English/Latin pin>",
            "file": "<RUN_DIR>/images/hero-soap-trio.png",
            "cdn_url": "https://storage.googleapis.com/msgsndr/...",  # PUBLIC, https
            "cdn_http_status": 200,                                   # verified 200
            "used_on_page_id": "PAGEID...",
            "file_id": "<ghl media fileId>"          # optional provenance
        }

    The contract is strict (per the spec): ``cdn_url`` MUST be ``https`` (no
    ``file://``, no placeholder note) and ``cdn_http_status`` MUST be 200. A record
    violating either is rejected LOUD — the manifest can only ever describe real,
    publicly-resolving images.

    Returns the validated list (and writes it to ``out_path`` when given).
    """
    if not isinstance(records, list) or not records:
        raise ValueError("records must be a non-empty list of image records")
    out: list[dict] = []
    for i, rec in enumerate(records):
        if not isinstance(rec, dict):
            raise ValueError(f"records[{i}] must be a dict")
        rid = str(rec.get("id", "")).strip()
        _require(rid, f"records[{i}].id")
        cdn_url = str(rec.get("cdn_url", "")).strip()
        if not cdn_url.lower().startswith("https://"):
            raise ValueError(
                f"records[{i}] ({rid}): cdn_url must be an https URL "
                f"(got {cdn_url!r}) — no file:// / placeholder is allowed"
            )
        status = rec.get("cdn_http_status")
        if status != 200:
            raise ValueError(
                f"records[{i}] ({rid}): cdn_http_status must be 200 "
                f"(got {status!r}) — the CDN URL must verify as a live 200"
            )
        entry = {
            "id": rid,
            "prompt": rec.get("prompt", ""),
            "file": rec.get("file", ""),
            "cdn_url": cdn_url,
            "cdn_http_status": 200,
            "used_on_page_id": rec.get("used_on_page_id", ""),
        }
        if "file_id" in rec:
            entry["file_id"] = rec["file_id"]
        out.append(entry)

    if out_path:
        Path(out_path).parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(out, f, indent=2)
    return out


__all__ = [
    "GHL_SERVICES_ORIGIN",
    "GHL_MEDIA_UPLOAD_PATH",
    "GHL_MEDIA_FOLDER_PATH",
    "GHL_MEDIA_VERSION",
    "create_media_folder",
    "ENGLISH_LATIN_PIN",
    "PNG_MAGIC",
    "kie_generate_path",
    "resolve_location_pit",
    "resolve_location_id",
    "build_prompts_json",
    "verify_png",
    "generate_images",
    "upload_media",
    "image_tag",
    "build_image_manifest",
]
