"""style_bibles.hybrid package: D21 Hybrid sketch-realism style bible.

Sketch (black-and-white Wimpy-Kid drawing) switches to realism (the D19
cinematic look read verbatim from style-bibles/realism-cinematic.md) and back,
ending in the warm golden realism finale. 2D-to-3D is never offered.
Stdlib only, no spend.
"""
from .hybrid_bible import (  # noqa: F401
    BANNED_STYLE_ALIASES,
    DISSOLVE_SECONDS,
    FINALE_BLOCK,
    GOLDEN_BEATS,
    HOLD_MIN_SECONDS,
    MODE_GOLDEN,
    MODE_REALISM,
    MODE_SKETCH,
    MODES,
    OFFERED,
    REALISM_BEATS,
    RECIPE_REQUIRED_PHRASES,
    SKETCH_BEATS,
    SKETCH_STYLE,
    SKETCH_STYLE_ID,
    SCHEMA_VERSION,
    HybridError,
    assert_offered,
    beat_mode,
    compile_prompt,
    enforce_finale,
    extract_recipe,
    find_recipe,
    offered_styles,
    plan_hybrid,
    realism_available,
    realism_block,
    realism_sha256,
    recipe_candidate_paths,
    sketch_style,
    validate_plan,
    validate_sketch,
)

__all__ = [
    "BANNED_STYLE_ALIASES",
    "DISSOLVE_SECONDS",
    "FINALE_BLOCK",
    "GOLDEN_BEATS",
    "HOLD_MIN_SECONDS",
    "MODE_GOLDEN",
    "MODE_REALISM",
    "MODE_SKETCH",
    "MODES",
    "OFFERED",
    "REALISM_BEATS",
    "RECIPE_REQUIRED_PHRASES",
    "SKETCH_BEATS",
    "SKETCH_STYLE",
    "SKETCH_STYLE_ID",
    "SCHEMA_VERSION",
    "HybridError",
    "assert_offered",
    "beat_mode",
    "compile_prompt",
    "enforce_finale",
    "extract_recipe",
    "find_recipe",
    "offered_styles",
    "plan_hybrid",
    "realism_available",
    "realism_block",
    "realism_sha256",
    "recipe_candidate_paths",
    "sketch_style",
    "validate_plan",
    "validate_sketch",
]
