"""no_echo package: D22a re-export of core audio_c3 for scripts/core/smp/.

One implementation lives in ``core/audio_c3/no_echo/no_echo.py`` (manual L1);
this package re-exports it so ``import no_echo`` under ``core/smp/`` keeps
resolving. Skill 74 stays the sole KIE path. Prompt/payload shaping and
verification only — no network, no media, no operator paths. stdlib only.
"""
from .no_echo import (  # noqa: F401
    BRIEF_NEGATIVE_TAGS,
    CARD_LINE,
    DOCS_LINE,
    DRY_RULE,
    KIND_SONG,
    KIND_VOICE_PACK,
    KIE_PATH,
    NEGATIVE_TAGS,
    NoEchoError,
    PROVIDER,
    REQUEST_KINDS,
    RULE_ID,
    RULE_TEXT,
    SCHEMA_VERSION,
    SPOKEN_BANNED_STYLE_WORDS,
    STYLE_TEXT_PATHS,
    TAG_LIST_TEXT,
    TOOL_VERSION,
    card_line,
    check,
    docs_line,
    main,
    negative_tags,
    refused_style_words,
    rule_text,
    song_request,
    stamp,
    voice_pack_request,
)

__all__ = [
    "BRIEF_NEGATIVE_TAGS",
    "CARD_LINE",
    "DOCS_LINE",
    "DRY_RULE",
    "KIND_SONG",
    "KIND_VOICE_PACK",
    "KIE_PATH",
    "NEGATIVE_TAGS",
    "NoEchoError",
    "PROVIDER",
    "REQUEST_KINDS",
    "RULE_ID",
    "RULE_TEXT",
    "SCHEMA_VERSION",
    "SPOKEN_BANNED_STYLE_WORDS",
    "STYLE_TEXT_PATHS",
    "TAG_LIST_TEXT",
    "TOOL_VERSION",
    "card_line",
    "check",
    "docs_line",
    "main",
    "negative_tags",
    "refused_style_words",
    "rule_text",
    "song_request",
    "stamp",
    "voice_pack_request",
]
