/**
 * Kie.ai Callback Worker -- Centralized operator fleet edge receiver
 *
 * Receives Kie.ai POST callbacks at:
 *   POST /cb?c=<clientSlug>&j=<submitId>&s=<callbackValidator>&h=<perTaskSecretHmac>
 *
 * Flow (Candidate B, transport B2 -- Worker-writes-to-KV, box-polls):
 *   1. Read X-Webhook-Timestamp + X-Webhook-Signature from headers
 *   2. Parse body to get taskId
 *   3. Verify HMAC-SHA256(taskId + "." + timestamp, webhookHmacKey) in constant time
 *   4. Check replay window (300 seconds -- policy choice; Kie does not define one)
 *   5. Check idempotency in KV (key: "idem:<taskId>", short TTL)
 *   6. Normalize result (handles 4o result_urls array OR Flux resultImageUrl/originImageUrl)
 *   7. Return 200 to Kie immediately (within the 15-second deadline)
 *   8. Write verified result to KV (key: "result:<clientSlug>:<submitId>") in waitUntil
 *      NOTE: KV stores perTaskSecretHmac (a hash), never the plaintext perTaskSecret.
 *   9. GET /healthz returns 200 with JSON for deploy verification
 *  10. GET /kv-read requires Authorization: Bearer <perClientKvReadToken> (fix F)
 *      and carries the perTaskSecret preimage in the X-Kie-Preimage header (fix G),
 *      never as a query param (query params land in edge access logs).
 *
 * KV bindings (wrangler.toml):
 *   KIE_CALLBACK_KV -- idempotency + result store
 *
 * Worker secrets (set via wrangler secret put) -- these are FLEET MASTER keys and
 * NEVER leave the Worker. Per-client credentials are DERIVED from them Worker-side
 * (fix F); each box only ever holds its own derived per-client value, so one
 * compromised box exposes only that one client, not the fleet.
 *   KIE_WEBHOOK_HMAC_KEY   -- the webhookHmacKey from https://kie.ai/settings
 *   KIE_CALLBACK_HMAC_KEY  -- fleet MASTER key. Per-client callback key is
 *                            HMAC-SHA256(clientSlug, MASTER) (fix F). Derives the
 *                            callback validator (fix D) + per-task-secret HMAC (fix C).
 *   KVREAD_TOKEN           -- fleet MASTER token. Per-client /kv-read bearer token is
 *                            HMAC-SHA256(clientSlug, MASTER) (fix F).
 *
 * Per-client derivation (fix F -- blast-radius containment):
 *   perClientCallbackKey  = HMAC-SHA256(clientSlug, KIE_CALLBACK_HMAC_KEY)  [hex]
 *   perClientKvReadToken  = HMAC-SHA256(clientSlug, KVREAD_TOKEN)           [hex]
 *   The operator computes these once per client and provisions ONLY the derived
 *   values onto the box (see DEPLOY.md). The Worker re-derives them on every
 *   request from the master + the c= slug and compares in constant time.
 *
 * callBackUrl params (generated by box, received from Kie at POST /cb):
 *   c=<clientSlug>      -- client identifier
 *   j=<submitId>        -- 128-bit random hex (fix A); never deckId_slideId
 *   s=<callbackValidator> -- HMAC-SHA256(clientSlug + ":" + submitId, perClientCallbackKey)
 *                           Nothing secret -- safe in logs (fix D + F)
 *   h=<perTaskSecretHmac> -- HMAC-SHA256(perTaskSecret, perClientCallbackKey)
 *                           A hash of the secret, not the secret (fix C). The Worker
 *                           stores this in KV; on /kv-read the box sends the preimage
 *                           (raw perTaskSecret) in the X-Kie-Preimage header (fix G)
 *                           and the Worker recomputes + compares.
 *
 * Security changes (2026-06-14 security-hardening pass):
 *   A. submitId is now a 128-bit random hex value generated on the box -- not guessable.
 *      Human-readable deckId/slideId labels are stored separately in the local registry.
 *   B. /kv-read requires Authorization: Bearer <KVREAD_TOKEN>; returns 401 if missing/wrong.
 *   C. perTaskSecret is never stored in KV nor returned over the wire. The callBackUrl
 *      carries HMAC-SHA256(perTaskSecret, KIE_CALLBACK_HMAC_KEY) as param h=. The Worker
 *      stores this HMAC in KV. On /kv-read the box sends the raw perTaskSecret as &p=;
 *      the Worker recomputes HMAC(preimage) in constant time and compares against stored.
 *      The plaintext perTaskSecret never sits in KV and is never returned in any response.
 *   D. callBackUrl no longer carries the raw perTaskSecret. The s= param is now
 *      HMAC-SHA256(clientSlug + ":" + submitId, KIE_CALLBACK_HMAC_KEY). The Worker
 *      recomputes and verifies in constant time on every POST /cb. Nothing secret
 *      traverses Kie or lands in server logs.
 *   E. Kie HMAC verification and idempotency/replay protection are unchanged.
 *   F. Per-client credential derivation (2026-07-05). The two shared secrets are now
 *      fleet MASTER keys that never leave the Worker. The callback key and the
 *      /kv-read bearer token are derived per client as HMAC-SHA256(clientSlug, MASTER).
 *      A box holds only its own derived values, so a single compromised box exposes
 *      exactly one client's callback path -- not the whole fleet (no commingling).
 *   G. The perTaskSecret preimage moved from the &p= query param to the X-Kie-Preimage
 *      header on /kv-read (2026-07-05). Query params are captured in edge/CDN access
 *      logs on every 2s poll; a request header is not. The plaintext secret still only
 *      ever travels over TLS to our own Worker and is never returned in any response.
 *
 * Security notes per DESIGN.md section 9:
 *   - HMAC covers only taskId.timestamp (Kie spec). Body integrity is NOT covered by Kie's sig.
 *   - Callback validator (s=) is the second factor binding callback to a submitted task.
 *   - Result URL host allowlist enforced before any box writes a download.
 *   - 300-second replay window is our policy, not a Kie-defined value.
 */

const REPLAY_WINDOW_SECONDS = 300; // policy choice -- Kie does not define a replay window

/** Constant-time byte comparison (avoids timing attacks) */
async function timingSafeEqual(a, b) {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) {
    diff |= a[i] ^ b[i];
  }
  return diff === 0;
}

/**
 * Compute HMAC-SHA256(message, keyMaterial) and return a lowercase hex string.
 * Used for: callback validator, perTaskSecretHmac, bearer token comparison.
 * keyMaterial may be a string or Uint8Array.
 */
async function hmacHex(message, keyMaterial) {
  const keyBytes = typeof keyMaterial === 'string'
    ? new TextEncoder().encode(keyMaterial)
    : keyMaterial;
  const cryptoKey = await crypto.subtle.importKey(
    'raw',
    keyBytes,
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  );
  const msgBytes = new TextEncoder().encode(message);
  const sigBytes = await crypto.subtle.sign('HMAC', cryptoKey, msgBytes);
  return Array.from(new Uint8Array(sigBytes)).map(b => b.toString(16).padStart(2, '0')).join('');
}

/**
 * Fix F: derive a per-client credential from a fleet master key and the client slug.
 * perClientCredential = HMAC-SHA256(clientSlug, masterKey) as lowercase hex.
 * Used for both the per-client callback key and the per-client /kv-read bearer token.
 * The master never leaves the Worker; a box only ever holds its own derived value.
 */
async function derivePerClient(masterKey, clientSlug) {
  return hmacHex(clientSlug, masterKey);
}

/**
 * Verify the Kie HMAC signature.
 * Algorithm: HMAC-SHA256(taskId + "." + timestamp, webhookHmacKey), base64-encoded.
 * Source: https://docs.kie.ai/common-api/webhook-verification (verified 2026-06-14)
 */
async function verifyKieSignature(taskId, timestamp, receivedSignature, hmacKey) {
  const message = `${taskId}.${timestamp}`;
  const enc = new TextEncoder();
  const keyBytes = enc.encode(hmacKey);
  const msgBytes = enc.encode(message);

  const cryptoKey = await crypto.subtle.importKey(
    'raw',
    keyBytes,
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  );

  const sigBytes = await crypto.subtle.sign('HMAC', cryptoKey, msgBytes);
  const expected = btoa(String.fromCharCode(...new Uint8Array(sigBytes)));

  // Constant-time compare
  const expectedBytes = new TextEncoder().encode(expected);
  const receivedBytes = new TextEncoder().encode(receivedSignature);
  return await timingSafeEqual(expectedBytes, receivedBytes);
}

/**
 * Normalize result URLs from either model family:
 *   4o family:   data.info.result_urls  (array of strings)
 *   Flux family: data.info.resultImageUrl + data.info.originImageUrl (strings)
 * Returns an array of URL strings.
 */
function extractResultUrls(data) {
  const info = data?.info || {};
  if (Array.isArray(info.result_urls) && info.result_urls.length > 0) {
    return info.result_urls.filter(Boolean);
  }
  const urls = [];
  if (info.resultImageUrl) urls.push(info.resultImageUrl);
  if (info.originImageUrl) urls.push(info.originImageUrl);
  return urls;
}

/**
 * KV read handler (B2 transport -- box polls this for verified callback result).
 *
 * Security (fixes B + C + F + G):
 *   B/F. Requires Authorization: Bearer <perClientKvReadToken>, where the per-client
 *        token is HMAC-SHA256(clientSlug, KVREAD_TOKEN master). Returns 401 on
 *        missing/wrong. The master KVREAD_TOKEN never leaves the Worker.
 *   C/G. Box sends the raw perTaskSecret in the X-Kie-Preimage header (fix G -- never a
 *        query param). Worker recomputes HMAC-SHA256(preimage, perClientCallbackKey)
 *        in constant time and compares against stored perTaskSecretHmac. Returns 403
 *        on mismatch. The response body NEVER includes perTaskSecretHmac or any secret.
 *
 * GET /kv-read?c=<clientSlug>&j=<submitId>
 * Authorization: Bearer <perClientKvReadToken>
 * X-Kie-Preimage: <perTaskSecretPreimage>
 *
 * Returns: { found: true, result: { taskId, clientSlug, submitId, code, msg, resultUrls,
 *                                   rawData, receivedAt } }
 *      or: { found: false }
 *
 * perTaskSecretHmac is intentionally absent from the response (fix C).
 */
async function handleKvRead(request, url, env) {
  // Read slug first -- required to derive the per-client credentials (fix F).
  const clientSlug            = url.searchParams.get('c');
  const submitId              = url.searchParams.get('j');
  // Fix G: preimage arrives in a header, not a query param (query params hit edge logs).
  const perTaskSecretPreimage = request.headers.get('x-kie-preimage') || '';

  if (!clientSlug || !submitId || !perTaskSecretPreimage) {
    return new Response(JSON.stringify({ found: false, error: 'missing params' }),
      { status: 400, headers: { 'Content-Type': 'application/json' } });
  }

  // Fix F: derive this client's /kv-read bearer token from the fleet master + slug.
  const kvReadMaster = env.KVREAD_TOKEN || '';
  const callbackMaster = env.KIE_CALLBACK_HMAC_KEY || '';
  if (!kvReadMaster || !callbackMaster) {
    console.error('KIE_KV: master secret(s) not configured -- refusing all /kv-read requests');
    return new Response(JSON.stringify({ error: 'server misconfiguration' }),
      { status: 500, headers: { 'Content-Type': 'application/json' } });
  }

  const perClientKvReadToken = await derivePerClient(kvReadMaster, clientSlug);

  // Fix B/F: authenticate with the per-client bearer token in constant time.
  const authHeader  = request.headers.get('Authorization') || '';
  const bearerToken = authHeader.startsWith('Bearer ') ? authHeader.slice(7) : '';

  const tokenValid = await timingSafeEqual(
    new TextEncoder().encode(perClientKvReadToken),
    new TextEncoder().encode(bearerToken)
  );
  if (!tokenValid) {
    return new Response(JSON.stringify({ error: 'unauthorized' }),
      { status: 401, headers: { 'Content-Type': 'application/json',
                                'WWW-Authenticate': 'Bearer realm="kie-callback"' } });
  }

  const kvKey = `result:${clientSlug}:${submitId}`;
  const value = await env.KIE_CALLBACK_KV.get(kvKey);
  if (!value) {
    return new Response(JSON.stringify({ found: false }),
      { headers: { 'Content-Type': 'application/json' } });
  }

  const stored = JSON.parse(value);

  // Fix C/F: validate the preimage against the stored HMAC using the per-client key.
  const perClientCallbackKey = await derivePerClient(callbackMaster, clientSlug);
  const expectedHmac = await hmacHex(perTaskSecretPreimage, perClientCallbackKey);
  const storedHmac   = stored.perTaskSecretHmac || '';

  const secretValid = await timingSafeEqual(
    new TextEncoder().encode(expectedHmac),
    new TextEncoder().encode(storedHmac)
  );
  if (!secretValid) {
    console.warn('KIE_KV: perTaskSecretHmac mismatch for submitId', submitId);
    return new Response(JSON.stringify({ found: false, error: 'secret mismatch' }),
      { status: 403, headers: { 'Content-Type': 'application/json' } });
  }

  // Fix C: strip perTaskSecretHmac from the response -- no secret leaves the Worker
  const { perTaskSecretHmac: _stripped, ...safeResult } = stored;

  return new Response(JSON.stringify({ found: true, result: safeResult }),
    { headers: { 'Content-Type': 'application/json' } });
}

/** Health check handler */
function handleHealth() {
  return new Response(JSON.stringify({
    status: 'ok',
    worker: 'kie-callback-relay',
    version: '1.1.0',
    timestamp: new Date().toISOString()
  }), {
    status: 200,
    headers: { 'Content-Type': 'application/json' }
  });
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    // Health check
    if (url.pathname === '/healthz') {
      return handleHealth();
    }

    // KV read endpoint (B2 transport): box polls for its result
    // GET /kv-read?c=<clientSlug>&j=<submitId>&p=<perTaskSecretPreimage>
    // Authorization: Bearer <KVREAD_TOKEN>
    if (request.method === 'GET' && url.pathname === '/kv-read') {
      return handleKvRead(request, url, env);
    }

    // Only accept POST to /cb
    if (request.method !== 'POST' || url.pathname !== '/cb') {
      return new Response('Not Found', { status: 404 });
    }

    // --- Parse query params ---
    const clientSlug        = url.searchParams.get('c');
    const submitId          = url.searchParams.get('j');
    // Fix D: s= is now a callback validator HMAC, not the raw perTaskSecret.
    //   Expected: HMAC-SHA256(clientSlug + ":" + submitId, KIE_CALLBACK_HMAC_KEY)
    const callbackValidator = url.searchParams.get('s');
    // Fix C: h= is HMAC-SHA256(perTaskSecret, KIE_CALLBACK_HMAC_KEY) -- a hash, not the secret.
    //   The Worker stores this in KV; validated against the preimage on /kv-read.
    const perTaskSecretHmac = url.searchParams.get('h');

    if (!clientSlug || !submitId || !callbackValidator || !perTaskSecretHmac) {
      // Return 200 to prevent Kie from retrying a permanently-bad URL,
      // but log the rejection
      console.error('KIE_CB: missing required query params',
        { clientSlug, submitId, hasValidator: !!callbackValidator, hasHmac: !!perTaskSecretHmac });
      return new Response('OK', { status: 200 });
    }

    // --- Read body ---
    let body;
    try {
      body = await request.json();
    } catch (err) {
      console.error('KIE_CB: body parse failed', err.message);
      return new Response('OK', { status: 200 }); // return 200; Kie must not retry bad payloads
    }

    // Kie sends taskId in data.taskId
    const taskId = body?.data?.taskId;
    if (!taskId) {
      console.error('KIE_CB: missing taskId in body', JSON.stringify(body).slice(0, 200));
      return new Response('OK', { status: 200 });
    }

    // --- Read HMAC verification headers ---
    const timestampHeader = request.headers.get('x-webhook-timestamp');
    const signatureHeader = request.headers.get('x-webhook-signature');

    if (!timestampHeader || !signatureHeader) {
      // HMAC is opt-in on Kie; if webhookHmacKey is configured we REQUIRE the headers.
      // Reject silently (return 200 so Kie does not retry; this is a misconfiguration).
      console.error('KIE_CB: missing HMAC headers for taskId', taskId);
      return new Response('OK', { status: 200 });
    }

    // --- Replay protection (policy: +/- 300 seconds; Kie does not define a window) ---
    const nowSeconds   = Math.floor(Date.now() / 1000);
    const msgTimestamp = parseInt(timestampHeader, 10);
    if (isNaN(msgTimestamp) || Math.abs(nowSeconds - msgTimestamp) > REPLAY_WINDOW_SECONDS) {
      console.warn('KIE_CB: replay/timestamp window exceeded for taskId', taskId,
        'delta', nowSeconds - msgTimestamp);
      return new Response('OK', { status: 200 });
    }

    // --- Kie HMAC verification (requires KIE_WEBHOOK_HMAC_KEY Worker secret) ---
    const hmacKey = env.KIE_WEBHOOK_HMAC_KEY;
    if (!hmacKey) {
      console.error('KIE_CB: KIE_WEBHOOK_HMAC_KEY secret not configured');
      return new Response('OK', { status: 200 });
    }

    const sigValid = await verifyKieSignature(taskId, timestampHeader, signatureHeader, hmacKey);
    if (!sigValid) {
      console.warn('KIE_CB: HMAC mismatch for taskId', taskId);
      return new Response('OK', { status: 200 }); // 200 to avoid infinite retries
    }

    // --- Fix D + F: verify the callback validator (s=) in constant time ---
    // Expected: HMAC-SHA256(clientSlug + ":" + submitId, perClientCallbackKey), where
    //   perClientCallbackKey = HMAC-SHA256(clientSlug, KIE_CALLBACK_HMAC_KEY master).
    // Unique per task (submitId is 128-bit random) AND per client (fix F), keyed by the
    // fleet master. Nothing in s= is the raw perTaskSecret, so nothing secret hits Kie logs.
    const callbackMaster = env.KIE_CALLBACK_HMAC_KEY;
    if (!callbackMaster) {
      console.error('KIE_CB: KIE_CALLBACK_HMAC_KEY secret not configured');
      return new Response('OK', { status: 200 });
    }

    const perClientCallbackKey = await derivePerClient(callbackMaster, clientSlug);
    const expectedValidator = await hmacHex(`${clientSlug}:${submitId}`, perClientCallbackKey);
    const validatorValid = await timingSafeEqual(
      new TextEncoder().encode(expectedValidator),
      new TextEncoder().encode(callbackValidator)
    );
    if (!validatorValid) {
      console.warn('KIE_CB: callback validator mismatch for submitId', submitId);
      return new Response('OK', { status: 200 }); // 200 to avoid Kie retries; our guard
    }

    // --- Idempotency check (KV key: "idem:<taskId>", TTL 24h) ---
    const idemKey  = `idem:${taskId}`;
    const existing = await env.KIE_CALLBACK_KV.get(idemKey);
    if (existing) {
      console.log('KIE_CB: duplicate callback dropped for taskId', taskId);
      return new Response('OK', { status: 200 }); // idempotent; already processed
    }

    // --- Mark idempotency immediately (before async work) ---
    // TTL: 86400 seconds (24 hours) -- long enough to absorb all Kie retries
    await env.KIE_CALLBACK_KV.put(idemKey, '1', { expirationTtl: 86400 });

    // Return 200 to Kie NOW -- within the 15-second deadline (Kie requirement)
    // Heavy KV write happens in waitUntil (async, non-blocking)
    ctx.waitUntil(writeResultToKV(env, {
      clientSlug,
      submitId,
      taskId,
      perTaskSecretHmac, // Fix C: store the HMAC (from h=), never the plaintext
      code: body.code,
      msg:  body.msg,
      resultUrls: extractResultUrls(body.data),
      rawData:    body.data,
      receivedAt: new Date().toISOString()
    }));

    return new Response('OK', { status: 200 });
  }
};

/**
 * Write verified result to KV for the box to pull.
 * Key pattern: "result:<clientSlug>:<submitId>"
 * TTL: 3600 seconds (1 hour) -- boxes should poll within seconds; 1h is ample
 *
 * Fix C: perTaskSecretHmac (HMAC-SHA256(perTaskSecret, KIE_CALLBACK_HMAC_KEY)) is stored
 * instead of the raw perTaskSecret. On /kv-read, the box sends the raw perTaskSecret as
 * &p=<preimage>; the Worker recomputes the HMAC and compares in constant time.
 * The plaintext perTaskSecret is never written to KV and never returned over the wire.
 */
async function writeResultToKV(env, result) {
  const kvKey  = `result:${result.clientSlug}:${result.submitId}`;
  const payload = JSON.stringify({
    taskId:           result.taskId,
    clientSlug:       result.clientSlug,
    submitId:         result.submitId,
    perTaskSecretHmac: result.perTaskSecretHmac, // Fix C: only the HMAC, never plaintext
    code:             result.code,
    msg:              result.msg,
    resultUrls:       result.resultUrls,
    rawData:          result.rawData,
    receivedAt:       result.receivedAt
  });

  // TTL: 3600s. The box polls this key every 2 seconds once a callback is expected.
  await env.KIE_CALLBACK_KV.put(kvKey, payload, { expirationTtl: 3600 });

  console.log('KIE_CB: result written to KV', kvKey, 'code', result.code,
    'urls', result.resultUrls.length);
}
