"""choice_card.stl_voice_guard: Sketch to Life is always All Suno (D25).

Owns the card's Voice row per look and the intake refusal for the one
forbidden pair -- Sketch to Life + Velvet Voiceover. Velvet Voiceover stays
offered on the other four looks; All Suno is the default on every look.
"""
from __future__ import annotations

from .stl_voice_guard import (  # noqa: F401
    ALL_SUNO_ID,
    ALL_SUNO_LABEL,
    CLIENT_REASON,
    DEFAULT_MODE,
    DEFAULT_VOICE_ID,
    LEGACY_VOICE_IDS,
    MODES,
    NEXT_ACTION_OK,
    NEXT_ACTION_REFUSED,
    REASK_ID,
    REASK_QUESTION,
    REASON_CODE,
    SCHEMA_VERSION,
    SOURCE,
    STL_LOOK_ID,
    STL_LOOK_LABEL,
    STL_OTHER_LOOKS,
    TOOL_NAME,
    TOOL_VERSION,
    VELVET_DISABLED_LABEL,
    VELVET_ID,
    VELVET_LABEL,
    VOICE_FIELD,
    VoiceError,
    StlGuardError,
    apply_voice,
    build_root,
    card_voice_block,
    guard,
    guard_intake,
    is_forbidden,
    normalize_voice_choice,
    resolve_look,
    selectable_voice_ids,
    velvet_offered_with,
    voice_line,
    voice_options_for,
)

__all__ = [
    "ALL_SUNO_ID",
    "ALL_SUNO_LABEL",
    "CLIENT_REASON",
    "DEFAULT_MODE",
    "DEFAULT_VOICE_ID",
    "LEGACY_VOICE_IDS",
    "MODES",
    "NEXT_ACTION_OK",
    "NEXT_ACTION_REFUSED",
    "REASK_ID",
    "REASK_QUESTION",
    "REASON_CODE",
    "SCHEMA_VERSION",
    "SOURCE",
    "STL_LOOK_ID",
    "STL_LOOK_LABEL",
    "STL_OTHER_LOOKS",
    "TOOL_NAME",
    "TOOL_VERSION",
    "VELVET_DISABLED_LABEL",
    "VELVET_ID",
    "VELVET_LABEL",
    "VOICE_FIELD",
    "VoiceError",
    "StlGuardError",
    "apply_voice",
    "build_root",
    "card_voice_block",
    "guard",
    "guard_intake",
    "is_forbidden",
    "normalize_voice_choice",
    "resolve_look",
    "selectable_voice_ids",
    "velvet_offered_with",
    "voice_line",
    "voice_options_for",
]
