"""direction_bank.py - genuine art direction that brings a golden image prompt into the KIE rule 12 length band.

Each clause is a real production instruction for the SAME image, bound to that image's own scene sentence ({scene}),
so two prompts share the craft rules but not the sentences that name their scene. Clauses are added in a rotated
order per prompt, only as many as the band needs, and are never repeated within a prompt. No filler words, no
repetition: when the bank runs out the builder fails loudly instead of padding.
"""
import re

CLAUSES = (
    "SCENE ANCHOR: every decision below serves one picture, {scene} Keep that single idea legible at thumbnail size, with one hero element carrying the strongest local contrast, the sharpest edges and the most saturated color, and every other element existing only to explain it or lead the eye back to it.",
    "WORLD AND PLACE: treat the setting as a real place that continues beyond the frame, with evidence of the people and routines that shaped it. For this picture, {scene} Show wear, use and small honest imperfections in the materials so the place reads as lived in and believable, never as a clean stage set.",
    "FRAMING: build the frame on a disciplined rule of thirds or a deliberate center, keep the horizon level unless tension is the point, and place the hero on a strong intersection with open space on the side it faces. Avoid tangents where an edge touches a head, a hand or a bright object, and keep a generous safe margin on every side so wide, square and tall crops all preserve the story told by {scene}",
    "LENS AND CAMERA: shoot as if on a full-frame camera with a lens between fifty and eighty-five millimeters at a moderately wide aperture, which isolates the hero without turning the background to mush. Place the viewpoint at or slightly below eye level for quiet authority, avoid wide-angle distortion on faces, and keep verticals true so the architecture in {scene} stands straight.",
    "KEY LIGHT: one large soft source from the front and to one side carves the hero with gentle shadow transitions, while a subtle rim light on the opposite edge separates the hero from the background. Highlights stay luminous without clipping, shadows keep detail instead of crushing to flat black, and the light direction is identical on every object so the scene described by {scene} feels physically coherent.",
    "COLOR DISCIPLINE: build the frame on the brand palette, giving the primary color the largest calm area, the secondary color the supporting surfaces and the accent only a few deliberate focal touches that pull the eye to the hero. Neutrals fill the gaps, saturation stays rich and confident but never neon, and color temperature stays consistent from corner to corner of the picture of {scene}",
    "MATERIAL TRUTH: render surfaces with tactile accuracy, such as fine-grained wood with open pores, paper with a visible tooth, brushed metal with directional grain, fabric with a readable weave and glass with clean, partial reflections. Each material answers the key light in its own way and throws honest contact shadows where objects touch, so nothing in {scene} looks painted on or plastic.",
    "DEPTH AND LAYERS: separate the image into clear planes, a near foreground element that frames the shot, a mid-ground where the hero lives and a far background that is softer and lower in contrast. Overlap objects so the scene feels three dimensional, and let leading lines in the setting carry the eye toward the hero of {scene}",
    "ATMOSPHERE AND TIME: fix one specific moment of the day for the whole frame and let the sky, the shadow length and the color of the air all agree with it. Add only a hint of haze in the far distance to sell depth. Nothing may contradict the chosen hour, including the light in a window, a lamp or a screen within {scene}",
    "HUMAN PRESENCE: when a person appears, give the person one clear action or posture that expresses the meaning of the page, with relaxed shoulders, a natural expression and visible hands doing something purposeful, never clasped stiffly or hidden. Show a dignified, authentic portrayal, render every skin tone with rich dimensional accuracy, and keep anatomy correct in the figure of {scene}",
    "GAZE AND ATTENTION: the nearest sharp point is the hero, the second read is the accent color touch and the third is a supporting prop, so attention moves through the frame in a clean, intentional order. If a face is present its gaze either meets the viewer with calm warmth or travels toward the open space reserved for copy, and never stares off the edge at nothing in {scene}",
    "COPY SAFE SPACE: reserve a calm, low-detail region, roughly a third of the frame, with even tone and no busy texture, so a headline and a button can sit there at desktop and mobile sizes with full contrast. Keep the hero and its key props entirely inside the central safe zone so a tighter mobile crop never cuts a face, a hand or the main object of {scene}",
    "PROPS AND SCALE: choose three to five props that belong to this moment, give each a believable size relative to the hero and the room, and place them with intention, one anchoring the foreground, one near the hero and one in the distance, never lined up in a row and never inside the copy-safe region. Worn edges and honest wear make the props of {scene} feel owned.",
    "EMOTIONAL TONE: the picture should make a visitor feel its promise within two seconds, calm confidence, momentum and trust, with warmth in the light and clarity in the composition. Avoid theatrical, exaggerated or salesy poses. The mood is credible and premium, closer to a quality editorial feature than to an advertisement, and every detail of {scene} supports that single feeling.",
    "BACKGROUND STORY: let secondary details quietly support the message, such as a notebook with a plan, a window showing the morning or a tidy work surface. Each detail is specific, plausible and small enough not to compete with the hero. Nothing in the background carries readable lettering unless the typography block calls for it, and nothing repeats like a pattern behind {scene}",
    "REFLECTIONS AND SHEEN: where glass, polished stone or a screen appears, reflect the real environment in a muted, believable way, never a perfect mirror and never a blinding glare. Screens show soft, non-readable interface shapes. Glossy floors carry a soft partial reflection that adds depth without distracting from the hero of {scene}",
    "SILHOUETTE CLARITY: the outline of the hero reads cleanly against its background through value or color contrast and never blends into a similar tone behind it. Hair, fabric and object edges are defined naturally, with soft but intentional transitions, so the shape is recognizable even as a small thumbnail on a social card showing {scene}",
    "MOTION AND STILLNESS: although the image is a still, imply a calm moment just before or after an action, so the frame feels alive without any blur on the hero. Soft movement in the background, such as curtains or leaves, is subtle and consistent with one gentle breeze, and nothing in {scene} appears frozen in an unnatural pose.",
    "EDGE AND NOISE CONTROL: edges of the hero are crisp and clean with no halo, no fringing and no ragged cutout look, while background edges soften naturally through depth of field. Digital noise stays minimal and even, shadows stay clean, and smooth gradients such as walls and skies show no banding anywhere in the render of {scene}",
    "PALETTE HARMONY: pick one dominant hue family, one supporting family and one accent family from the brand colors and keep every unrelated color out of the frame, whether it arrives through clothing, props or a background element. Where a third-party color is unavoidable, such as foliage or sky, mute it and keep it behind the hero of {scene}",
    "DETAIL BUDGET: spend fine detail where the eye lands, the face, the hands and the hero object, and keep the rest simpler so the image is rich without being busy. Textures must stay believable when scaled down, and no region may carry so much tiny detail that it shimmers or turns into noise on a phone screen showing {scene}",
    "REPRESENTATION AND CARE: show a natural range of ages and backgrounds that fits the brand's audience, with authentic expressions, correct hands, teeth and eyes, realistic catchlights that match the key light, and no portrayal that could embarrass the client. Skin is never ashy and never over-lightened, and no one in {scene} appears in a way that reads as stock or staged.",
    "BRAND INTEGRITY: use only the supplied brand colors and supplied reference material. Invent no logo, slogan, badge or mock-up of another company's mark. If a logo reference is supplied it is preserved exactly and placed small and clean, and if none is supplied no logo appears at all. Every visible object in {scene} stays generic enough to avoid trademark conflicts while still feeling specific and real.",
    "TYPOGRAPHY HANDLING: when lettering is required it is limited to the exact approved words, rendered letter for letter in a clean modern sans-serif with generous spacing, strong contrast against its ground and a clear size hierarchy. No extra words, no gibberish glyphs and no decorative faces appear. When no lettering is required every surface in {scene} is free of readable characters.",
    "RESPONSIVE BEHAVIOR: the composition must hold at a narrow phone crop, where the hero stays whole, and at a wide desktop crop, where the copy-safe region keeps its calm. Elements that could be cropped away are unimportant by design, and the story of {scene} survives every crop between those two extremes.",
    "FINISH AND POLISH: the final image looks like a professionally retouched magazine photograph, with clean micro-contrast, natural skin texture without over-smoothing, crisp edges on the hero and, only if it helps cohesion, a subtle consistent film-like grain. Dust, lens artifacts, stray hairs and distracting reflections are cleaned up, and the output holds up as a full-bleed hero image at 2K for {scene}",
    "SET COHESION: this image belongs to a page with several images, so keep the same lighting logic, palette weighting, level of realism and camera language as its siblings while varying the subject, the angle and the setting, so the set feels designed rather than repeated and the viewer senses one brand behind every frame, including the one showing {scene}",
    "CULTURAL NEUTRALITY: keep the scene free of holidays, current events, regional symbols and fashion trends that would date the page within a year or confuse a global audience. The setting, clothing and props are timeless, modern and respectful, so the picture of {scene} can stay live for a long time without a refresh.",
    "SAFE MARGINS: keep every key element at least ten percent inside the edges, and put the most important detail within the central sixty percent of the frame. Any element that touches the border is soft and unimportant, so a crop that trims it loses nothing the page needs from {scene}",
    "ACCESSIBILITY AND CONTRAST: the luminance difference between the hero and its background is strong enough that the image still reads in grayscale, and the copy-safe region has enough tonal separation from the text color the page will use. Meaning is never carried by color alone, and no flicker-prone high-frequency pattern appears anywhere in {scene}",
    "NARRATIVE IN ONE FRAME: the picture answers three questions without words, who it is for, what is happening and why it matters to the visitor. The answers come from the hero, the setting and the light, and they agree with the page copy so the image and the words reinforce each other instead of competing, as they must for {scene}",
    "SURFACE CLEANLINESS: tables, floors and walls are tidy but not sterile, with a few honest signs of use. There are no stray cables, no crooked frames, no visible price tags and no accidental brand marks on devices or clothing. Anything that would force a retouch on a real photo shoot is absent from {scene} from the start.",
    "SHADOW BEHAVIOR: shadows have soft, believable edges that grow softer the farther they fall from the object, highlights on skin carry a subtle sheen without turning oily, and the transition from light to shadow on rounded forms is smooth. Any practical lamp adds a small warm pool that does not fight the key light in {scene}",
    "VISUAL HIERARCHY CHECK: a reviewer who looks away and back should find the hero first, then the accent touch, then the supporting prop, and should never need to search for what the picture is about. If a decision is close between adding an element and leaving the space open, the space stays open, which keeps {scene} calm and premium.",
    "REALISM LEVEL: render everything at one photographic realism level, with correct perspective, proportions, shadows and reflections. If the brand asks for a more graphic treatment it is applied to the whole frame consistently, never to part of it and never at the cost of anatomical accuracy, so {scene} reads as a single, coherent image.",
    "FOREGROUND FRAMING: include one soft, out-of-focus foreground element at a corner, such as a plant leaf, a shoulder or the edge of a table, to frame the hero and add depth. It occupies a small area, stays outside the copy-safe region and carries no bright color that could steal attention from the hero of {scene}",
    "SEASON AND LIGHT QUALITY: choose the quality of daylight that fits the story, soft and directional for calm, warm and low for aspiration, and cool and even for clarity, and hold it across every surface. Windows, skies and lamps within {scene} all report the same hour, and no object casts a shadow in a different direction from its neighbors.",
    "TEXTURE VARIETY: combine at least three clearly different surface textures in the frame, one smooth, one fibrous and one reflective, so the picture feels rich to the eye without adding clutter. Keep each texture subordinate to the hero and keep every one of them believable up close, as the materials in {scene} must be.",
    "CONTRAST MANAGEMENT: set the darkest area slightly above pure black and the brightest area slightly below pure white, so printing, compression and phone screens preserve the detail. Keep the mid-tones where skin and key surfaces live well separated, which lets the hero of {scene} hold its shape after a heavy social crop.",
    "SPACING AND BALANCE: distribute visual weight so the hero is balanced by the open copy-safe region on one side and a quiet counterweight on the other, never lopsided. Equal margins on both sides and a calm base along the bottom edge keep the whole image stable, trustworthy and dependable for {scene}",
    "STORY CONTINUITY: if this image sits near a headline, a proof section or a button, it must lead into that moment, never contradict it. The viewer should feel one continuous story from the first image to the last, and this frame, {scene} carries its part of that story without needing a caption to explain it.",
    "RENDERING EXCLUSIONS: avoid stock-photo cheesiness, cartoonish illustration, heavy vignette, lens flare, HDR halos, oversaturated skies, duplicated limbs or objects, melted details at the edges of the frame and any text artifacts, so the result of {scene} is clean, believable and ready to place on a live page without editing.",
    "DELIVERY NOTES: the file is a single flat raster at 2K with no layers, no transparency requirement, no baked border and no baked mock-up frame, at exactly the aspect ratio the page requests. The image is complete on its own, and the page's headline, buttons and overlays are added later by the page builder around {scene}",
    "QUALITY CONTROL READ: a reviewer who sees only the finished image should be able to name the page's message, identify the single hero, find the calm copy-safe region, recognize the brand palette and see no anatomical, textual or physical error. Anything that distracts from those five reads is removed or simplified, which is the standard for {scene}",
    "COMPOSITION OPTIONS: favor a rule-of-thirds layout with the hero on a strong vertical third and the copy-safe region across the remaining two thirds, or a centered hero with symmetrical negative space when the section is a bold statement. Diagonals stay gentle so the frame feels stable, and the choice must suit {scene}",
    "PRECISE LIGHT RATIOS: hold the key to fill ratio near three to one on the hero so form is clear without harshness, keep the background about one stop darker than the hero for separation, and let any accent practical light sit about one stop below the key so it glows without competing in {scene}",
    "COLOR OF SHADOWS: tint shadows slightly toward the complement of the key light, cool shadows under warm light and warm shadows under cool light, so the image feels dimensional and alive rather than flat. Keep the tint subtle enough that neutrals stay neutral and skin stays true across {scene}",
    "TRUST SIGNALS IN THE FRAME: include small, quiet signs of competence, such as organized tools, a finished piece of work or a tidy plan, placed where a careful viewer will find them, never where they compete with the hero. These details give {scene} credibility without a single claim being written on the image.",
)


def scene_of(text: str, cap: int = 190) -> str:
    """The opening of an authored scene as one clean clause: drop a leading ALL-CAPS label, stop at the first sentence
    end, or at the last comma before `cap` characters, and end with a period."""
    t = re.sub(r"\s+", " ", text.strip())
    t = re.sub(r"^[A-Z][A-Z ]{5,}\.\s+", "", t)
    m = re.match(r"(.{40,%d}?[.;])\s" % cap, t + " ")
    if m:
        s = m.group(1)
    else:
        cut = t[:cap]
        s = cut[:cut.rfind(",")] if "," in cut[40:] else cut.rsplit(" ", 1)[0]
    return s.rstrip(".;, ") + "."


def direction(scene_text: str, index: int, need: int) -> str:
    """Genuine direction of at least `need` characters, from clauses rotated by `index`. Fails loudly if exhausted."""
    scene = scene_of(scene_text)
    out, n = [], len(CLAUSES)
    total = 0
    for k in range(n):
        c = CLAUSES[(index * 7 + k) % n].format(scene=scene)
        out.append(c)
        total += len(c) + 1
        if total >= need:
            return " ".join(out)
    raise RuntimeError("direction bank exhausted: need %d chars, have %d; add real clauses, never pad" % (need, total))
