"""style_bibles.canvas_to_3d package: D21/D29 Canvas to 3D style bible.

A 2D hand-painted cartoon opening switches to lifelike 3D cinematic CGI and
back -- the Version E recipe, offered by the owner 2026-10-07. Switch on
matching poses or framings, 0.3-0.4 s dissolve (0.4 s per Version E), hold
each style at least 3 s (7.2 s per Version E), identity lock across both
halves, lip-sync only on short front-facing lifelike 3D close-ups. Realism
and the golden-realism finale belong to the other hybrid looks and never
appear here. stdlib only, no spend.
"""
from .canvas_3d_bible import (  # noqa: F401
    BANNED_PROMPT_PHRASES,
    BANNED_STYLE_ALIASES,
    DISSOLVE_SECONDS,
    HOLD_MIN_SECONDS,
    IDENTITY_FIELDS,
    LIFELIKE_3D_STYLE,
    LOOK_ID,
    MODE_3D,
    MODE_PAINTED,
    MODES,
    OFFERED,
    PAINTED_BEATS,
    PAINTED_STYLE,
    PAINTED_STYLE_ID,
    RECEIPT_ENV_VAR,
    RECEIPT_FILENAME,
    SCHEMA_VERSION,
    THREED_BEATS,
    THREED_STYLE_ID,
    VERSION_E_DISSOLVE_SECONDS,
    VERSION_E_MIN_HOLD_SECONDS,
    VERSION_E_MODES,
    VERSION_E_SWITCHES_S,
    Canvas3DError,
    assert_identity_lock,
    assert_offered,
    assert_version_e,
    beat_mode,
    compile_prompt,
    dissolve_seconds,
    find_receipt,
    identity_errors,
    identity_fingerprint,
    identity_lock,
    offered_look,
    plan_switches,
    receipt_candidate_paths,
    style_block,
    style_record,
    switch_match,
    validate_3d,
    validate_painted,
    validate_plan,
    version_e_errors,
    version_e_schedule,
)

__all__ = [
    "BANNED_PROMPT_PHRASES",
    "BANNED_STYLE_ALIASES",
    "DISSOLVE_SECONDS",
    "HOLD_MIN_SECONDS",
    "IDENTITY_FIELDS",
    "LIFELIKE_3D_STYLE",
    "LOOK_ID",
    "MODE_3D",
    "MODE_PAINTED",
    "MODES",
    "OFFERED",
    "PAINTED_BEATS",
    "PAINTED_STYLE",
    "PAINTED_STYLE_ID",
    "RECEIPT_ENV_VAR",
    "RECEIPT_FILENAME",
    "SCHEMA_VERSION",
    "THREED_BEATS",
    "THREED_STYLE_ID",
    "VERSION_E_DISSOLVE_SECONDS",
    "VERSION_E_MIN_HOLD_SECONDS",
    "VERSION_E_MODES",
    "VERSION_E_SWITCHES_S",
    "Canvas3DError",
    "assert_identity_lock",
    "assert_offered",
    "assert_version_e",
    "beat_mode",
    "compile_prompt",
    "dissolve_seconds",
    "find_receipt",
    "identity_errors",
    "identity_fingerprint",
    "identity_lock",
    "offered_look",
    "plan_switches",
    "receipt_candidate_paths",
    "style_block",
    "style_record",
    "switch_match",
    "validate_3d",
    "validate_painted",
    "validate_plan",
    "version_e_errors",
    "version_e_schedule",
]
