#!/usr/bin/env python3
"""ghl_media.py — T2 REAL IMAGE PIPELINE for the Skill-06 funnel/website builder.

WHAT THIS IS
------------
The build path the spec assumes is: the page copy drives REAL, on-brand raster
images (generated by the repo's verified KIE.ai tooling), those PNGs are uploaded
to the GoHighLevel media library (which returns a PUBLIC, login-free GCS object
URL), and the in-page custom-code element is rewritten to reference that CDN URL
via the proven token-id autosave (``ghl_rest_canvas.edit_element_customcode`` +
``page_autosave``). This module owns the deterministic, mechanical halves of that
pipeline so they are never improvised:

  1. ``build_prompts_json(copy_specs, ...)`` — mechanically derive the KIE
     ``prompts.json`` (one entry per image) from the page copy, with the
     mandatory English/Latin-only pin appended to EVERY prompt verbatim.
  2. ``generate_images(prompts_path, out_dir, ...)`` — a thin wrapper that shells
     the canonical ``kie_generate.py`` (REUSED AS-IS — never forked). It submits,
     polls, downloads, and PNG-magic-byte-verifies; this wrapper only locates the
     tool, runs it, and reports which ``<slide>.png`` files landed (+ re-asserts
     the PNG magic bytes itself, so a non-PNG can never be passed downstream).
  3. ``upload_media(png_path, location_id, name, pit, ...)`` — ports the PROVEN
     ``POST services.leadconnectorhq.com/medias/upload-file`` Bearer-PIT call from
     ``37-zhc-closeout/scripts/upload-ghl-media.sh`` to Python, returning
     ``{fileId, url}`` where ``url`` is the PUBLIC ``storage.googleapis.com/msgsndr/...``
     GCS object URL (openable with NO login — that is the real ``cdn_url``).
  4. ``image_tag(cdn_url, alt)`` + ``build_image_manifest(...)`` — the in-page
     ``<img>`` snippet and the ``images/manifest.json`` output contract.

AUTH-MODEL SPLIT (LOAD-BEARING — this module sits ENTIRELY on the bare-Python side)
-----------------------------------------------------------------------------------
  * KIE.ai (``api.kie.ai``) and the GHL MEDIA upload (``services.leadconnectorhq.com``
    + ``Authorization: Bearer <LOCATION PIT>``) are NOT behind the funnels-builder
    Cloudflare interstitial, so they run from bare Python. This module makes those
    calls directly (KIE via the reused subprocess; media via ``urllib``).
  * The IN-PAGE write that references the CDN URL (``/funnels/builder/autosave``)
    IS Cloudflare-WAF-gated (1010 from bare Python) and MUST run inside the
    agent-browser eval. This module does NOT make that call — it only produces the
    edited blob + the ``<img>`` snippet; ``ghl_rest_canvas.page_autosave`` (driven
    by ``ghl_builder.emit_rest_save_plan``) executes it in-browser.

KEYS — OPERATOR'S OWN, NEVER A CLIENT'S
---------------------------------------
``KIE_API_KEY`` is read by the reused ``kie_generate.py`` from the environment or
the standard env stores. The GHL LOCATION Private Integration Token (PIT) is read
by ``resolve_location_pit`` from EVERY known LOCATION-class env-var alias
(``GOHIGHLEVEL_API_KEY`` preferred → ``GHL_API_KEY`` → ``GOHIGHLEVEL_LOCATION_PIT``
→ ``GHL_LOCATION_PIT``) AND — when the live env is empty — the canonical env
STORES (``~/.openclaw/secrets/.env`` → ``~/clawd/secrets/.env`` →
``~/.openclaw/workspace/.env``), so a clean agent shell can never false-fail on a
token that physically lives in the store. It NEVER falls back to an AGENCY-class
PIT (``*_AGENCY_PIT``/``*_AGENCY_API_KEY``) — agency tokens 401 for media. The
location id is resolved the same way by ``resolve_location_id``
(``GOHIGHLEVEL_LOCATION_ID`` → ``GHL_LOCATION_ID`` → the ``*_ALLOWED_LOCATION_IDS``
single-id fallbacks → the same stores). In THIS phase the keys are the operator's
own fixture keys; a client key must never appear here.

NO-FABRICATION / FAIL-LOUD
--------------------------
Every step fails LOUD rather than substitute a placeholder: a non-PNG download
raises (never an SVG stub); a missing key raises (never a ``file://`` cdn_url); an
upload that returns no ``fileId``/``url`` raises (never a fake CDN URL). The
``images/manifest.json`` contract therefore can only ever carry real ``https``
``cdn_url`` values with a verified HTTP status.
"""

from __future__ import annotations

import json
import logging
import mimetypes
import os
import re
import subprocess
import sys
import urllib.error
import urllib.request
import uuid
from pathlib import Path
from typing import Any, Callable

logger = logging.getLogger(__name__)

# ── Constants (ported from the PROVEN upload-ghl-media.sh + kie_generate.py) ──

# Media upload lives on the services.* origin (Bearer PIT) — NOT WAF-gated, so
# this runs from bare Python. (The funnels/builder autosave that REFERENCES the
# returned URL is WAF-gated and runs in-browser; that is NOT this module.)
GHL_SERVICES_ORIGIN = "https://services.leadconnectorhq.com"
GHL_MEDIA_UPLOAD_PATH = "/medias/upload-file"
# Per-run folder create endpoint (Skill 48 addition). Lets each ad-run's images land
# in their own named folder; the "upload to root with a name prefix" fallback
# (media_folder_name_prefix) covers a GHL plan that does not expose this endpoint.
GHL_MEDIA_FOLDER_PATH = "/medias/folder"
GHL_MEDIA_VERSION = "2021-07-28"

# The mandatory English/Latin-only pin — appended VERBATIM to every prompt that
# renders copy (carried verbatim from kie_generate.py's module docstring so the
# generator and this builder agree on the exact text).
ENGLISH_LATIN_PIN = (
    "All text rendered in the image MUST be in English, Latin alphabet ONLY. NO "
    "Chinese/CJK or non-Latin characters anywhere. Render the copy spelled "
    "correctly, letter-for-letter. No garbled, misspelled, or invented text."
)

# The NO-TEXT pin — appended VERBATIM to every prompt whose spec is NOT
# ``text_bearing``. FIX-IMG-09 (ii): the English/Latin pin was previously
# appended to EVERY prompt, including photographic no-text scenes, which
# ironically INVITES gpt-image-2 to render (correctly-spelled) text where none
# was wanted. A no-text section must instead be told, unambiguously, to render
# no lettering at all; only text-bearing sections carry the spelling pin.
TEXT_ABSENT_PIN = (
    "Absolutely no text, lettering, words, captions, watermarks, logos with "
    "text, or typography of any kind anywhere in the image."
)

# Minimum stripped length (characters, excluding the appended pin) of an image
# prompt before it may reach a PAID Kie call. FIX-XC-04f (d): Skill 6 previously
# fabricated a ~200-char generic hero prompt; a prompt that thin can never carry
# the 8-block, brand-graded direction a real page image needs. ``build_prompts_json``
# raises ``ValueError`` when ``enforce_floor=True`` and a prompt is below this
# floor, so a weak prompt physically cannot reach the paid generator. The build
# path (``ghl_image_stage.run_image_pipeline``) always enforces it.
PROMPT_CHAR_FLOOR = 1500

# PNG magic bytes — a real raster starts with these. A non-PNG download is a hard
# FAIL (never stubbed). Mirrors the verify in kie_generate.py.
PNG_MAGIC = b"\x89PNG\r\n\x1a\n"

# Canonical location of the REUSED (never forked) KIE generator, relative to this
# file (.../06-ghl-install-pages/tools/ -> repo root -> 23-.../kie_generate.py).
_KIE_GENERATE_RELPATH = os.path.join(
    "..", "..", "23-ai-workforce-blueprint", "templates",
    "presentation-render", "kie_generate.py",
)

# ── GHL credential resolution — multi-alias, multi-store (NEVER false-fail) ───
#
# WHY THIS EXISTS (the six-month false-fail incident)
# ---------------------------------------------------
# The image step once raised "GHL LOCATION PIT not found" on a token the operator
# had used for SIX MONTHS. Root cause: the resolver checked ONLY two env-var names
# in the LIVE process environment and never opened the canonical secrets store. In
# an agent shell where the gateway/launchd wrapper had NOT exported secrets/.env,
# both vars read empty and the tool fail-loud — even though the value was sitting
# in ``~/.openclaw/secrets/.env`` under the very name it checks (GOHIGHLEVEL_API_KEY).
#
# The fix below mirrors the proven multi-alias pattern already used for the Google
# key (3 aliases, one value) and the KIE key store-fallback in ``ghl_image_stage``:
#   1. resolve from EVERY known LOCATION-class alias, in preference order;
#   2. if the live env is empty, parse the canonical env STORES directly
#      (``~/.openclaw/secrets/.env`` → ``~/clawd/secrets/.env`` →
#       ``~/.openclaw/workspace/.env``) — the same files the rest of the skill names;
#   3. ONLY declare a credential missing AFTER all aliases × all stores are exhausted,
#      and when it does, the error NAMES exactly which vars and which store paths it
#      checked, and tells the agent to ``source`` the store.
#
# AGENCY vs LOCATION (load-bearing distinction)
# ---------------------------------------------
# GHL has TWO token classes, distinguished PURELY by env-var NAME (both literally
# start with "pit-", so the value prefix does not distinguish them):
#   * LOCATION-level PIT  → has ``medias.write`` scope → media upload SUCCEEDS.
#   * AGENCY-level  PIT   → NO media scope → media upload 401s "not authorized".
# This resolver resolves ONLY from LOCATION-class names and NEVER falls back to an
# AGENCY-class name — silently using an agency PIT would turn a clean "not found"
# into a confusing 401 at upload time. The agency names are listed (``_AGENCY_PIT_ENV_NAMES``)
# solely so the error message can say "I saw an agency PIT but it is NOT media-scoped".

# Canonical LOCATION-PIT env-var aliases, in preference order. GOHIGHLEVEL_API_KEY
# is the legacy name the closeout script (upload-ghl-media.sh) and the live
# openclaw.json ghl-mcp config both use for the LOCATION PIT; GHL_API_KEY is the
# short alias; GOHIGHLEVEL_LOCATION_PIT / GHL_LOCATION_PIT are explicit names for
# the same LOCATION token.
_PIT_ENV_NAMES = (
    "GOHIGHLEVEL_API_KEY",             # preferred — the LOCATION PIT (medias.write); matches openclaw.json + upload-ghl-media.sh
    "GHL_API_KEY",                     # legacy short alias for the same LOCATION PIT
    "GHL_PIT",                         # canonical short alias
    "GHL_TOKEN",                       # alternate alias
    "GHL_PRIVATE_INTEGRATION_TOKEN",   # explicit full-name alias
    "PRIVATE_INTEGRATION_TOKEN",       # bare PIT alias (some client envs use this)
    "GHL_PRIVATE_TOKEN",               # shortened private-token alias
    "PIT_TOKEN",                       # short PIT alias
    "GHL_PIT_TOKEN",                   # combined PIT alias
    "GOHIGHLEVEL_LOCATION_PIT",        # explicit LOCATION-PIT name (future-proof alias)
    "GHL_LOCATION_PIT",                # explicit LOCATION-PIT short alias
)
# GHL PIT aliases: see TERMINOLOGY.md for the canonical alias set and backend-equivalence notes.

# AGENCY-class names — NEVER used for media (they 401). Listed only so the
# fail-loud message can distinguish "no token at all" from "only an agency token".
_AGENCY_PIT_ENV_NAMES = (
    "GOHIGHLEVEL_AGENCY_PIT",
    "GOHIGHLEVEL_AGENCY_API_KEY",
    "GOHIGHLEVEL_CONVERTANDFLOW_AGENCY_PIT",
    "GHL_AGENCY_PIT",
)

# Canonical GHL location-id env-var aliases, in preference order.
_LOCATION_ENV_NAMES = (
    "GOHIGHLEVEL_LOCATION_ID",   # preferred — matches openclaw.json + secrets/.env
    "GHL_LOCATION_ID",           # short alias
    "GOHIGHLEVEL_ALLOWED_LOCATION_IDS",  # single-location allowlist fallback (first id)
    "CAF_ALLOWED_LOCATION_IDS",          # Skill-44 allowlist fallback (first id)
)

# Canonical env STORES, searched in order when the live process environment is
# empty for a credential. These are exactly the files the gateway/launchd wrapper
# sources upstream in a real fleet build (and that ghl_image_stage already reads
# for KIE_API_KEY); we read them directly so a clean agent shell can never produce
# a false "credential not found" for a value that physically lives in the store.
_GHL_ENV_STORES = (
    "~/.openclaw/secrets/.env",   # canonical operator secrets store (the PIT + location id live here)
    "~/clawd/secrets/.env",       # symlink target / alternate operator store
    "~/.openclaw/workspace/.env", # workspace-scoped overrides
)


def _scan_env_stores(names: tuple[str, ...]) -> tuple[str, str] | None:
    """Search the canonical env STORES for the first non-empty value of any of
    ``names``, in (name-preference × store-order) priority.

    Returns ``(value, "<NAME> in <store_path>")`` for provenance, or ``None`` when
    no store defines any of the names. NEVER raises — a missing/unreadable store is
    simply skipped (the caller decides whether absence is fatal).

    A store line is parsed as ``KEY=VALUE`` (``export KEY=VALUE`` also accepted);
    surrounding quotes are stripped; ``#`` comment lines are ignored. For an
    allowlist-style value (comma-separated ids) the FIRST id is returned (callers
    that pass *_ALLOWED_LOCATION_IDS rely on this to pick a single location)."""
    # Preference is by NAME first (so GOHIGHLEVEL_API_KEY in a later store still
    # beats GHL_API_KEY in an earlier store — the preferred alias always wins).
    for name in names:
        for store_path in _GHL_ENV_STORES:
            expanded = os.path.expanduser(store_path)
            if not os.path.isfile(expanded):
                continue
            try:
                with open(expanded, encoding="utf-8", errors="replace") as fh:
                    for line in fh:
                        line = line.strip()
                        if not line or line.startswith("#") or "=" not in line:
                            continue
                        if line.startswith("export "):
                            line = line[len("export "):].lstrip()
                        k, _, v = line.partition("=")
                        if k.strip() != name:
                            continue
                        v = v.strip().strip("'\"").strip()
                        # An allowlist value may be a comma list — take the first id.
                        if "," in v:
                            v = v.split(",", 1)[0].strip()
                        if v:
                            return v, f"{name} in {store_path}"
            except OSError:
                continue
    return None


# ── small helpers ─────────────────────────────────────────────────────────────

def _require(value: Any, name: str) -> None:
    """Reject empty / whitespace-only required values (fail loud, never silently
    proceed with a blank that would target the wrong resource)."""
    if value is None or (isinstance(value, str) and not value.strip()):
        raise ValueError(f"{name} is required and must be non-empty")


def kie_generate_path() -> str:
    """Absolute path to the canonical ``kie_generate.py`` (REUSED AS-IS).

    Resolved relative to this module so the wrapper works regardless of the
    caller's working directory. Raises if the reused tool is not where the repo
    layout puts it (fail loud rather than silently skip image generation)."""
    path = os.path.normpath(os.path.join(os.path.dirname(__file__), _KIE_GENERATE_RELPATH))
    if not os.path.isfile(path):
        raise FileNotFoundError(
            f"reused KIE generator not found at {path!r} — expected the repo's "
            "23-ai-workforce-blueprint/templates/presentation-render/kie_generate.py"
        )
    return path


def resolve_location_pit(env: dict | None = None, *, search_stores: bool = True) -> str:
    """Resolve the GHL LOCATION Private Integration Token (media-scoped).

    Resolution order (REAL research before any honest-fail):
      1. The live process environment, across EVERY LOCATION-class alias in
         ``_PIT_ENV_NAMES`` (``GOHIGHLEVEL_API_KEY`` preferred, then ``GHL_API_KEY``,
         then the explicit ``*_LOCATION_PIT`` names) — preferred alias wins.
      2. If the live env is empty, the canonical env STORES in ``_GHL_ENV_STORES``
         (``~/.openclaw/secrets/.env`` → ``~/clawd/secrets/.env`` →
          ``~/.openclaw/workspace/.env``) are parsed directly — the SAME file the
         rest of this skill names. This is what makes a clean agent shell (where the
         gateway never exported secrets/.env) resolve the real token instead of
         false-failing on an empty env var.

    The LOCATION PIT is what media upload REQUIRES (``medias.write`` scope); an
    AGENCY PIT 401s for media, so this NEVER falls back to an agency-class name.

    Only after every alias × every store is exhausted does it raise — and the error
    NAMES exactly which env vars and which store paths were checked, and tells the
    caller to ``source`` the store. If the search found an AGENCY PIT but no LOCATION
    PIT, the message says so explicitly (that is a scope problem, not a missing-token
    problem).

    Args:
        env: env mapping to read (default ``os.environ``).
        search_stores: when True (default) fall back to parsing the canonical env
            stores; tests set False to assert the pure-env behaviour in isolation.

    Raises:
        RuntimeError: the LOCATION PIT was not found in ANY alias in the live env
            NOR in any canonical store — with the full list of what was checked.
    """
    env = env if env is not None else os.environ

    # 1) Live process environment — every LOCATION-class alias, preferred first.
    for name in _PIT_ENV_NAMES:
        val = str(env.get(name, "")).strip().strip("'\"")
        if val:
            return val

    # 2) Canonical env stores (the value physically lives here in a real install).
    if search_stores:
        hit = _scan_env_stores(_PIT_ENV_NAMES)
        if hit:
            return hit[0]

    # 3) Genuinely absent — fail loud, naming EVERYTHING that was checked.
    agency_seen = any(str(env.get(n, "")).strip() for n in _AGENCY_PIT_ENV_NAMES)
    if search_stores and not agency_seen:
        agency_seen = _scan_env_stores(_AGENCY_PIT_ENV_NAMES) is not None
    agency_note = (
        " An AGENCY PIT WAS found, but the agency token is NOT media-scoped (it "
        "401s on media uploads) — set the LOCATION PIT instead."
        if agency_seen else ""
    )
    raise RuntimeError(
        "GHL LOCATION PIT not found IN THE ENVIRONMENT or in any canonical env "
        "store. Checked env vars (LOCATION-class, in order): "
        f"{', '.join(_PIT_ENV_NAMES)}. Checked stores: "
        f"{', '.join(_GHL_ENV_STORES)}. "
        "The LOCATION Private Integration Token normally lives in "
        "~/.openclaw/secrets/.env under GOHIGHLEVEL_API_KEY — load it first "
        "(e.g. `set -a; source ~/.openclaw/secrets/.env; set +a`) and retry. "
        "Media uploads REQUIRE the LOCATION PIT (medias.write scope); the AGENCY "
        f"PIT 401s for media.{agency_note}"
    )


def resolve_location_id(env: dict | None = None, *, search_stores: bool = True) -> str:
    """Resolve the GHL location id (the media/sub-account location).

    Same robust resolution order as ``resolve_location_pit``: every alias in
    ``_LOCATION_ENV_NAMES`` across the live env first (``GOHIGHLEVEL_LOCATION_ID``
    preferred, then ``GHL_LOCATION_ID``, then the ``*_ALLOWED_LOCATION_IDS`` single-id
    fallbacks), THEN the canonical env stores. Only after both are exhausted does it
    raise, naming exactly which vars and stores were checked.

    Args:
        env: env mapping to read (default ``os.environ``).
        search_stores: when True (default) fall back to parsing the canonical env
            stores; tests set False to assert pure-env behaviour in isolation.

    Raises:
        RuntimeError: the location id was not found in any alias nor any store —
            with the full list of what was checked.
    """
    env = env if env is not None else os.environ

    # 1) Live env — every alias, preferred first. An allowlist value may be a comma
    #    list; take the first id (single-location builds pin one id).
    for name in _LOCATION_ENV_NAMES:
        val = str(env.get(name, "")).strip().strip("'\"")
        if "," in val:
            val = val.split(",", 1)[0].strip()
        if val:
            return val

    # 2) Canonical env stores.
    if search_stores:
        hit = _scan_env_stores(_LOCATION_ENV_NAMES)
        if hit:
            return hit[0]

    raise RuntimeError(
        "GHL location id not found IN THE ENVIRONMENT or in any canonical env "
        "store. Checked env vars (in order): "
        f"{', '.join(_LOCATION_ENV_NAMES)}. Checked stores: "
        f"{', '.join(_GHL_ENV_STORES)}. "
        "The location id normally lives in ~/.openclaw/secrets/.env under "
        "GOHIGHLEVEL_LOCATION_ID — load it first "
        "(e.g. `set -a; source ~/.openclaw/secrets/.env; set +a`) and retry."
    )


# ── 1) build_prompts_json — derive the KIE prompts from the page copy ─────────

def build_prompts_json(
    copy_specs: list[dict],
    out_path: str | None = None,
    *,
    default_mode: str = "t2i",
    enforce_floor: bool = False,
) -> list[dict]:
    """Mechanically build the KIE ``prompts.json`` array from page-copy specs.

    Each ``copy_specs`` entry describes ONE image the page needs and is shaped::

        {
            "id": "hero-soap-trio",          # the slide id (becomes <id>.png)
            "prompt": "<copy-derived scene>", # the visual brief from the page copy
            "mode": "t2i",                    # optional; default_mode otherwise
            "input_urls": ["https://..."],    # required ONLY when mode == "i2i"
            "used_on_page_id": "PAGEID...",   # optional provenance (carried through)
            "alt": "...",                     # optional <img> alt text
            "text_bearing": False,            # optional; True => copy renders IN the image
            "locator": {"section_idx": 0, "element_idx": 2}  # optional splice target
        }

    The output array matches what ``kie_generate.py`` consumes
    (``[{"slide", "prompt", "mode", ["input_urls"]}]``) and appends a mandatory
    pin to EVERY prompt verbatim (idempotent — never doubled): the
    ``ENGLISH_LATIN_PIN`` spelling pin when the spec is ``text_bearing``, else the
    ``TEXT_ABSENT_PIN`` (a photographic section is told to render NO text at all
    rather than being invited to spell nonexistent copy).
    ``t2i`` (``gpt-image-2-text-to-image``) is the default because the fictional
    brand has no logo to seed image-to-image; an ``i2i`` entry MUST carry
    ``input_urls`` (the generator enforces this too).

    The build-time fields the generator ignores (``used_on_page_id``, ``alt``,
    ``locator``) are preserved on the returned objects so the caller can map each
    rendered PNG back to its page element after generation, but they are stripped
    before the file is written (the file is exactly what ``kie_generate.py`` wants).

    Args:
        copy_specs: The list of per-image copy specs (above).
        out_path: When given, the generator-shaped array is written there as JSON
            (the file ``kie_generate.py`` is then pointed at).
        default_mode: Fallback mode for entries that omit ``mode`` (default
            ``"t2i"``).
        enforce_floor: When True, every prompt's CONTENT (measured before the pin
            is appended) must be at least ``PROMPT_CHAR_FLOOR`` characters or a
            ``ValueError`` is raised. Default False so the mechanical unit tests of
            pin/mode/dup behaviour are unaffected; the paid build path
            (``ghl_image_stage.run_image_pipeline``) always passes True, which is
            what makes it impossible for a weak prompt to reach a paid Kie call.

    Returns:
        The list of ENRICHED prompt dicts (generator fields + carried-through
        build-time fields). The on-disk file (when ``out_path`` is given) carries
        only the generator fields.

    Raises:
        ValueError: empty specs, a missing/blank ``id`` or ``prompt``, a duplicate
            ``id``, an unknown ``mode``, an ``i2i`` entry without ``input_urls``,
            or (when ``enforce_floor``) a prompt below ``PROMPT_CHAR_FLOOR``.
    """
    if not isinstance(copy_specs, list) or not copy_specs:
        raise ValueError("copy_specs must be a non-empty list of image specs")

    enriched: list[dict] = []
    file_entries: list[dict] = []
    seen_ids: set[str] = set()

    for i, spec in enumerate(copy_specs):
        if not isinstance(spec, dict):
            raise ValueError(f"copy_specs[{i}] must be a dict")
        slide_id = str(spec.get("id", "")).strip()
        _require(slide_id, f"copy_specs[{i}].id")
        if slide_id in seen_ids:
            raise ValueError(f"duplicate image id {slide_id!r} in copy_specs")
        seen_ids.add(slide_id)

        prompt = str(spec.get("prompt", "")).strip()
        _require(prompt, f"copy_specs[{i}].prompt ({slide_id})")

        mode = str(spec.get("mode", default_mode)).strip().lower()
        if mode not in ("t2i", "i2i"):
            raise ValueError(
                f"copy_specs[{i}] ({slide_id}): mode must be 't2i' or 'i2i' (got {mode!r})"
            )

        # FIX-XC-04f (d): the FLOOR is measured on the creative prompt CONTENT —
        # BEFORE any boilerplate pin is appended — so the pin can never inflate a
        # thin prompt over the bar. A weak prompt then physically cannot reach a
        # paid Kie call (the build path passes enforce_floor=True).
        content_len = len(prompt.strip())

        # FIX-IMG-09 (ii): pick the pin by whether the spec renders copy.
        #   * text_bearing spec  → the English/Latin SPELLING pin (render text
        #     correctly, Latin only) so on-image copy is not garbled/CJK.
        #   * non-text spec      → the NO-TEXT pin, so a photographic scene is not
        #     seeded with unwanted (however well-spelled) lettering.
        # Both are appended VERBATIM and idempotently (never doubled).
        text_bearing = bool(spec.get("text_bearing"))
        pin = ENGLISH_LATIN_PIN if text_bearing else TEXT_ABSENT_PIN
        if pin not in prompt:
            prompt = f"{prompt} {pin}"

        if enforce_floor and content_len < PROMPT_CHAR_FLOOR:
            raise ValueError(
                f"copy_specs[{i}] ({slide_id}): prompt content is {content_len} "
                f"chars, below the PROMPT_CHAR_FLOOR of {PROMPT_CHAR_FLOOR} "
                "(measured before the pin). A prompt this thin is refused so it "
                "can never reach a paid Kie call — build an 8-block, brand-graded "
                "prompt (see ghl_image_stage._derive_copy_specs)."
            )

        # Generator-shaped entry (exactly what kie_generate.py consumes).
        gen_entry: dict[str, Any] = {"slide": slide_id, "prompt": prompt, "mode": mode}
        if mode == "i2i":
            input_urls = spec.get("input_urls") or []
            if not isinstance(input_urls, list) or not input_urls:
                raise ValueError(
                    f"copy_specs[{i}] ({slide_id}): mode=i2i requires a non-empty "
                    "input_urls list (set mode=t2i if there is no reference image)"
                )
            gen_entry["input_urls"] = list(input_urls)
        file_entries.append(gen_entry)

        # Enriched object the caller keeps for post-gen mapping.
        out_obj = dict(gen_entry)
        if "used_on_page_id" in spec:
            out_obj["used_on_page_id"] = spec["used_on_page_id"]
        if "alt" in spec:
            out_obj["alt"] = spec["alt"]
        if "locator" in spec:
            out_obj["locator"] = spec["locator"]
        enriched.append(out_obj)

    if out_path:
        Path(out_path).parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(file_entries, f, indent=2)

    return enriched


# ── 2) generate_images — thin wrapper over the REUSED kie_generate.py ─────────

def verify_png(path: str) -> bool:
    """True iff ``path`` exists and starts with the PNG magic bytes.

    Re-asserted here (independently of the generator's own check) so a non-PNG
    can never be passed downstream into the manifest / page splice."""
    p = Path(path)
    if not p.is_file() or p.stat().st_size < len(PNG_MAGIC):
        return False
    with open(p, "rb") as f:
        return f.read(len(PNG_MAGIC)) == PNG_MAGIC


def generate_images(
    prompts_path: str,
    out_dir: str,
    *,
    expected_ids: list[str] | None = None,
    runner: Callable[[list[str]], int] | None = None,
    python_exe: str | None = None,
) -> dict:
    """Shell the canonical ``kie_generate.py`` (REUSED AS-IS) to generate + verify
    the rasters, then confirm each expected ``<id>.png`` landed and is a real PNG.

    This wrapper does NOT re-implement KIE submit/poll/download — it locates the
    proven tool, runs ``python3 kie_generate.py <prompts_path> <out_dir>`` (which
    handles waves/rate-cap, polling, the CDN download, and its own PNG-magic-byte
    verify, exiting 0 only when ALL slides downloaded), then independently
    re-verifies the PNG magic bytes of each output. Injectable ``runner`` keeps it
    unit-testable WITHOUT any live KIE call (the live run is a later phase).

    Args:
        prompts_path: The generator ``prompts.json`` (from ``build_prompts_json``).
        out_dir: Directory where ``<slide>.png`` files are written.
        expected_ids: The slide ids that MUST be present as ``<id>.png`` after the
            run (defaults to the ids parsed from ``prompts_path``).
        runner: Optional callable taking the argv list and returning the process
            exit code (default = real ``subprocess.run``). Tests inject a fake that
            writes PNG fixtures + returns 0 — NO live network.
        python_exe: Python interpreter for the subprocess (default ``sys.executable``).

    Returns:
        ``{ok, exit_code, out_dir, images: [{id, file, png_verified, bytes}],
        missing, subprocess_timeout}``. ``ok`` is True iff the generator exited 0
        AND every expected PNG verified. ``subprocess_timeout`` is the prompt-count-
        scaled cap actually applied (FIX-IMG-08), for the run evidence log.

    Raises:
        ValueError: empty/missing ``prompts_path``.
        FileNotFoundError: the reused generator is absent.
    """
    _require(prompts_path, "prompts_path")
    if not os.path.isfile(prompts_path):
        raise ValueError(f"prompts_path does not exist: {prompts_path}")
    Path(out_dir).mkdir(parents=True, exist_ok=True)

    if expected_ids is None:
        entries = json.load(open(prompts_path))
        expected_ids = [str(e.get("slide", "")).strip() for e in entries if e.get("slide")]

    gen = kie_generate_path()  # raises if the reused tool is missing
    argv = [python_exe or sys.executable, gen, prompts_path, out_dir]

    # FIX-IMG-08: the flat 1800 s (30 min) cap KILLED large image sets mid-run,
    # orphaning already-PAID images. KIE generates in rate-capped waves, so wall
    # time scales with the number of prompts. Scale the cap by prompt count —
    # 5 min base + 2 min per prompt, never below the old 1800 s floor — so a big
    # multi-section page can finish. KIE_SUBPROCESS_TIMEOUT still overrides. The
    # computed cap is logged into run evidence (also returned in the result).
    n_prompts = len(expected_ids)
    _scaled_timeout = max(1800, 300 + 120 * n_prompts)
    _kie_timeout = int(os.environ.get("KIE_SUBPROCESS_TIMEOUT", str(_scaled_timeout)))
    logger.info(
        "KIE subprocess timeout cap = %ds (%d prompt(s); scaled=%ds, env-override=%s)",
        _kie_timeout, n_prompts, _scaled_timeout,
        os.environ.get("KIE_SUBPROCESS_TIMEOUT", "<none>"),
    )

    if runner is None:
        try:
            proc = subprocess.run(argv, capture_output=True, text=True, timeout=_kie_timeout)
            exit_code = proc.returncode
        except subprocess.TimeoutExpired:
            exit_code = 1
    else:
        exit_code = int(runner(argv))

    images: list[dict] = []
    missing: list[str] = []
    for sid in expected_ids:
        png = os.path.join(out_dir, f"{sid}.png")
        ok_png = verify_png(png)
        if ok_png:
            images.append({
                "id": sid,
                "file": png,
                "png_verified": True,
                "bytes": os.path.getsize(png),
            })
        else:
            missing.append(sid)

    return {
        "ok": exit_code == 0 and not missing,
        "exit_code": exit_code,
        "out_dir": out_dir,
        "images": images,
        "missing": missing,
        "subprocess_timeout": _kie_timeout,  # FIX-IMG-08: scaled cap (run evidence)
    }


# ── 3) upload_media — PROVEN services.* Bearer-PIT media upload (bare Python) ──

def _multipart_encode(fields: dict[str, str], file_field: str, file_path: str) -> tuple[bytes, str]:
    """Encode ``multipart/form-data`` for the media upload (one file + text fields).

    Returns ``(body_bytes, content_type)``. Mirrors the curl ``-F`` form the proven
    shell script sends: ``file=@<path>``, ``locationId``, ``name``, ``hosted`` (and
    optional ``parentId``). A small, dependency-free encoder so the upload runs on
    stock Python (no ``requests``)."""
    boundary = f"----ghlmedia{uuid.uuid4().hex}"
    crlf = b"\r\n"
    out: list[bytes] = []
    for key, val in fields.items():
        out.append(b"--" + boundary.encode())
        out.append(f'Content-Disposition: form-data; name="{key}"'.encode())
        out.append(b"")
        out.append(str(val).encode("utf-8"))
    # The file part.
    fname = os.path.basename(file_path)
    ctype = mimetypes.guess_type(fname)[0] or "application/octet-stream"
    with open(file_path, "rb") as f:
        file_bytes = f.read()
    out.append(b"--" + boundary.encode())
    out.append(
        f'Content-Disposition: form-data; name="{file_field}"; filename="{fname}"'.encode()
    )
    out.append(f"Content-Type: {ctype}".encode())
    out.append(b"")
    body = crlf.join(out) + crlf + file_bytes + crlf
    body += b"--" + boundary.encode() + b"--" + crlf
    return body, f"multipart/form-data; boundary={boundary}"


def upload_media(
    png_path: str,
    location_id: str,
    name: str,
    pit: str,
    *,
    hosted: bool = False,
    parent_id: str | None = None,
    timeout: int = 300,
    opener: Callable[[urllib.request.Request, int], Any] | None = None,
) -> dict:
    """Upload one media file to the GHL media library and return ``{fileId, url}``.

    Ports the PROVEN call from ``37-zhc-closeout/scripts/upload-ghl-media.sh``:
    ``POST services.leadconnectorhq.com/medias/upload-file`` with
    ``Authorization: Bearer <LOCATION PIT>`` + ``Version: 2021-07-28`` and the
    multipart fields ``file`` / ``locationId`` / ``name`` / ``hosted`` (+ optional
    ``parentId`` FOLDER id — the field is ``parentId``, NOT ``folderId``). The
    response ``url`` is a PUBLIC ``storage.googleapis.com/msgsndr/...`` GCS object
    URL — openable with NO login. THAT public URL is the real ``cdn_url`` the page
    references.

    This is on the bare-Python side of the auth split (services.* + Bearer PIT is
    NOT Cloudflare-WAF-gated). FAIL-LOUD: a non-2xx response, or a 2xx with no
    ``fileId``/``url``, raises (we never fabricate a CDN URL).

    Args:
        png_path: Local PNG to upload (must be a real PNG — re-verified).
        location_id: The GHL sub-account location id (fixture ``Mct54...``).
        name: Human-friendly media-library name.
        pit: The LOCATION Private Integration Token (Bearer).
        hosted: The ``hosted`` form field (default False).
        parent_id: Optional FOLDER id (``parentId``); files land in the media root
            when omitted (still fully shareable).
        timeout: HTTP timeout seconds (uploads can be large).
        opener: Optional callable ``(Request, timeout) -> response-like`` for tests
            (mock the HTTP). Default = ``urllib.request.urlopen`` (real call).

    Returns:
        ``{fileId, url, name, local_path, http}`` — ``url`` is the public GCS URL.

    Raises:
        ValueError: missing args or a non-PNG file.
        RuntimeError: non-2xx HTTP, or a 2xx response missing ``fileId``/``url``.
    """
    _require(png_path, "png_path")
    _require(location_id, "location_id")
    _require(name, "name")
    _require(pit, "pit")
    if not verify_png(png_path):
        raise ValueError(
            f"refusing to upload {png_path!r}: not a valid PNG (magic-byte check "
            "failed) — only real generated rasters are uploaded, never a stub"
        )

    fields: dict[str, str] = {
        "locationId": location_id,
        "name": name,
        "hosted": "true" if hosted else "false",
    }
    if parent_id:
        fields["parentId"] = parent_id  # documented folder field is parentId

    body, content_type = _multipart_encode(fields, "file", png_path)
    url = GHL_SERVICES_ORIGIN.rstrip("/") + GHL_MEDIA_UPLOAD_PATH
    req = urllib.request.Request(url, data=body, method="POST")
    req.add_header("Authorization", f"Bearer {pit}")
    req.add_header("Version", GHL_MEDIA_VERSION)
    req.add_header("Content-Type", content_type)

    _opener = opener or (lambda r, t: urllib.request.urlopen(r, timeout=t))
    try:
        resp = _opener(req, timeout)
        code = resp.getcode()
        raw = resp.read()
        if isinstance(raw, bytes):
            raw = raw.decode("utf-8", "replace")
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", "replace") if hasattr(exc, "read") else ""
        raise RuntimeError(
            f"media upload HTTP {exc.code} for {name!r}: {detail[:300]} "
            "(media uploads REQUIRE the LOCATION PIT with medias.write scope; "
            "the Agency PIT 401s)"
        ) from exc

    if not (200 <= int(code) < 300):
        raise RuntimeError(f"media upload returned HTTP {code} for {name!r}: {raw[:300]}")

    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise RuntimeError(
            f"media upload {code} but body is not JSON for {name!r}: {raw[:300]}"
        ) from exc

    file_id = data.get("fileId") or data.get("id")
    public_url = data.get("url") or data.get("fileUrl")
    if not file_id or not public_url:
        raise RuntimeError(
            f"media upload {code} but response missing fileId/url for {name!r}: "
            f"{json.dumps(data)[:300]} — refusing to fabricate a CDN URL"
        )

    return {
        "fileId": file_id,
        "url": public_url,
        "name": name,
        "local_path": png_path,
        "http": int(code),
    }


# ── 3b) create_media_folder — per-run named folder (Skill 48 addition) ────────

def media_folder_name_prefix(folder_name: str) -> str:
    """The FALLBACK namespacing when a real media folder cannot be created.

    GHL media has no hard nested-folder requirement, so when ``create_media_folder``
    cannot make a folder (an older plan / a non-2xx folder endpoint), a run's images
    can still be grouped + kept findable by prepending this slug to every uploaded
    file ``name`` (e.g. ``fbad-run-20260625__hero.png``). Returns ``"<slug>__"``.

    Raises ValueError on an empty name (fail loud — never silently un-namespace)."""
    _require(folder_name, "folder_name")
    slug = re.sub(r"[^A-Za-z0-9._-]+", "-", folder_name.strip()).strip("-")
    if not slug:
        raise ValueError(f"folder_name {folder_name!r} reduced to an empty slug")
    return f"{slug}__"


def create_media_folder(
    name: str,
    location_id: str,
    pit: str,
    *,
    parent_id: str | None = None,
    timeout: int = 60,
    opener: Callable[[urllib.request.Request, int], Any] | None = None,
) -> dict:
    """Create a named folder in the GHL media library and return ``{folderId, name, http}``.

    ``POST services.leadconnectorhq.com/medias/folder`` with
    ``Authorization: Bearer <LOCATION PIT>`` + ``Version: 2021-07-28`` and a JSON body
    ``{name, altType:"location", altId:<locationId>, parentId?}``. Media operations
    REQUIRE the LOCATION Private Integration Token (the Agency PIT 401s), and it must be
    the CLIENT'S OWN location PIT — never the operator's key.

    A per-run folder groups one ad-run's 10 finished images under one named, login-free,
    shareable set. The returned ``folderId`` is passed as ``parent_id`` to
    ``upload_media`` so each image lands inside the run's folder.

    Sits on the bare-Python side of the auth split (``services.*`` + Bearer PIT is NOT
    Cloudflare-WAF-gated), exactly like ``upload_media``.

    FAIL-LOUD: a non-2xx response, or a 2xx with no recognizable folder id, raises (we
    never fabricate a folder id). When the deployment's GHL plan does not expose a folder
    endpoint, the caller catches the ``RuntimeError`` and falls back to uploading into the
    media ROOT with ``media_folder_name_prefix(name)`` prepended to each file ``name``
    (still grouped + still shareable).

    Args:
        name: Human-friendly folder name (e.g. the campaign / run id).
        location_id: The GHL sub-account location id.
        pit: The LOCATION Private Integration Token (Bearer) with ``medias.write`` scope.
        parent_id: Optional parent folder id to nest under.
        timeout: HTTP timeout seconds.
        opener: Optional ``(Request, timeout) -> response-like`` for tests (mock the HTTP).
            Default = ``urllib.request.urlopen`` (real call).

    Returns:
        ``{folderId, name, http}`` — ``folderId`` is the real GHL media folder id.

    Raises:
        ValueError: missing required args.
        RuntimeError: non-2xx HTTP, a 2xx that is not JSON, or a 2xx missing a folder id
            (the signal for the caller to use the name-prefix fallback).
    """
    _require(name, "name")
    _require(location_id, "location_id")
    _require(pit, "pit")

    payload: dict[str, Any] = {
        "name": name,
        "altType": "location",
        "altId": location_id,
    }
    if parent_id:
        payload["parentId"] = parent_id

    body = json.dumps(payload).encode("utf-8")
    url = GHL_SERVICES_ORIGIN.rstrip("/") + GHL_MEDIA_FOLDER_PATH
    req = urllib.request.Request(url, data=body, method="POST")
    req.add_header("Authorization", f"Bearer {pit}")
    req.add_header("Version", GHL_MEDIA_VERSION)
    req.add_header("Content-Type", "application/json")
    req.add_header("Accept", "application/json")

    _opener = opener or (lambda r, t: urllib.request.urlopen(r, timeout=t))
    try:
        resp = _opener(req, timeout)
        code = resp.getcode()
        raw = resp.read()
        if isinstance(raw, bytes):
            raw = raw.decode("utf-8", "replace")
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", "replace") if hasattr(exc, "read") else ""
        raise RuntimeError(
            f"media folder create HTTP {exc.code} for {name!r}: {detail[:300]} "
            "(media ops REQUIRE the LOCATION PIT with medias.write scope; the Agency PIT "
            "401s). If the folder endpoint is unavailable on this plan, fall back to "
            "uploading into the media root with media_folder_name_prefix(name)."
        ) from exc

    if not (200 <= int(code) < 300):
        raise RuntimeError(
            f"media folder create returned HTTP {code} for {name!r}: {raw[:300]} — "
            "fall back to the name-prefix path."
        )

    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise RuntimeError(
            f"media folder create {code} but body is not JSON for {name!r}: {raw[:300]}"
        ) from exc

    folder_id = (
        data.get("folderId")
        or data.get("id")
        or data.get("_id")
        or (data.get("folder") or {}).get("id")
        or (data.get("media") or {}).get("id")
    )
    if not folder_id:
        raise RuntimeError(
            f"media folder create {code} but response missing a folder id for {name!r}: "
            f"{json.dumps(data)[:300]} — refusing to fabricate a folder id; use the "
            "media_folder_name_prefix fallback."
        )

    return {"folderId": folder_id, "name": name, "http": int(code)}


# ── 3c) folder-per-funnel media discipline (transcript §3, ~01:14–02:42) ──────
#
# Trevor's media-storage rule: ONE clearly-named folder PER funnel/website, with
# SUBFOLDERS as needed — "clear organization is the main point." NO browser
# control for media storage; folders are made via this services.* + Bearer-PIT
# path (API / MCP / Skill 44), never by driving the page builder UI. The funnel's
# images then live grouped under that one folder, and each page's assets can land
# in a per-page subfolder, so a built funnel's media is findable and shareable.

def funnel_media_folder_plan(funnel_name: str, page_names: list[str] | None = None) -> dict:
    """PURE planner for the folder-per-funnel structure (no I/O, no network).

    Returns the intended media-storage layout for a funnel/website:
    one top-level folder named after the (ZHC-prefixed) funnel, plus an optional
    per-page subfolder for each page. Names are passed through verbatim (the
    builder already ZHC-prefixes them); ``ensure_funnel_media_folders`` is the
    side-effecting counterpart that actually creates them.

    Args:
        funnel_name: The funnel/website name (already ZHC-prefixed by the builder).
        page_names: Optional per-page names → one subfolder each (blank/dupes dropped).

    Returns:
        ``{"folder": <funnel folder name>, "subfolders": [<page subfolder names>]}``.
    """
    _require(funnel_name, "funnel_name")
    folder = funnel_name.strip()
    subs: list[str] = []
    seen: set[str] = set()
    for p in (page_names or []):
        name = str(p).strip()
        if not name or name.lower() in seen:
            continue
        seen.add(name.lower())
        subs.append(name)
    return {"folder": folder, "subfolders": subs}


def ensure_funnel_media_folders(
    funnel_name: str,
    location_id: str,
    pit: str,
    *,
    page_names: list[str] | None = None,
    timeout: int = 60,
    opener: Callable[[urllib.request.Request, int], Any] | None = None,
) -> dict:
    """Create ONE media folder for a funnel/website (+ optional per-page subfolders).

    The transcript §3 discipline made operable: a single named funnel folder via
    ``create_media_folder`` on the ``services.*`` + Bearer-LOCATION-PIT path (NOT
    browser-routed), then each page's subfolder nested under it (``parentId`` =
    the funnel folder id). FAIL-SOFT: if the GHL plan does not expose the folder
    endpoint (``create_media_folder`` raises ``RuntimeError``), the funnel still
    stays organized via the ``media_folder_name_prefix`` fallback — each image's
    ``name`` is prefixed with the funnel slug (and per-page slug) instead. Media
    upload then passes ``parent_id`` (real folder) OR the name prefix (fallback).

    Args:
        funnel_name: The funnel/website name (already ZHC-prefixed by the builder).
        location_id: The GHL sub-account location id.
        pit: The LOCATION Private Integration Token (Bearer, ``medias.write``).
        page_names: Optional per-page names → one subfolder each.
        timeout / opener: forwarded to ``create_media_folder`` (opener for tests).

    Returns:
        ``{"mode": "folders"|"name-prefix", "funnel": {...}, "pages": {<page>: {...}},
        "browser_routed": False}``. In ``folders`` mode each entry carries a real
        ``folderId`` (pass as ``upload_media(parent_id=...)``). In ``name-prefix``
        mode each entry carries a ``name_prefix`` (prepend to each file ``name``).
    """
    _require(funnel_name, "funnel_name")
    _require(location_id, "location_id")
    _require(pit, "pit")
    plan = funnel_media_folder_plan(funnel_name, page_names)

    try:
        funnel_folder = create_media_folder(
            plan["folder"], location_id, pit, timeout=timeout, opener=opener
        )
    except RuntimeError:
        # Endpoint unavailable on this plan → name-prefix fallback (still grouped).
        pages_pfx = {
            sub: {"name_prefix": media_folder_name_prefix(f"{plan['folder']} {sub}")}
            for sub in plan["subfolders"]
        }
        return {
            "mode": "name-prefix",
            "funnel": {"name_prefix": media_folder_name_prefix(plan["folder"])},
            "pages": pages_pfx,
            "browser_routed": False,
        }

    pages: dict[str, dict] = {}
    for sub in plan["subfolders"]:
        try:
            pages[sub] = create_media_folder(
                sub, location_id, pit,
                parent_id=funnel_folder["folderId"], timeout=timeout, opener=opener,
            )
        except RuntimeError:
            # A subfolder failure is non-fatal: keep the funnel folder, prefix the page.
            pages[sub] = {"name_prefix": media_folder_name_prefix(f"{plan['folder']} {sub}")}

    return {
        "mode": "folders",
        "funnel": funnel_folder,
        "pages": pages,
        "browser_routed": False,
    }


# ── 4) in-page <img> snippet + the images/manifest.json output contract ───────

def image_tag(cdn_url: str, alt: str = "") -> str:
    """Return the ``<img>`` snippet that references the PUBLIC CDN URL in-page.

    The ``cdn_url`` MUST be an ``http(s)`` URL (the public GCS object URL from
    ``upload_media``) — a ``file://`` or SVG-data placeholder is REFUSED, so a
    stub can never be spliced into the page. The caller passes the returned HTML
    to ``ghl_rest_canvas.edit_element_customcode`` (the in-browser autosave then
    lands it)."""
    _require(cdn_url, "cdn_url")
    low = cdn_url.strip().lower()
    if not (low.startswith("http://") or low.startswith("https://")):
        raise ValueError(
            f"cdn_url must be an http(s) URL (got {cdn_url!r}) — file:// / data: "
            "placeholders are refused; only the public GCS media URL is allowed"
        )
    alt_attr = alt.replace('"', "&quot;") if alt else ""
    return f'<img src="{cdn_url}" alt="{alt_attr}" loading="lazy">'


def build_image_manifest(records: list[dict], out_path: str | None = None) -> list[dict]:
    """Assemble + (optionally) write ``images/manifest.json``.

    Each input record maps one generated+uploaded image::

        {
            "id": "hero-soap-trio",
            "prompt": "<the full prompt incl. the English/Latin pin>",
            "file": "<RUN_DIR>/images/hero-soap-trio.png",
            "cdn_url": "https://storage.googleapis.com/msgsndr/...",  # PUBLIC, https
            "cdn_http_status": 200,                                   # verified 200
            "used_on_page_id": "PAGEID...",
            "file_id": "<ghl media fileId>"          # optional provenance
        }

    The contract is strict (per the spec): ``cdn_url`` MUST be ``https`` (no
    ``file://``, no placeholder note) and ``cdn_http_status`` MUST be 200. A record
    violating either is rejected LOUD — the manifest can only ever describe real,
    publicly-resolving images.

    Returns the validated list (and writes it to ``out_path`` when given).
    """
    if not isinstance(records, list) or not records:
        raise ValueError("records must be a non-empty list of image records")
    out: list[dict] = []
    for i, rec in enumerate(records):
        if not isinstance(rec, dict):
            raise ValueError(f"records[{i}] must be a dict")
        rid = str(rec.get("id", "")).strip()
        _require(rid, f"records[{i}].id")
        cdn_url = str(rec.get("cdn_url", "")).strip()
        if not cdn_url.lower().startswith("https://"):
            raise ValueError(
                f"records[{i}] ({rid}): cdn_url must be an https URL "
                f"(got {cdn_url!r}) — no file:// / placeholder is allowed"
            )
        status = rec.get("cdn_http_status")
        if status != 200:
            raise ValueError(
                f"records[{i}] ({rid}): cdn_http_status must be 200 "
                f"(got {status!r}) — the CDN URL must verify as a live 200"
            )
        entry = {
            "id": rid,
            "prompt": rec.get("prompt", ""),
            "file": rec.get("file", ""),
            "cdn_url": cdn_url,
            "cdn_http_status": 200,
            "used_on_page_id": rec.get("used_on_page_id", ""),
        }
        if "file_id" in rec:
            entry["file_id"] = rec["file_id"]
        out.append(entry)

    if out_path:
        Path(out_path).parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(out, f, indent=2)
    return out


__all__ = [
    "GHL_SERVICES_ORIGIN",
    "GHL_MEDIA_UPLOAD_PATH",
    "GHL_MEDIA_FOLDER_PATH",
    "GHL_MEDIA_VERSION",
    "ENGLISH_LATIN_PIN",
    "TEXT_ABSENT_PIN",
    "PROMPT_CHAR_FLOOR",
    "PNG_MAGIC",
    "kie_generate_path",
    "resolve_location_pit",
    "resolve_location_id",
    "_PIT_ENV_NAMES",
    "_AGENCY_PIT_ENV_NAMES",
    "_LOCATION_ENV_NAMES",
    "_GHL_ENV_STORES",
    "build_prompts_json",
    "verify_png",
    "generate_images",
    "upload_media",
    "create_media_folder",
    "media_folder_name_prefix",
    "funnel_media_folder_plan",
    "ensure_funnel_media_folders",
    "image_tag",
    "build_image_manifest",
]
