// D03 versioned question/rubric policy packs (JEV spec 1.1, ss 2.2/4.1/4.4/8.6).
// Generated by hand to mirror policies/__init__.py + the four *_pack.json files.
// Rubrics are descriptive N-level (spec 8.6), never "rate 1-10":
// normalized = level / (levels - 1). No new external service required.

export type PackKind = "question" | "task" | "mixed" | "control";

export type MessageIntent =
  | "answer_only"
  | "task_request"
  | "mixed_answer_and_task"
  | "existing_task_control"
  | "clarification_response"
  | "social_conversation"
  | "unresolved";

export type ExecutionPreference =
  | "normal_delegation"
  | "current_assistant"
  | "named_worker"
  | "named_department"
  | "unspecified";

export interface ChoiceQuestion {
  question_id: string;
  prompt: string;
  weight: number;
  choices: string[];
  rubric?: never;
}

export interface RubricQuestion {
  question_id: string;
  prompt: string;
  weight: number;
  rubric: string;
  choices?: never;
}

export type PolicyQuestion = ChoiceQuestion | RubricQuestion;

export interface DescriptiveRubric {
  levels: string[]; // >= 2 distinct descriptive levels; index = score level
}

export interface IntakeFixture {
  message: string;
  expected_intent: MessageIntent;
  note?: string;
}

export interface PolicyPack {
  schemaVersion: string; // major 1 accepted
  pack_id: string;
  pack_version: string; // major 1 accepted
  policy_version: string; // matches envelope policyVersion, e.g. "decision-policy-v1"
  kind: PackKind;
  departments: string[];
  roles: string[];
  questions: PolicyQuestion[];
  rubrics: Record<string, DescriptiveRubric>;
  fixtures: IntakeFixture[];
}

/** N-level score to [0,1]: level / (levels - 1). Throws on invalid input. */
export function normalizeScore(level: number, levels: number): number {
  if (!Number.isInteger(level) || !Number.isInteger(levels)) {
    throw new Error(`level/levels must be ints, got ${level}/${levels}`);
  }
  if (levels < 2) throw new Error(`levels must be >= 2, got ${levels}`);
  if (level < 0 || level >= levels) {
    throw new Error(`level ${level} out of range for ${levels} levels`);
  }
  return level / (levels - 1);
}
