#!/usr/bin/env python3
"""embed-kie-prompt-enforcer.py - generate (or check) the last-known limit table inside the shared enforcer and the
hash-locked embedded copies of it that standalone gates fall back to.

Why: shared-utils/kie_prompt_enforcer.py is the ONE Python enforcer of KIE prompt rule 12, but a box may ship a skill
(for example 45 design library, 06 install pages) without shared-utils beside it, and may not have Skill 74 either.
Those gates must still enforce the identical 80 percent floor and 100 percent ceiling and must never fail open. So:

  * the enforcer carries LAST_KNOWN_MAX, the registry snapshot's prompt maxLength per model id (generated here from
    74-kie-live-adapter/references/kie-model-registry.json through the adapter's own limit code). It is consulted ONLY
    through last_known(model), as the fallback_max a gate passes, so a live Skill 74 answer always wins;
  * each destination listed in shared-utils/kie_prompt_gates.json "enforcer_copies" holds a byte-identical copy,
    imported only when shared-utils is absent. tests/unit/kie-prompt-enforcer-embedded-lock.test.py fails if a copy,
    or the table, drifts from the source.

  python3 scripts/embed-kie-prompt-enforcer.py            # regenerate the table and the copies
  python3 scripts/embed-kie-prompt-enforcer.py --check    # exit 1 if anything is stale
"""
import importlib.util
import json
import os
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ENFORCER = REPO / "shared-utils" / "kie_prompt_enforcer.py"
ADAPTER = REPO / "74-kie-live-adapter" / "scripts" / "kie_live_adapter.py"
REGISTRY = REPO / "74-kie-live-adapter" / "references" / "kie-model-registry.json"
GATES = REPO / "shared-utils" / "kie_prompt_gates.json"
BEGIN = "# >>> BEGIN LAST-KNOWN LIMITS (generated by scripts/embed-kie-prompt-enforcer.py; do not edit by hand)"
END = "# <<< END LAST-KNOWN LIMITS"


def table():
    os.environ["HOME"] = tempfile.mkdtemp()
    os.environ.pop("KIE_API_KEY", None)
    spec = importlib.util.spec_from_file_location("kie_live_adapter_gen", ADAPTER)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    adapter = mod.Adapter(env={"HOME": os.environ["HOME"]})
    out = {}
    for m in json.loads(REGISTRY.read_text(encoding="utf-8"))["models"]:
        d = adapter.cmd_prompt_budget(m["id"])["data"]
        if d.get("max") and not d.get("verbatim"):
            out[m["id"]] = int(d["max"])
    return dict(sorted(out.items()))


def block(tab):
    lines = [BEGIN,
             "# Registry snapshot of the prompt maxLength per model id (descriptive prompt fields only). A gate passes",
             "# last_known(model) as fallback_max, so the live Skill 74 answer always wins and this table only keeps the",
             "# 80 percent floor and 100 percent ceiling enforced when the adapter is not installed.",
             "LAST_KNOWN_MAX = {"]
    lines += ['    %s: %d,' % (json.dumps(k), v) for k, v in tab.items()]
    lines += ["}", "",
              "def last_known(model):", '    """Last-known prompt maxLength for a model id, or None when the id is not in the table."""',
              "    return LAST_KNOWN_MAX.get(model)", END, ""]
    return "\n".join(lines)


def render(src, tab):
    if BEGIN in src:
        a = src.index(BEGIN)
        b = src.index(END) + len(END)
        b = b + 1 if src[b:b + 1] == "\n" else b
        return src[:a] + block(tab) + src[b:]
    return src.rstrip("\n") + "\n\n\n" + block(tab)


def main(argv):
    check = "--check" in argv
    tab = table()
    src = ENFORCER.read_text(encoding="utf-8")
    new = render(src, tab)
    copies = json.loads(GATES.read_text(encoding="utf-8"))["enforcer_copies"]
    stale = []
    if new != src:
        stale.append(str(ENFORCER.relative_to(REPO)))
        if not check:
            ENFORCER.write_text(new, encoding="utf-8")
    for rel in copies:
        p = REPO / rel
        if not p.is_file() or p.read_text(encoding="utf-8") != new:
            stale.append(rel)
            if not check:
                p.write_text(new, encoding="utf-8")
    if check:
        if stale:
            print("STALE (run python3 scripts/embed-kie-prompt-enforcer.py): " + ", ".join(stale))
            return 1
        print("OK: last-known limit table matches the registry and %d embedded copies are byte-identical" % len(copies))
        return 0
    print("wrote %d model limits; updated: %s" % (len(tab), ", ".join(stale) or "nothing"))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
