#!/usr/bin/env bash
# ============================================================
#  skill-content-hash.sh — Shared Content-Hash Helper (Fix A1)
#
#  PURPOSE: Produce a deterministic per-skill content manifest
#  from a skills root directory. Used by update-skills.sh to
#  gate the version-stamp write on actual content parity, not
#  just a string match.
#
#  USAGE:
#    bash skill-content-hash.sh <skills-root-dir>
#
#  OUTPUT (to stdout):
#    One line per non-archived skill:
#      <skill-name>|<sha256-of-sorted-file-list-and-contents>
#    Final line:
#      __TREE_SHA__|<rollup-hash-over-all-per-skill-digests>
#
#  EXIT CODES:
#    0  — success
#    1  — skills-root-dir argument missing or not a directory
#    9  — neither shasum nor sha256sum is available
# ============================================================
set -euo pipefail

SKILLS_ROOT="${1:-}"
if [[ -z "$SKILLS_ROOT" || ! -d "$SKILLS_ROOT" ]]; then
  echo "ERROR: skill-content-hash.sh requires a skills root directory as \$1" >&2
  exit 1
fi

# ----------------------------------------------------------
# Detect SHA-256 tool once; fail loud if neither is present.
# ----------------------------------------------------------
_SHA_CMD=""
if command -v shasum >/dev/null 2>&1; then
  _SHA_CMD="shasum -a 256"
elif command -v sha256sum >/dev/null 2>&1; then
  _SHA_CMD="sha256sum"
else
  echo "ERROR: neither 'shasum' nor 'sha256sum' found — cannot compute content hashes" >&2
  exit 9
fi

# Helper: hash bytes from stdin
_hash_stdin() {
  $_SHA_CMD | awk '{print $1}'
}

# ----------------------------------------------------------
# Volatile / local-only files to exclude from content hash.
#
# A3 HASH-RACE FIX (v12.39.0): install-time post-processors (hash-content-manifest.py,
# generate_how_to_use_docs.py) rewrite a small set of generated artifact files AFTER
# the SRC hash is computed but BEFORE the DEST hash is computed, producing a spurious
# SRC != DEST mismatch even when the installed content is fully correct.  These files
# are excluded from BOTH sides of the A3 comparison so the gate sees the same stable
# view on both sides.  The gate still detects a real partial download or content
# truncation because all non-generated role/SOP/persona .md files remain in scope.
#
# Files excluded here MUST be legitimately regenerated at install time by a
# deterministic pipeline whose output is already CI-verified by --check gates.
# ----------------------------------------------------------
_should_exclude() {
  local f="$1"
  local base
  base="$(basename "$f")"
  case "$base" in
    # Runtime/local markers written by the installer, not part of shipped content.
    .wired-*|skill-version.txt|.onboarding-version|.onboarding-content-manifest.json)
      return 0 ;;
    # Backup files created during rollback / pre-update copy.
    *.bak|*.bak-pre-*)
      return 0 ;;
    # Generated manifest: hash-content-manifest.py rewrites _index.json with a fresh
    # content_hashed_at / generated_at timestamp on every run, so SRC (pre-install)
    # and DEST (post-install) always differ even when all role content is identical.
    # CI's hash-content-manifest.py --check gate verifies the per-artifact content_sha
    # values are current before any release is tagged, so excluding this file from A3
    # does not weaken correctness — it removes a false-positive race condition.
    _index.json)
      return 0 ;;
    # Generated QC summary: regenerated by QC scripts as part of the release pipeline.
    # Its content is volatile (timestamps, run dates) and is not the integrity signal
    # that A3 is meant to protect.
    _qc-summary.md)
      return 0 ;;
    # Department "how-to-use" guides: generated by generate_how_to_use_docs.py and
    # committed in CI.  They can be re-rendered by the install pipeline and their
    # content may legitimately diverge on a freshly installed box before the first
    # agent run triggers the regenerator.  Real content integrity for these is verified
    # by the test-how-to-use-docs.sh gate, not A3.
    how-to-use-this-department.md)
      return 0 ;;
    # A3 LIVE-BOX RESOLVE FIX: the Anthology Engine's preflight.sh renders a resolved
    # model-map.json (OUT_DIR defaults to the skill dir) at install time on every
    # live-model box, so the file lands INSIDE the A3-hashed skill tree
    # (59-anthology-engine/model-map.json). It is ABSENT from the clean source tree
    # (only config/model-map.template.json is shipped), carries per-box resolved
    # tier→credential-LABEL bindings (never a key value), and therefore made the DEST
    # digest of 59-anthology-engine diverge from SRC on every live box — withholding
    # the version stamp fleet-wide. Its integrity is enforced separately by
    # preflight.sh --check (AF-AE-UNRESOLVED-MODELMAP / AF-AE-ANTHROPIC), so excluding
    # it does not weaken A3. Basename match ONLY hits the resolved artifact; the
    # shipped model-map.template.json (different basename) stays fully in scope. Same
    # class as the */OpenMontage/*, */node_modules/*, and */working/* exclusions.
    model-map.json)
      return 0 ;;
  esac
  case "$f" in
    */.git/*) return 0 ;;
    # Install-time Python bytecode: Python writes __pycache__/*.pyc / *.pyo into
    # the DEST skill dir when skill scripts execute at install time.  These files
    # (a) are absent from the source tree, (b) embed a per-run source hash/mtime
    # that changes every install, and (c) vary by Python version.  They carry no
    # shipped content so excluding them restores A3 determinism without weakening
    # the integrity gate (all .py source files remain in scope).
    */__pycache__/*) return 0 ;;
    # A3 CLONE-RACE FIX (v14.0.1): Skill 47 (Movie Producer) clones the upstream
    # OpenMontage engine (~56MB, AGPLv3) onto the client box at install time. The
    # v14.0.1 installer clones OUTSIDE the hashed skill dir, but legacy installs (and
    # any future skill that clones a third-party repo into its own dir) would drop an
    # OpenMontage/ tree, a node_modules/ tree, or a nested .git inside the skill dir.
    # Those are runtime-fetched dependencies, NOT shipped skill content — they are
    # absent from the clean source tree, so hashing them makes the DEST hash never
    # match the SRC manifest and BLOCKS the version stamp fleet-wide. Prune them on
    # BOTH sides so even a legacy in-dir clone can never break the content hash. All
    # genuine shipped .md / .py / .sh skill files remain in scope.
    */OpenMontage/*) return 0 ;;
    */node_modules/*) return 0 ;;
    # A3 SELF-TEST RACE FIX (v14.3.15): Skill 48's installer self-tests write
    # scripts/working/af-coverage.json (and potentially other ephemeral artifacts)
    # into the hashed skill dir at install time.  These files are absent from the
    # clean source tree, so their presence made DEST!=SRC digest, causing A3 to
    # fail and the version stamp to never write.  Exclude the
    # entire */working/* subtree on both sides — it mirrors the same rationale as
    # */node_modules/* above.  Genuine shipped skill content (.md/.py/.sh) is
    # never placed in a working/ dir, so this exclusion does not weaken the gate.
    */working/*) return 0 ;;
    # A3 CROSS-SKILL EXTENSION FIX (v16.2.11): Skill 39 (Real-Estate Playbook)
    # installs an ADDITIVE extension file INTO Skill 38's installed protocols/ dir at
    # install time — 39-real-estate-playbook/scripts/05-install-sales-brain-extension.sh
    # copies references/sales-brain-real-estate-extension.md →
    # 38-conversational-ai-system/protocols/sales-best-practices-real-estate-extension.md
    # (additive; it NEVER overwrites Skill 38's own sales-best-practices-protocol.md and
    # verifies that file is byte-unchanged). That injected file is ABSENT from the clean
    # source tree, so the DEST digest of Skill 38 always differed from the SRC digest,
    # causing A3 to FAIL on 38-conversational-ai-system and the version stamp to never
    # write — this deterministically BLOCKED the fleet update on every box where Skill 39
    # is wired. The extension's canonical shipped content is STILL fully hashed under
    # Skill 39 (references/sales-brain-real-estate-extension.md), and every one of Skill
    # 38's OWN protocol files (including sales-best-practices-protocol.md) remains in
    # scope, so excluding ONLY this exact injected path — on BOTH the SRC and DEST sides
    # — restores A3 determinism without weakening tamper-detection. Same rationale and
    # scope as the */OpenMontage/*, */node_modules/*, and */working/* exclusions above.
    */38-conversational-ai-system/protocols/sales-best-practices-real-estate-extension.md) return 0 ;;
    # A3 CROSS-SKILL MARKER FIX (v16.2.11, blast-radius item 3): Skill 32's
    # add-department.sh mark_persona_stale() writes a transient marker file
    # `.persona-index-stale` INTO Skill 23's installed dir using CANONICAL skills-dir
    # candidates (~/.openclaw/skills/23-… and /data/.openclaw/skills/23-…), so it DOES
    # land in the A3-hashed tree. It is a single ephemeral dotfile (a "rebuild the
    # cached dept-tag→persona map" signal for persona-selector-v2.py), ABSENT from the
    # clean source tree and never shipped. If present at hash time it would diverge
    # Skill 23's DEST digest from SRC and block the update. Exclude ONLY this exact
    # dotfile at ONLY this path, on BOTH sides — every one of Skill 23's real role/SOP/
    # persona/template files (including all healer-*.md role files) stays in scope, so
    # tamper-detection is unchanged. Same class as the */38-…/…-extension.md exclusion.
    */23-ai-workforce-blueprint/.persona-index-stale) return 0 ;;
    # A3 RUNTIME-LOG FIX (WAVE-7): Skill 23 ships a PRISTINE
    # persona-selection-log.md (a ~785 B header ending "Append new entries below
    # this line. Do not delete historical entries."). At RUNTIME the persona
    # selector (persona-selector-v2.py / create_role_workspaces.py /
    # build-workforce.py) APPENDS one row per task dispatch to this exact file in
    # the INSTALLED skill dir, so on any box that has ever selected a persona the
    # DEST content diverges from the pristine SRC header — diverging Skill 23's
    # DEST digest from SRC and withholding the version stamp fleet-wide (observed
    # on the operator canary: DEST 4367 B vs SRC 785 B). The appended log is
    # volatile runtime state, NOT the shipped integrity signal (same class as the
    # _qc-summary.md / how-to-use / _index.json exclusions above). Exclude ONLY
    # this exact path on BOTH sides. Basename is deliberately NOT used: the static
    # golden-fixture copies under 49-signature-funnel/examples/ and
    # 56-sales-page-assets/examples/ carry the SAME basename but are byte-stable
    # shipped content and MUST stay in scope (the full-funnel-pipeline evidence
    # copies are already covered by */working/*). Every real role/SOP/persona/
    # template .md under Skill 23 remains hashed, so tamper-detection is unchanged.
    */23-ai-workforce-blueprint/persona-selection-log.md) return 0 ;;
  esac
  case "$base" in
    # Python compiled/optimised bytecode files — same rationale as __pycache__
    # above; may appear outside the __pycache__ dir on older toolchains.
    *.pyc|*.pyo) return 0 ;;
    # macOS Finder metadata — OS-generated, never shipped content.
    .DS_Store) return 0 ;;
  esac
  return 1
}

# ----------------------------------------------------------
# Iterate each non-archived numbered skill folder.
# ----------------------------------------------------------
ALL_SKILL_DIGESTS=""

while IFS= read -r -d '' SKILL_DIR; do
  skill_name="$(basename "$SKILL_DIR")"
  case "$skill_name" in *ARCHIVED*) continue ;; esac

  # Collect all non-excluded regular files, sorted deterministically.
  FILE_HASH_INPUT=""
  while IFS= read -r -d '' fpath; do
    _should_exclude "$fpath" && continue
    rel_path="${fpath#"$SKILL_DIR/"}"
    file_content_hash=$(LC_ALL=C $_SHA_CMD "$fpath" 2>/dev/null | awk '{print $1}')
    FILE_HASH_INPUT="${FILE_HASH_INPUT}${rel_path}:${file_content_hash}"$'\n'
  done < <(find "$SKILL_DIR" -type f -print0 2>/dev/null | LC_ALL=C sort -z)

  if [[ -z "$FILE_HASH_INPUT" ]]; then
    skill_digest="empty"
  else
    skill_digest=$(printf '%s' "$FILE_HASH_INPUT" | $_SHA_CMD | awk '{print $1}')
  fi

  echo "${skill_name}|${skill_digest}"
  ALL_SKILL_DIGESTS="${ALL_SKILL_DIGESTS}${skill_name}:${skill_digest}"$'\n'

done < <(find "$SKILLS_ROOT" -maxdepth 1 -mindepth 1 -type d -name '[0-9]*' -print0 2>/dev/null \
         | LC_ALL=C sort -z)

# Rollup hash
if [[ -z "$ALL_SKILL_DIGESTS" ]]; then
  TREE_SHA="empty"
else
  TREE_SHA=$(printf '%s' "$ALL_SKILL_DIGESTS" | $_SHA_CMD | awk '{print $1}')
fi

echo "__TREE_SHA__|${TREE_SHA}"
