#!/usr/bin/env bash
# ============================================================
# test-skill-manifest-reaper.sh
#
# Fixture test for the retirement of .skill-manifest.json.
#
# BACKGROUND
# .skill-manifest.json was a version-string inventory written exactly once
# by install.sh Step 11 and regenerated by nothing. It froze at the version
# of the last full install and reported that stale version forever, while
# the updater kept moving the skills underneath it. It had zero code
# readers. It has been deleted from the repo and is now reaped from every
# box by update-skills.sh.
#
# WHAT THIS TEST PROVES
#   1. After an update run, the box's manifest state is CORRECT: the lying
#      version-string file is gone and the content-hashed
#      .onboarding-content-manifest.json survives byte-identical.
#   2. The reaper never touches the two load-bearing neighbours
#      (.onboarding-version, .onboarding-content-manifest.json) or any
#      skill payload.
#   3. It is idempotent and silent on an already-clean box.
#   4. It cannot abort the updater under `set -euo pipefail`.
#   5. The repo no longer ships either writer.
#
# Runs entirely against temp fixtures. Touches no real box. HOME is
# redirected for every fixture run.
#
# Usage:  bash scripts/test-skill-manifest-reaper.sh
# Exit:   0 all pass, 1 any failure
# ============================================================
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")/.." && pwd)"
UPDATER="$REPO_ROOT/update-skills.sh"
INSTALLER="$REPO_ROOT/install.sh"

PASS=0
FAIL=0

ok()   { PASS=$((PASS + 1)); echo "  PASS  $1"; }
bad()  { FAIL=$((FAIL + 1)); echo "  FAIL  $1"; }
check(){ if [ "$2" = "$3" ]; then ok "$1"; else bad "$1 (expected '$3', got '$2')"; fi; }

TMPROOT="$(mktemp -d "${TMPDIR:-/tmp}/skill-manifest-reaper.XXXXXX")"
trap 'rm -rf "$TMPROOT"' EXIT

echo "============================================"
echo "  .skill-manifest.json reaper — fixture test"
echo "  repo: $REPO_ROOT"
echo "============================================"

# ------------------------------------------------------------
# Extract the reaper from update-skills.sh by marker.
# Extracting (rather than re-implementing) means this test fails if the
# shipped function ever drifts from what is asserted here.
# ------------------------------------------------------------
REAPER_SRC="$TMPROOT/reaper.inc"
awk '/^# --- BEGIN REAP-DEAD-SKILL-MANIFEST ---$/{f=1;next}
     /^# --- END REAP-DEAD-SKILL-MANIFEST ---$/{f=0}
     f' "$UPDATER" > "$REAPER_SRC"

if [ ! -s "$REAPER_SRC" ]; then
  echo "  FATAL: could not extract REAP-DEAD-SKILL-MANIFEST block from $UPDATER"
  exit 1
fi
ok "reaper block extracted from update-skills.sh ($(wc -l < "$REAPER_SRC" | tr -d ' ') lines)"

bash -n "$REAPER_SRC" && ok "extracted reaper passes bash -n" || bad "extracted reaper fails bash -n"

# ------------------------------------------------------------
# Fixture builder: a box mid-drift, exactly like the operator Mac was.
# Stale manifest says v20.0.10; the real stamp says v20.0.68.
# ------------------------------------------------------------
STAMP_CONTENT="v20.0.68"
CONTENT_MANIFEST_JSON='{
  "onboardingVersion": "v20.0.68",
  "tree_sha": "d1e5c0ffee00000000000000000000000000beef",
  "recorded_skills": {
    "01-alpha-skill": "aaaa1111bbbb2222cccc3333dddd4444eeee5555ffff6666aaaa7777bbbb8888",
    "02-beta-skill":  "9999aaaa8888bbbb7777cccc6666dddd5555eeee4444ffff3333aaaa2222bbbb"
  }
}'

build_fixture() {   # $1 = fixture dir, $2 = "dirty" | "clean"
  local F="$1" MODE="$2"
  mkdir -p "$F/.openclaw/skills/01-alpha-skill" \
           "$F/.openclaw/skills/02-beta-skill" \
           "$F/.openclaw/scripts" \
           "$F/Downloads/openclaw-master-files" \
           "$F/.openclaw/onboarding"

  echo "1.1.3"  > "$F/.openclaw/skills/01-alpha-skill/skill-version.txt"
  echo "alpha"  > "$F/.openclaw/skills/01-alpha-skill/SKILL.md"
  echo "0.2.11" > "$F/.openclaw/skills/02-beta-skill/skill-version.txt"
  echo "beta"   > "$F/.openclaw/skills/02-beta-skill/SKILL.md"

  # The two load-bearing neighbours. These MUST survive untouched.
  printf '%s\n' "$STAMP_CONTENT" > "$F/.openclaw/skills/.onboarding-version"
  printf '%s\n' "$CONTENT_MANIFEST_JSON" > "$F/.openclaw/skills/.onboarding-content-manifest.json"

  if [ "$MODE" = "dirty" ]; then
    # The lying file, in every location it has ever been written.
    local STALE='{"generated":"2026-06-01T00:00:00Z","onboardingVersion":"v20.0.10","skills":{"01-alpha-skill":"1.1.0","02-beta-skill":"0.2.4"}}'
    printf '%s\n' "$STALE" > "$F/.openclaw/skills/.skill-manifest.json"
    printf '%s\n' "$STALE" > "$F/Downloads/openclaw-master-files/.skill-manifest.json"
    printf '%s\n' "$STALE" > "$F/.openclaw/onboarding/.skill-manifest.json"
    # The orphaned regenerator that ships to every box and is called by nothing.
    printf '#!/bin/bash\n# dead orphan\n' > "$F/.openclaw/scripts/generate-manifest.sh"
    chmod +x "$F/.openclaw/scripts/generate-manifest.sh"
  fi
}

# Run the reaper against a fixture in a subshell with HOME redirected,
# under the updater's real shell options. Captures stdout, returns rc.
run_reaper() {   # $1 = fixture dir, $2 = stdout capture file
  (
    set -euo pipefail
    HOME="$1"
    SKILLS_DIR="$1/.openclaw/skills"
    export HOME SKILLS_DIR
    # shellcheck source=/dev/null
    source "$REAPER_SRC"
    reap_dead_skill_manifest
  ) > "$2" 2>&1
  return $?
}

# ============================================================
echo ""
echo "[1] Dirty box — simulates the state AFTER an update run reaches the reaper"
# ============================================================
DIRTY="$TMPROOT/dirty"
build_fixture "$DIRTY" dirty

STAMP_BEFORE="$(cksum < "$DIRTY/.openclaw/skills/.onboarding-version")"
CMANI_BEFORE="$(cksum < "$DIRTY/.openclaw/skills/.onboarding-content-manifest.json")"
SKILLS_BEFORE="$(cd "$DIRTY/.openclaw/skills" && find . -type f ! -name '.skill-manifest.json' | LC_ALL=C sort | cksum)"

OUT1="$TMPROOT/out1.txt"
run_reaper "$DIRTY" "$OUT1"; RC1=$?
check "reaper exits 0 under set -euo pipefail" "$RC1" "0"

# --- the lying file is gone everywhere ---
for LOC in ".openclaw/skills" "Downloads/openclaw-master-files" ".openclaw/onboarding"; do
  if [ -e "$DIRTY/$LOC/.skill-manifest.json" ]; then
    bad ".skill-manifest.json removed from $LOC"
  else
    ok  ".skill-manifest.json removed from $LOC"
  fi
done

if [ -e "$DIRTY/.openclaw/scripts/generate-manifest.sh" ]; then
  bad "orphaned generate-manifest.sh removed from ~/.openclaw/scripts"
else
  ok  "orphaned generate-manifest.sh removed from ~/.openclaw/scripts"
fi

# --- MANIFEST STATE IS CORRECT AFTER THE RUN ---
# "Correct" = the version-string oracle is gone and the content-hashed
# oracle is intact and still parses with its per-skill digests.
if [ -f "$DIRTY/.openclaw/skills/.onboarding-content-manifest.json" ]; then
  ok ".onboarding-content-manifest.json SURVIVES (it is the real drift oracle)"
else
  bad ".onboarding-content-manifest.json SURVIVES (it is the real drift oracle)"
fi
check ".onboarding-content-manifest.json byte-identical (not rewritten)" \
      "$(cksum < "$DIRTY/.openclaw/skills/.onboarding-content-manifest.json")" "$CMANI_BEFORE"

RECORDED=$(python3 -c "
import json,sys
d=json.load(open(sys.argv[1]))
print(len(d.get('recorded_skills',{})))
" "$DIRTY/.openclaw/skills/.onboarding-content-manifest.json" 2>/dev/null || echo "ERR")
check "surviving content manifest still parses, 2 per-skill digests" "$RECORDED" "2"

# --- the stamp and the payload are untouched ---
check ".onboarding-version byte-identical" \
      "$(cksum < "$DIRTY/.openclaw/skills/.onboarding-version")" "$STAMP_BEFORE"
check ".onboarding-version content preserved" \
      "$(tr -d '[:space:]' < "$DIRTY/.openclaw/skills/.onboarding-version")" "$STAMP_CONTENT"
check "skill payload files untouched" \
      "$(cd "$DIRTY/.openclaw/skills" && find . -type f | LC_ALL=C sort | cksum)" "$SKILLS_BEFORE"

if grep -q "Reaped 4 dead" "$OUT1"; then
  ok "reported exactly 4 reaped artifacts"
else
  bad "reported exactly 4 reaped artifacts (got: $(tr '\n' '|' < "$OUT1"))"
fi

# ============================================================
echo ""
echo "[2] Idempotence — a second run is a silent no-op"
# ============================================================
OUT2="$TMPROOT/out2.txt"
run_reaper "$DIRTY" "$OUT2"; RC2=$?
check "second run exits 0" "$RC2" "0"
check "second run prints nothing" "$(wc -c < "$OUT2" | tr -d ' ')" "0"

# ============================================================
echo ""
echo "[3] Clean box — never provisioned with the dead file"
# ============================================================
CLEAN="$TMPROOT/clean"
build_fixture "$CLEAN" clean
OUT3="$TMPROOT/out3.txt"
run_reaper "$CLEAN" "$OUT3"; RC3=$?
check "clean box exits 0" "$RC3" "0"
check "clean box prints nothing" "$(wc -c < "$OUT3" | tr -d ' ')" "0"
if [ -f "$CLEAN/.openclaw/skills/.onboarding-version" ] \
   && [ -f "$CLEAN/.openclaw/skills/.onboarding-content-manifest.json" ]; then
  ok "clean box neighbours intact"
else
  bad "clean box neighbours intact"
fi

# ============================================================
echo ""
echo "[4] VPS path coverage — asserted by inspection (/data cannot be fixtured)"
# ============================================================
for VPSPATH in "/data/.openclaw/skills/.skill-manifest.json" "/data/.openclaw/scripts/generate-manifest.sh"; do
  if grep -qF "$VPSPATH" "$REAPER_SRC"; then
    ok "reaper covers $VPSPATH"
  else
    bad "reaper covers $VPSPATH"
  fi
done

# Guard against the reaper ever growing a path that would eat a live file.
for FORBIDDEN in ".onboarding-version" ".onboarding-content-manifest.json"; do
  if grep -q "^\s*\"[^\"]*$FORBIDDEN\" *\\\\\?$" "$REAPER_SRC"; then
    bad "reaper must NOT list $FORBIDDEN as a deletion target"
  else
    ok  "reaper does not list $FORBIDDEN as a deletion target"
  fi
done

# ============================================================
echo ""
echo "[5] Repo no longer ships either writer"
# ============================================================
if [ -e "$REPO_ROOT/scripts/generate-manifest.sh" ]; then
  bad "scripts/generate-manifest.sh deleted from repo"
else
  ok  "scripts/generate-manifest.sh deleted from repo"
fi

# install.sh must still write the stamp, but must no longer WRITE the manifest.
if grep -q 'onboarding-version"' "$INSTALLER"; then
  ok "install.sh still writes .onboarding-version (load-bearing)"
else
  bad "install.sh still writes .onboarding-version (load-bearing)"
fi
if grep -qE "json\.dump\(manifest|MANIFEST_PATH=.*skill-manifest\.json" "$INSTALLER"; then
  bad "install.sh no longer generates .skill-manifest.json"
else
  ok  "install.sh no longer generates .skill-manifest.json"
fi
# The only remaining mentions anywhere must be comments or deletion targets.
if grep -n "skill-manifest" "$INSTALLER" "$UPDATER" | grep -vE "^[^:]+:[0-9]+: *#|skill-manifest\.json\" \\\\?$|Reaped|\.skill-manifest\.json is|\.skill-manifest\.json and" >/dev/null 2>&1; then
  echo "  NOTE  remaining skill-manifest mentions (review — expect comments + rm targets only):"
  grep -n "skill-manifest" "$INSTALLER" "$UPDATER" | sed 's/^/          /'
fi

# ============================================================
echo ""
echo "============================================"
echo "  PASS: $PASS   FAIL: $FAIL"
echo "============================================"
[ "$FAIL" -eq 0 ] || exit 1
exit 0
