#!/usr/bin/env python3
"""embed_kie_client.py - generate (or check) the blocks embedded in kie_image.py.

The OpenMontage clone and the Docker image carry only the two files under
kie-adapters/, so everything the adapters need from the rest of the repo has to
travel inside one of them. Two blocks live at the bottom of kie_image.py, each
copied VERBATIM from its source and stamped with a sha256 (kie_video.py and the
driver read the same blocks out of kie_image.py):

  CLIENT         74-kie-live-adapter/scripts/kie_live_adapter.py, from its
                 `import argparse` line to the line before its CLI banner (the
                 Skill 74 transport: Adapter, validate, upload, price, prompt-budget).
  SECRET-HELPER  shared-utils/secret_helper.py, the placeholder / shape / entropy
                 gate `looks_like_real_key` (from `_REALISH_RE` to the line before
                 `assert_real_key`), so a bare clone or the Docker image, which have
                 no shared-utils, still tell a real key from a placeholder.

  python3 47-movie-producer/scripts/embed_kie_client.py            # regenerate the blocks
  python3 47-movie-producer/scripts/embed_kie_client.py --check    # exit 1 if a block is stale

Run it again whenever either source changes; scripts/test_kie_embedded_client_hashlock.py
fails until you do.
"""
import hashlib
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
TARGET = REPO / "47-movie-producer" / "kie-adapters" / "tools" / "graphics" / "kie_image.py"

CLIENT_SRC = REPO / "74-kie-live-adapter" / "scripts" / "kie_live_adapter.py"
CLIENT_VERSION_FILE = REPO / "74-kie-live-adapter" / "skill-version.txt"
SECRET_SRC = REPO / "shared-utils" / "secret_helper.py"

# Backward-compatible names used by the lock test.
SRC = CLIENT_SRC
VERSION_FILE = CLIENT_VERSION_FILE
BEGIN = "# >>> BEGIN EMBEDDED SKILL-74 CLIENT (generated by 47-movie-producer/scripts/embed_kie_client.py; do not edit by hand)"
END = "# <<< END EMBEDDED SKILL-74 CLIENT"
PLACEHOLDER = "# EMBEDDED_CLIENT_PLACEHOLDER"

SECRET_BEGIN = "# >>> BEGIN EMBEDDED SECRET-HELPER (generated by 47-movie-producer/scripts/embed_kie_client.py; do not edit by hand)"
SECRET_END = "# <<< END EMBEDDED SECRET-HELPER"
SECRET_PLACEHOLDER = "# EMBEDDED_SECRET_HELPER_PLACEHOLDER"


def _slice(source_text: str, start_prefix: str, end_prefix: str) -> str:
    lines = source_text.split("\n")
    start = next(i for i, ln in enumerate(lines) if ln.startswith(start_prefix))
    end = next(i for i, ln in enumerate(lines) if i > start and ln.startswith(end_prefix))
    section = lines[start:end]
    while section and not section[-1].strip():
        section.pop()
    return "\n".join(section) + "\n"


def extract_section(source_text: str) -> str:
    """Skill 74 client section."""
    return _slice(source_text, "import argparse", "# --------------------------------------------------------------------- CLI")


def extract_secret_section(source_text: str) -> str:
    """shared-utils/secret_helper.py placeholder gate section."""
    return _slice(source_text, "# Value shapes that read as real keys", "def assert_real_key(")


def build_block(source_text: str, version: str) -> str:
    section = extract_section(source_text)
    digest = hashlib.sha256(section.encode("utf-8")).hexdigest()
    header = (
        f"{BEGIN}\n"
        f"# source: 74-kie-live-adapter/scripts/kie_live_adapter.py (skill version {version}); the section between the markers\n"
        f"# below is that file from its `import argparse` line to the line before its CLI banner, byte for byte.\n"
        f'_EMBEDDED_CLIENT_SHA256 = "{digest}"\n'
    )
    return header + section + END + "\n"


def build_secret_block(source_text: str) -> str:
    section = extract_secret_section(source_text)
    digest = hashlib.sha256(section.encode("utf-8")).hexdigest()
    header = (
        f"{SECRET_BEGIN}\n"
        "# source: shared-utils/secret_helper.py; the section after the imports is that file from `_REALISH_RE` through\n"
        "# `looks_like_real_key`, byte for byte (placeholder, provider-shape and entropy gate).\n"
        f'_EMBEDDED_SECRET_HELPER_SHA256 = "{digest}"\n'
        "import math\nimport re\nfrom typing import Dict, Optional\n"
    )
    return header + section + SECRET_END + "\n"


def current_block(target_text: str, begin: str = BEGIN, end: str = END):
    """-> the text from BEGIN through END (inclusive), or None."""
    if begin not in target_text or end not in target_text:
        return None
    start = target_text.index(begin)
    return target_text[start:target_text.index(end, start) + len(end) + 1]


def _regenerate(target_text: str, block: str, begin: str, end: str, placeholder: str) -> str:
    old = current_block(target_text, begin, end)
    if old is not None:
        return target_text.replace(old, block)
    if placeholder in target_text:
        return target_text.replace(placeholder + "\n", block)
    raise SystemExit(f"kie_image.py has neither the block nor its placeholder ({placeholder})")


def regenerate(target_text: str, block: str) -> str:
    return _regenerate(target_text, block, BEGIN, END, PLACEHOLDER)


def regenerate_all(target_text: str) -> str:
    text = regenerate(target_text, build_block(CLIENT_SRC.read_text(encoding="utf-8"), CLIENT_VERSION_FILE.read_text().strip()))
    return _regenerate(text, build_secret_block(SECRET_SRC.read_text(encoding="utf-8")), SECRET_BEGIN, SECRET_END, SECRET_PLACEHOLDER)


def main(argv=None) -> int:
    check = "--check" in (argv if argv is not None else sys.argv[1:])
    text = TARGET.read_text(encoding="utf-8")
    new = regenerate_all(text)
    if check:
        if new != text:
            print("STALE: an embedded block in kie_image.py differs from its source (Skill 74 client or shared-utils secret_helper); run embed_kie_client.py")
            return 1
        print("OK: embedded Skill 74 client and secret helper match their sources")
        return 0
    if new != text:
        TARGET.write_text(new, encoding="utf-8")
        print("regenerated", TARGET)
    else:
        print("already current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
