#!/usr/bin/env python3
"""embed_kie_client.py - generate (or check) the embedded Skill 74 client inside kie_image.py.

The OpenMontage clone and the Docker image carry only the two files under
kie-adapters/, so Skill 74's client has to travel inside one of them. This script
copies Skill 74's source VERBATIM (from the `import argparse` line up to the line
before the CLI banner: imports, constants, schema helpers, price and prompt-budget
helpers, the Adapter class) into the marked block at the bottom of kie_image.py and
stamps its sha256. kie_video.py reads the same block out of its sibling kie_image.py.

  python3 47-movie-producer/scripts/embed_kie_client.py            # regenerate the block
  python3 47-movie-producer/scripts/embed_kie_client.py --check    # exit 1 if the block is stale

Run it again whenever 74-kie-live-adapter/scripts/kie_live_adapter.py changes;
scripts/test_kie_embedded_client_hashlock.py fails until you do.
"""
import hashlib
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SRC = REPO / "74-kie-live-adapter" / "scripts" / "kie_live_adapter.py"
VERSION_FILE = REPO / "74-kie-live-adapter" / "skill-version.txt"
TARGET = REPO / "47-movie-producer" / "kie-adapters" / "tools" / "graphics" / "kie_image.py"

SECTION_START = "import argparse"
SECTION_END = "# --------------------------------------------------------------------- CLI"
BEGIN = "# >>> BEGIN EMBEDDED SKILL-74 CLIENT (generated by 47-movie-producer/scripts/embed_kie_client.py; do not edit by hand)"
END = "# <<< END EMBEDDED SKILL-74 CLIENT"
PLACEHOLDER = "# EMBEDDED_CLIENT_PLACEHOLDER"


def extract_section(source_text: str) -> str:
    lines = source_text.split("\n")
    start = lines.index(SECTION_START)
    end = lines.index(SECTION_END)
    section = lines[start:end]
    while section and not section[-1].strip():
        section.pop()
    return "\n".join(section) + "\n"


def build_block(source_text: str, version: str) -> str:
    section = extract_section(source_text)
    digest = hashlib.sha256(section.encode("utf-8")).hexdigest()
    header = (
        f"{BEGIN}\n"
        f"# source: 74-kie-live-adapter/scripts/kie_live_adapter.py (skill version {version}); the section between the markers\n"
        f"# below is that file from its `import argparse` line to the line before its CLI banner, byte for byte.\n"
        f'_EMBEDDED_CLIENT_SHA256 = "{digest}"\n'
    )
    return header + section + END + "\n"


def current_block(target_text: str):
    """-> the text from BEGIN through END (inclusive), or None."""
    if BEGIN not in target_text or END not in target_text:
        return None
    start = target_text.index(BEGIN)
    return target_text[start:target_text.index(END, start) + len(END) + 1]


def regenerate(target_text: str, block: str) -> str:
    old = current_block(target_text)
    if old is not None:
        return target_text.replace(old, block)
    if PLACEHOLDER in target_text:
        return target_text.replace(PLACEHOLDER + "\n", block)
    raise SystemExit("kie_image.py has neither the embedded block nor the placeholder line")


def main(argv=None) -> int:
    check = "--check" in (argv if argv is not None else sys.argv[1:])
    block = build_block(SRC.read_text(encoding="utf-8"), VERSION_FILE.read_text().strip())
    text = TARGET.read_text(encoding="utf-8")
    new = regenerate(text, block)
    if check:
        if new != text:
            print("STALE: embedded Skill 74 client differs from 74-kie-live-adapter/scripts/kie_live_adapter.py; run embed_kie_client.py")
            return 1
        print("OK: embedded Skill 74 client matches Skill 74's source")
        return 0
    if new != text:
        TARGET.write_text(new, encoding="utf-8")
        print("regenerated", TARGET)
    else:
        print("already current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
