"""style_bibles.canvas_to_life package: D21/D29 Canvas to Life bible.

2D hand-painted cartoon switches to REAL FOOTAGE (the D19 cinematic recipe
read verbatim from style-bibles/realism-cinematic.md) and back, with the
character identity locked across the switch. A golden realism finale is
optional, never required. The 2D-to-3D path is never used here. Stdlib only,
no spend.
"""
from .canvas_to_life_bible import (  # noqa: F401
    BANNED_3D_ALIASES,
    DISSOLVE_SECONDS,
    FINALE_BLOCK,
    GOLDEN_BEATS,
    HOLD_MIN_SECONDS,
    LOOK_ID,
    LOOKS,
    MODE_GOLDEN,
    MODE_PAINTED,
    MODE_REALISM,
    MODES,
    PAINTED_BEATS,
    PAINTED_STYLE,
    PAINTED_STYLE_ID,
    REALISM_BEATS,
    REALISM_STYLE_ID,
    RECIPE_REQUIRED_PHRASES,
    SCHEMA_VERSION,
    CanvasToLifeError,
    assert_identity_lock,
    assert_look,
    beat_mode,
    compile_prompt,
    enforce_switch,
    extract_recipe,
    find_recipe,
    identity_lock,
    identity_lock_block,
    looks,
    lock_valid,
    painted_block,
    painted_style,
    plan_hybrid,
    realism_available,
    realism_block,
    realism_sha256,
    recipe_candidate_paths,
    validate_painted,
    validate_plan,
)

__all__ = [
    "BANNED_3D_ALIASES",
    "DISSOLVE_SECONDS",
    "FINALE_BLOCK",
    "GOLDEN_BEATS",
    "HOLD_MIN_SECONDS",
    "LOOK_ID",
    "LOOKS",
    "MODE_GOLDEN",
    "MODE_PAINTED",
    "MODE_REALISM",
    "MODES",
    "PAINTED_BEATS",
    "PAINTED_STYLE",
    "PAINTED_STYLE_ID",
    "REALISM_BEATS",
    "REALISM_STYLE_ID",
    "RECIPE_REQUIRED_PHRASES",
    "SCHEMA_VERSION",
    "CanvasToLifeError",
    "assert_identity_lock",
    "assert_look",
    "beat_mode",
    "compile_prompt",
    "enforce_switch",
    "extract_recipe",
    "find_recipe",
    "identity_lock",
    "identity_lock_block",
    "looks",
    "lock_valid",
    "painted_block",
    "painted_style",
    "plan_hybrid",
    "realism_available",
    "realism_block",
    "realism_sha256",
    "recipe_candidate_paths",
    "validate_painted",
    "validate_plan",
]
