#!/usr/bin/env bash
# Secret-leak test for openclaw-loop-protection-restore.sh
#
# Builds a fake HOME whose secret-bearing files are stuffed with tracer strings, stubs the
# `openclaw` CLI so every config read returns tracer-laden output, then runs the restore script in
# BOTH modes and asserts no tracer ever reaches stdout, stderr, or any file the script writes.
#
# The one legitimate exception is the timestamped BACKUP of the secret file itself: a backup of a
# secrets file necessarily contains those secrets. That copy is asserted to exist with mode 600.

set -uo pipefail
export PATH="/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:${PATH}"

SCRIPT="${1:?usage: secret-leak-test.sh /path/to/openclaw-loop-protection-restore.sh}"
DIST="${2:?usage: secret-leak-test.sh <script> <distDir>}"

WORK="$(/usr/bin/mktemp -d -t ocloop-tracer.XXXXXX)" || exit 2
FHOME="${WORK}/home"
BIN="${WORK}/bin"
mkdir -p "${FHOME}/.openclaw/service-env" "${FHOME}/.openclaw/scripts" "${FHOME}/.openclaw/hooks" \
         "${FHOME}/.openclaw/extensions/ceo-routing-doctrine/dist" "${FHOME}/.claude" "${BIN}"

C_ENV_A="TRACERENVSTRIPEsk11test22deadbeef"
C_ENV_B="TRACERENVROOTPASSWDhunter2trombone"
C_ENV_C="TRACERENVSUPABASEserviceroleJWTxyz"
C_PROMPT="TRACERPROMPTsecretinsideprompttext"
C_ALLOW="TRACERALLOWplugintokenvalue"
C_AGENTS="TRACERAGENTSproviderapikeyvalue"
ALL_TRACERS="${C_ENV_A} ${C_ENV_B} ${C_ENV_C} ${C_PROMPT} ${C_ALLOW} ${C_AGENTS}"

# --- secret-bearing service-env fixture: target key WRONG so --apply must rewrite this file ----
ENVF="${FHOME}/.openclaw/service-env/ai.openclaw.gateway.env"
{
  printf '# Generated by OpenClaw. Do not edit.\n'
  printf 'STRIPE_SECRET_KEY=%s\n' "${C_ENV_A}"
  printf 'VPS_ROOT_PASSWORD=%s\n' "${C_ENV_B}"
  printf 'SUPABASE_SERVICE_ROLE_KEY=%s\n' "${C_ENV_C}"
  printf 'OPENCLAW_SERVICE_MANAGED_ENV_KEYS=STRIPE_SECRET_KEY,SUPABASE_SERVICE_ROLE_KEY\n'
  printf 'OPENCLAW_TELEGRAM_SPOOLED_HANDLER_TIMEOUT_MS=%s\n' "'60000'"
} > "${ENVF}"
chmod 600 "${ENVF}"

printf '{"hooks":{}}\n' > "${FHOME}/.claude/settings.json"
printf 'echo stub\n' > "${FHOME}/.openclaw/scripts/ensure-daily-memory-stub.sh"
chmod +x "${FHOME}/.openclaw/scripts/ensure-daily-memory-stub.sh"
printf 'export default {};\n' > "${FHOME}/.openclaw/extensions/ceo-routing-doctrine/dist/index.js"

# --- stubbed openclaw CLI: every config read hands back tracer-laden content -------------------
# Non-secret numeric/boolean keys return their CORRECT values so that any tracer appearing in
# output can only have come from a path that must never be printed.
cat > "${BIN}/openclaw" <<STUBEOF
#!/usr/bin/env bash
if [ "\$1" = "--version" ]; then echo "OpenClaw 0.0.0-tracer-stub"; exit 0; fi
if [ "\$1" = "config" ] && [ "\$2" = "get" ]; then
  case "\$3" in
    agents.defaults.compaction.memoryFlush.enabled) echo true ;;
    agents.defaults.compaction.memoryFlush.forceFlushTranscriptBytes) echo 0 ;;
    agents.defaults.compaction.memoryFlush.prompt)
      printf 'Flush now. embedded secret: %s\n' "${C_PROMPT}" ;;
    tools.loopDetection.enabled) echo true ;;
    tools.loopDetection.warningThreshold) echo 2 ;;
    tools.loopDetection.criticalThreshold) echo 3 ;;
    tools.loopDetection.globalCircuitBreakerThreshold) echo 6 ;;
    tools.loopDetection.unknownToolThreshold) echo 3 ;;
    tools.loopDetection.postCompactionGuard.windowSize) echo 2 ;;
    agents.main.tools.loopDetection) echo "Config path not found" ; exit 1 ;;
    agents.list)
      printf '[{"id":"main","apiKey":"%s","tools":{"allow":["read","exec"],"deny":[]}}]\n' "${C_AGENTS}" ;;
    plugins.load.paths) printf '["%s/.openclaw/extensions"]\n' "${FHOME}" ;;
    plugins.allow) printf '["ceo-routing-doctrine","%s"]\n' "${C_ALLOW}" ;;
    plugins.entries.ceo-routing-doctrine.enabled) echo true ;;
    plugins.entries.ceo-routing-doctrine.hooks.allowPromptInjection) echo true ;;
    *) exit 1 ;;
  esac
  exit 0
fi
if [ "\$1" = "config" ] && [ "\$2" = "set" ]; then exit 0; fi
exit 1
STUBEOF
chmod +x "${BIN}/openclaw"

# crontab shim so the real crontab is never read or written by this test
cat > "${BIN}/crontab" <<'CRONEOF'
#!/usr/bin/env bash
if [ "${1:-}" = "-l" ]; then echo "*/5 * * * * /bin/bash /somewhere/ensure-daily-memory-stub.sh"; exit 0; fi
exit 0
CRONEOF
chmod +x "${BIN}/crontab"

FAILED=0
report() { printf '%s\n' "$1"; }

run_mode() {
  local mode="$1" out err rc
  out="${WORK}/${mode}.stdout"; err="${WORK}/${mode}.stderr"
  ( export HOME="${FHOME}"; export PATH="${BIN}:${PATH}"; export OPENCLAW_DIST_DIR="${DIST}"; \
    if [ "${mode}" = "apply" ]; then "${SCRIPT}" --apply; else "${SCRIPT}"; fi ) >"${out}" 2>"${err}"
  rc=$?
  report ""
  report "--- mode=${mode} exit=${rc} ---"
  for c in ${ALL_TRACERS}; do
    if /usr/bin/grep -q "${c}" "${out}"; then report "  LEAK: tracer in STDOUT (${c})"; FAILED=1; fi
    if /usr/bin/grep -q "${c}" "${err}"; then report "  LEAK: tracer in STDERR (${c})"; FAILED=1; fi
  done
  # control: the tracers really ARE readable from the fixture the script just read.
  # No `grep -q` inside a pipeline here: under `set -o pipefail`, grep -q closes the pipe early,
  # SIGPIPEs the producer and fails the whole pipeline - an instrument artifact, not a result.
  local seen=0 probe="${WORK}/${mode}.probe"
  { "${BIN}/openclaw" config get agents.list
    "${BIN}/openclaw" config get plugins.allow
    "${BIN}/openclaw" config get agents.defaults.compaction.memoryFlush.prompt
    /bin/cat "${ENVF}"
  } > "${probe}" 2>/dev/null
  for c in ${C_ENV_A} ${C_PROMPT} ${C_ALLOW} ${C_AGENTS}; do
    if /usr/bin/grep -F -q -- "${c}" "${probe}"; then seen=$((seen+1)); fi
  done
  report "  control: ${seen}/4 tracers confirmed readable from the fixture (must be 4)"
  [ "${seen}" = "4" ] || { report "  TEST INSTRUMENT BROKEN - tracers not actually reachable"; FAILED=1; }
  report "  stdout bytes=$(/usr/bin/wc -c <"${out}" | /usr/bin/tr -d ' ')  stderr bytes=$(/usr/bin/wc -c <"${err}" | /usr/bin/tr -d ' ')"
}

report "=============================================================="
report " TRACER LEAK TEST"
report "=============================================================="
run_mode check
run_mode apply

# --- files written by the script ---------------------------------------------------------------
report ""
report "--- files the script wrote under the fake HOME ---"
# Rule 3.1: a census must enumerate symlinks too — a symlink to a file IS a file
# for counting purposes. ( -type f -o -type l ), never a bare -type f.
WROTE="$(/usr/bin/find "${FHOME}/.openclaw-patch-backups" \( -type f -o -type l \) 2>/dev/null)"
if [ -z "${WROTE}" ]; then
  report "  NO BACKUP WAS WRITTEN - --apply should have backed up the service-env file"
  FAILED=1
else
  for f in ${WROTE}; do
    MODE="$(/usr/bin/stat -f '%Lp' "${f}" 2>/dev/null)"
    report "  ${f##*/}  mode=${MODE}"
    case "${f}" in
      *ai.openclaw.gateway.env*)
        if ! /usr/bin/grep -q "${C_ENV_A}" "${f}"; then
          report "    BACKUP IS NOT A FAITHFUL COPY - tracer missing"; FAILED=1
        else
          report "    contains the original secrets (expected for a backup)"
        fi
        [ "${MODE}" = "600" ] || { report "    BACKUP PERMISSIONS TOO OPEN (want 600)"; FAILED=1; } ;;
      *)
        for c in ${ALL_TRACERS}; do
          /usr/bin/grep -q "${c}" "${f}" && { report "    LEAK: tracer in written file"; FAILED=1; }
        done ;;
    esac
  done
fi

# --- the rewritten env file must keep every secret and gain the right value --------------------
report ""
report "--- service-env after --apply ---"
for c in ${C_ENV_A} ${C_ENV_B} ${C_ENV_C}; do
  /usr/bin/grep -q "${c}" "${ENVF}" || { report "  DESTROYED A SECRET: a tracer is gone from the env file"; FAILED=1; }
done
report "  all 3 env tracers survived the atomic rewrite"
NEWVAL="$(/usr/bin/grep -o "OPENCLAW_TELEGRAM_SPOOLED_HANDLER_TIMEOUT_MS=['\"]\{0,1\}[0-9]*" "${ENVF}" | /usr/bin/grep -o '[0-9]*$')"
if [ "${NEWVAL}" = "1800000" ]; then report "  target key rewritten to 1800000"; else report "  target key NOT rewritten (got ${NEWVAL:-<none>})"; FAILED=1; fi
EMODE="$(/usr/bin/stat -f '%Lp' "${ENVF}")"
[ "${EMODE}" = "600" ] && report "  env file mode preserved at 600" || { report "  ENV FILE MODE CHANGED to ${EMODE}"; FAILED=1; }
LINES="$(/usr/bin/grep -c "" "${ENVF}")"
report "  env file line count=${LINES} (fixture had 6)"

report ""
report "=============================================================="
if [ "${FAILED}" = "0" ]; then
  report " RESULT: PASS - no tracer reached stdout, stderr, or any written file"
  report "         except the mode-600 backup of the secret file itself."
else
  report " RESULT: FAIL - see LEAK/DESTROYED lines above"
fi
report " fixture kept at: ${WORK}"
report "=============================================================="
exit "${FAILED}"
