#!/usr/bin/env python3
"""
synthesize_full_speech.py — FULL-LENGTH presenter-audio synthesis for the
Presentations department (audio-demonstration-specialist, SOP 9.2 / 9.3).

WHY THIS EXISTS
---------------
The original Corey run synthesized only a 7-section "KEY BEATS" sizzle demo
(~4 min) instead of the whole 62-slide speech (~25.6 min). There was no
committed script that walked the ENTIRE speech, and no gate that caught the
audio being far shorter than the written script. This script fixes both:

  1. Splits the ENTIRE speech into Fish-Audio-safe chunks (sentence/paragraph
     boundaries, each <= --chunk-chars UTF-8-safe characters).
  2. Synthesizes EACH chunk via Fish Audio /v1/tts (same key + voice + model).
  3. Concatenates all chunks with ffmpeg into ONE mp3 and loudness-normalizes.
  4. DURATION SANITY GATE (hard, FAIL LOUD): the rendered audio duration MUST
     be >= --min-ratio (default 0.80) of the expected length computed from the
     spoken word count at --wpm (default 140). If the audio is far short of the
     speech, the script EXITS NON-ZERO and does NOT overwrite the deliverable.

EXPRESSIVE AUDIO (GAUNTLET LOOP 2, Feature A) — why this is no longer flat
-------------------------------------------------------------------------
Fish Audio S2 / S2.1-Pro expressiveness is driven by INLINE [bracket] reader
tags embedded in the text (e.g. `[confident]` `[pause]` `[whispering]`) — there
is NO SSML / emotion request field. The department already produces those tags
in `speech_fish_tag.py` -> `PRESENTERS-SPEECH-FISH-TAGGED.md`, but the executor
fed the UNTAGGED `PRESENTERS-SPEECH.md` to the API, so the tags never reached
the model and every read came out flat. This script now:

  - Synthesizes the **FISH-TAGGED** speech (`--tagged-speech`) when provided,
    so `[bracket]` emotion / reader tags actually reach the API.
  - Sends the documented expressiveness knobs the API supports:
      temperature          0.9 (higher = more expressive; default 0.7)
      top_p                0.8 (nucleus-sampling diversity)
      repetition_penalty   1.2 (suppress repetitive audio patterns)
      prosody              {speed, volume, normalize_loudness}
    (Fish OpenAPI: https://api.fish.audio/openapi.json — verified field names.)
  - Splices **measured** silence at pause markers (see PAUSES below) so the
    1-5 s dramatic pauses are EXACT, not whatever the model decides.

PAUSES — exact 1-5 s dramatic silence
-------------------------------------
The Fish API pause tags (`[pause]`, `[long pause]`, `[long-break]`, `[break]`,
`[short pause]`) have NO documented duration (docs only say "brief"/"extended").
To get deterministic 1-5 s silences we do NOT rely on the model's guess: pause
markers are stripped from the text sent to the API and replaced with a measured
silent mp3 (ffmpeg anullsrc) spliced at the exact position in the concat.
Defaults (override with --pause-short / --pause / --pause-long):
  [short pause]                    -> 0.8 s
  [pause] / [break] / [PAUSE]      -> 1.2 s
  [BREATHE]                        -> 1.2 s (breath cue -> beat)
  [long pause] / [long-break]      -> 2.5 s
  (PAUSE N seconds)                -> N seconds (parsed)
Director cues `(OWNER: ...)` are dropped entirely (never spoken aloud).

USAGE
-----
  FISH_AUDIO_API_KEY=... FISH_AUDIO_VOICE_ID=... \
  python3 synthesize_full_speech.py \
      --speech        /path/PRESENTERS-SPEECH.md \
      --tagged-speech /path/PRESENTERS-SPEECH-FISH-TAGGED.md \
      --out           /path/PRESENTER-AUDIO.mp3 \
      [--voice-id <reference_id>] [--api-key <key>] \
      [--model s2.1-pro] [--bitrate 192] [--wpm 140] [--min-ratio 0.80] \
      [--chunk-chars 280] [--workdir <dir>] \
      [--temperature 0.9] [--top-p 0.8] [--repetition-penalty 1.2] \
      [--prosody-speed 1.25] [--prosody-volume 0] \
      [--pause-short 0.8] [--pause 1.2] [--pause-long 2.5] \
      [--webinar-intro-outro]

The word-count / duration gate is computed from the UNTAGGED `--speech` (bracket
tags are not spoken words). Synthesis chunks come from `--tagged-speech` when
given, else fall back to `--speech`.

WEBINAR FRAMING (Feature L2-H): with `--webinar-intro-outro`, a ~10-minute
framing layer is INJECTED into the synthesis input (in memory) — a ~5-min
WELCOME section before Slide 1 and a ~2-min CHAT Q&A + ~3-min CRESCENDO CLOSE
after the last slide, generated by `webinar_intro_outro.py` (Fish-tagged). The
framing words are included in the duration gate (the audio really is longer), but
the on-disk UNTAGGED deck — the deck-only contract for the teleprompter and the
webinar timing track — is NEVER modified.

The speech is cleaned the same way the word-count gate expects: markdown
headers (## Slide N), the how-to blockquote, horizontal rules, and bold-only
label lines are NOT spoken; everything else is. `[bracket]` tags are preserved;
director cues (`[PAUSE]`/`[BREATHE]`/`(PAUSE N seconds)`/`(OWNER: ...)`) are
converted to measured silence or dropped rather than spoken.
"""

import argparse
import json
import os
import re
import subprocess
import sys
import time
import urllib.request
import urllib.error

# ----------------------------------------------------------------------------
# FIX 14 — governor gate for every outbound Fish Audio /v1/tts call.
# One lease per HTTP attempt: the rate bucket (providers.yaml fish row:
# rps 1.0, burst 10) keeps the synth loop from flooding the API, and a live
# HTTP 429 halves the next 60 s of rate via report_429 (report_ok recovers).
# Fail-soft: when the governor module is absent (a legacy checkout predating
# the FIX 14 merge) every helper is a no-op passthrough — synthesis proceeds
# exactly as before, just unthrottled.
# ----------------------------------------------------------------------------
try:
    from presentation_job import governor as _governor
except Exception:  # noqa: BLE001 — fail-soft: legacy tree without governor.py
    # The repo-root presentation_job/governor.py is the single source; walk up
    # from this file to find it and file-load it (the same pattern build_deck
    # uses when the scripts-local package shadows the repo-root one).
    try:
        import importlib.util as _ilu
        _g = __file__ and os.path.dirname(os.path.abspath(__file__))
        _cand = None
        for _ in range(6):
            if _g and os.path.isfile(os.path.join(_g, "presentation_job", "governor.py")):
                _cand = os.path.join(_g, "presentation_job", "governor.py")
                break
            _g = os.path.dirname(_g) if _g else _g
        _governor = None
        if _cand:
            _spec = _ilu.spec_from_file_location("_presentation_governor", _cand)
            if _spec and _spec.loader:
                _gov_mod = _ilu.module_from_spec(_spec)
                sys.modules.setdefault("_presentation_governor", _gov_mod)
                _spec.loader.exec_module(_gov_mod)
                _governor = _gov_mod
    except Exception:  # noqa: BLE001 — never break synthesis on a gate failure
        _governor = None

_GOV_TTS_PROVIDER = "fish"


# ----------------------------------------------------------------------------
# FIX 114 — key-resolution gate for FISH_AUDIO_API_KEY. Same failure class the
# speech harness burned: a placeholder key reaching the provider and eating the
# whole run budget. The key NAME resolves through the one secret-name canon
# (shared-utils/secret_helper: FISH_AUDIO_API_KEY <-> FISHAUDIO_API_KEY /
# FISH_API_KEY), and the VALUE must pass is_placeholder + looks_like_real_key
# before any synthesis call. A box without the canon helper keeps the exact
# pre-fix behavior (the direct env name, accepted as given) — never a hard
# break. The value is never printed, logged, or stored.
# ----------------------------------------------------------------------------
def _fish_canon_family() -> tuple:
    """The accepted env names for the Fish key: the direct name plus its canon
    alias family. Canon absent or broken -> (direct name,)."""
    names = ("FISH_AUDIO_API_KEY",)
    try:
        import importlib.util as _ilu
        _g = os.path.dirname(os.path.abspath(__file__))
        _cand = None
        for _ in range(6):
            if _g and os.path.isfile(os.path.join(_g, "shared-utils", "secret_helper.py")):
                _cand = os.path.join(_g, "shared-utils", "secret_helper.py")
                break
            _g = os.path.dirname(_g) if _g else _g
        if _cand:
            _spec = _ilu.spec_from_file_location("secret_helper_s114fish", _cand)
            _helper = _ilu.module_from_spec(_spec)
            _spec.loader.exec_module(_helper)
            fam = _helper.alias_list(_helper.canonical_for("FISH_AUDIO_API_KEY"))
            names = tuple(n for n in fam if isinstance(n, str) and n) or names
    except Exception:  # noqa: BLE001 — canon failure degrades to the direct name
        return ("FISH_AUDIO_API_KEY",)
    return names


def _fish_key_is_real(value: str) -> bool:
    """False when `value` is obviously a placeholder or does not read as a real
    Fish credential. Canon gate when reachable, else the inline placeholder
    gate (the same minimal discipline research_web.py carries)."""
    if not value:
        return False
    low = value.strip().lower()
    if len(low) < 10:
        return False
    for sub in ("paste_real_token", "your_key_here", "change_me", "changeme",
                "<todo>", "[replace]", "{{", "placeholder", "example_key",
                "todo:", "xxx"):
        if sub in low:
            return False
    if low.startswith("<") and low.endswith(">"):
        return False
    if low.startswith("[") and low.endswith("]"):
        return False
    try:
        import importlib.util as _ilu
        _g = os.path.dirname(os.path.abspath(__file__))
        _cand = None
        for _ in range(6):
            if _g and os.path.isfile(os.path.join(_g, "shared-utils", "secret_helper.py")):
                _cand = os.path.join(_g, "shared-utils", "secret_helper.py")
                break
            _g = os.path.dirname(_g) if _g else _g
        if _cand:
            _spec = _ilu.spec_from_file_location("secret_helper_s114fish2", _cand)
            _helper = _ilu.module_from_spec(_spec)
            _spec.loader.exec_module(_helper)
            return bool(_helper.looks_like_real_key(value, "FISH_AUDIO_API_KEY"))
    except Exception:  # noqa: BLE001 — canon failure keeps the inline verdict
        pass
    return True


def resolve_fish_api_key() -> str:
    """FIX 114: resolve the Fish Audio bearer key. The canon alias family is
    consulted in order (FISH_AUDIO_API_KEY first), and a resolved value must
    pass the placeholder/shape gate. Returns "" when nothing real resolves —
    the caller's existing missing-key FAIL handles that loudly."""
    for name in _fish_canon_family():
        v = (os.environ.get(name) or "").strip()
        if v and _fish_key_is_real(v):
            return v
    return ""


def _gov_tts_acquire():
    """One Fish Audio lease for this TTS attempt. None = unthrottled."""
    if _governor is None:
        return None
    try:
        return _governor.acquire(_GOV_TTS_PROVIDER, n=1, timeout_s=60.0)
    except Exception:  # noqa: BLE001 — the rate window is a courtesy, not a gate
        return None


def _gov_tts_release(lease) -> None:
    if _governor is None or lease is None:
        return
    try:
        _governor.release(lease)
    except Exception:  # noqa: BLE001
        pass


def _gov_tts_report(kind: str) -> None:
    """Telemetry into the governor: kind is 'ok' or '429'. No-op when absent."""
    if _governor is None:
        return
    try:
        if kind == "429":
            _governor.report_429(_GOV_TTS_PROVIDER)
        elif kind == "ok":
            _governor.report_ok(_GOV_TTS_PROVIDER)
    except Exception:  # noqa: BLE001
        pass


# ----------------------------------------------------------------------------
# Speech cleaning  — keep ONLY what a presenter actually says aloud.
# Must match the word-count gate exactly so the gate is honest.
# ----------------------------------------------------------------------------
def extract_spoken(md_text: str) -> str:
    lines = md_text.splitlines()
    # Front-matter (title block, byline, how-to) lives before the first
    # slide/section heading and is NOT spoken. Drop everything up to the first
    # "## " (or "# ") heading that introduces actual slide content.
    start = 0
    for i, line in enumerate(lines):
        # First "## " (or deeper) heading begins the spoken slide content.
        if re.match(r"^#{2,6}\s", line):
            start = i
            break
    spoken = []
    for line in lines[start:]:
        s = line.strip()
        if not s:
            spoken.append("")
            continue
        if s.startswith("#"):              # slide headings / titles — not spoken
            continue
        if s.startswith(">"):              # how-to blockquote — not spoken
            continue
        if s.startswith("---"):            # horizontal rule
            continue
        if re.match(r"^\*\*.*\*\*$", s):   # bold-only label lines
            continue
        if re.match(r"^\*[^*].*\*$", s):   # italic-only stage directions (*...*)
            continue
        # Strip inline markdown emphasis so the engine never voices asterisks.
        s = re.sub(r"\*{1,3}([^*]+)\*{1,3}", r"\1", s)
        spoken.append(s)
    text = "\n".join(spoken)
    text = re.sub(r"\n{3,}", "\n\n", text).strip()
    return text


def strip_cues(text: str) -> str:
    """Remove director/pause cues for WORD COUNTING only — the duration gate must
    count real spoken words, not `[PAUSE]`/`(OWNER: ...)` tokens. Pause cues are
    later re-inserted as measured silence by segment_pauses(); this helper exists
    so a cue never inflates the expected-duration estimate."""
    text = _OWNER_CUE_RE.sub(" ", text)
    text = _PAUSE_TAG_RE.sub(" ", text)
    return re.sub(r"\s+", " ", text).strip()


def word_count(text: str) -> int:
    return len(text.split())


# ----------------------------------------------------------------------------
# Chunking — split into <= chunk_chars pieces on sentence/paragraph boundaries.
# Never splits mid-sentence unless a single sentence exceeds the limit (then it
# splits on the nearest space). Every word of the speech ends up in some chunk.
# ----------------------------------------------------------------------------
def chunk_text(text: str, chunk_chars: int) -> list[str]:
    # Split into sentence-ish units, preserving terminal punctuation.
    raw = re.split(r"(?<=[.!?])\s+", text.replace("\n\n", " \n\n "))
    units = []
    for u in raw:
        u = u.strip()
        if u:
            units.append(u)

    chunks: list[str] = []
    cur = ""
    for u in units:
        if len(u) > chunk_chars:
            # flush current, then hard-split the long unit on spaces
            if cur:
                chunks.append(cur.strip())
                cur = ""
            words = u.split(" ")
            piece = ""
            for w in words:
                if len(piece) + len(w) + 1 > chunk_chars:
                    if piece:
                        chunks.append(piece.strip())
                    piece = w
                else:
                    piece = (piece + " " + w).strip()
            if piece:
                cur = piece
            continue
        if len(cur) + len(u) + 1 > chunk_chars:
            chunks.append(cur.strip())
            cur = u
        else:
            cur = (cur + " " + u).strip()
    if cur.strip():
        chunks.append(cur.strip())
    return [c for c in chunks if c.strip()]


# ----------------------------------------------------------------------------
# Pause markers -> measured silence (seconds).
#
# Fish S2/S2.1-Pro pause tags have NO documented duration. To get deterministic
# 1-5 s dramatic pauses we splice a measured silent mp3 at the ffmpeg stage
# instead of trusting the model's "brief"/"extended" guess. The tag is stripped
# from the text sent to the API so it is never voiced as a word and never
# double-pauses. Defaults are overridable via CLI.
# ----------------------------------------------------------------------------
DEFAULT_PAUSE_SECONDS = {
    "short pause": 0.8,       # [short pause]  — quick beat
    "pause": 1.2,             # [pause] / [break] / [PAUSE]  — beat / let it land
    "breathe": 1.2,           # [BREATHE]  — breath cue -> beat
    "long pause": 2.5,        # [long pause] / [long-break]  — big silence
}

# Regex that matches a pause marker ANYWHERE in the text (standalone line or
# inline mid-sentence). Group(1) = numeric seconds for `(PAUSE N seconds)`.
_PAUSE_TAG_RE = re.compile(
    r"\[\s*short\s*pause\s*\]"                       # [short pause]
    r"|\[\s*long\s*[- ]?pause\s*\]"                  # [long pause] / [long-pause]
    r"|\[\s*long\s*[- ]?break\s*\]"                  # [long-break] / [long break]
    r"|\[\s*(?:PAUSE|BREATHE|BREAK)\s*\]"            # [pause] [PAUSE] [breathe] [break]
    r"|\(\s*PAUSE\s+(\d+(?:\.\d+)?)\s*seconds?\s*\)"  # (PAUSE 2 seconds) -> exact
    ,
    re.IGNORECASE,
)

# Regex that matches a (OWNER: ...) director cue INLINE so it is dropped, never
# voiced as text.
_OWNER_CUE_RE = re.compile(r"\(\s*OWNER\s*:.*?\)", re.IGNORECASE | re.DOTALL)


def segment_pauses(text: str, pause_seconds: dict) -> list:
    """Split *text* into an ordered list of ("speech", str) and ("silence", float)
    items.

    Pause markers (standalone or inline) are removed from the speech text and
    turned into measured-silence items; `(OWNER: ...)` director cues are dropped
    entirely. Adjacent silence items are merged so `[pause][long pause]` becomes
    one 3.7 s gap instead of two separate files.
    """
    # Drop (OWNER: ...) director cues before anything else — they are notes, not
    # spoken words, and must never reach the API.
    text = _OWNER_CUE_RE.sub(" ", text)

    items: list = []           # ("speech"|"silence", payload)
    cursor = 0
    for m in _PAUSE_TAG_RE.finditer(text):
        before = text[cursor:m.start()]
        if before.strip():
            items.append(("speech", before.strip()))
        tag = m.group(0)
        if m.group(1) is not None:
            seconds = float(m.group(1))
        else:
            low = tag.lower().strip()
            if "short pause" in low:
                seconds = pause_seconds["short pause"]
            elif "long" in low:
                seconds = pause_seconds["long pause"]
            elif "breathe" in low:
                seconds = pause_seconds["breathe"]
            else:
                seconds = pause_seconds["pause"]
        items.append(("silence", seconds))
        cursor = m.end()
    tail = text[cursor:]
    if tail.strip():
        items.append(("speech", tail.strip()))

    # Merge adjacent silence items.
    merged: list = []
    for kind, payload in items:
        if kind == "silence" and merged and merged[-1][0] == "silence":
            merged[-1] = ("silence", merged[-1][1] + payload)
        else:
            merged.append((kind, payload))
    return merged


def make_silence_mp3(seconds: float, out_path: str, bitrate: int,
                     sample_rate: int = 44100) -> str:
    """Generate a *measured* silent MP3 of exactly *seconds* via ffmpeg anullsrc.
    Deterministic and reliable for the 1-5 s dramatic-pause requirement."""
    subprocess.check_call([
        "ffmpeg", "-y",
        "-f", "lavfi", "-i", f"anullsrc=r={sample_rate}:cl=mono",
        "-t", f"{seconds:.3f}",
        "-c:a", "libmp3lame", "-b:a", f"{bitrate}k",
        out_path,
    ], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return out_path


# ----------------------------------------------------------------------------
# Fish Audio synthesis (one request per chunk).
# ----------------------------------------------------------------------------
FISH_URL = "https://api.fish.audio/v1/tts"

# The authoritative Fish Audio model for CLIENT production (FIX-9 / T-10 model
# truth): S2.1 Pro (paid), per 30-fish-audio-api-reference/references/
# fish-audio-api-reference.md and SKILL.md. The interim `s2-pro` id was superseded
# by S2.1 Pro; `s2.1-pro-free` is operator-internal ONLY (no SLA, may train on
# submitted inputs, expires end of July 2026) and is FORBIDDEN for client work.
# This is the single source for the argparse default.
MAIN_MODEL_DEFAULT = "s2.1-pro"


def synth_chunk(text, api_key, voice_id, model, bitrate, out_path,
                normalize=True, retries=3,
                temperature=0.9, top_p=0.8, repetition_penalty=1.2,
                prosody_speed=1.25, prosody_volume=0.0,
                prosody_normalize_loudness=True):
    """Synthesize *text* via Fish Audio /v1/tts.

    EXPRESSIVE REQUEST (GAUNTLET LOOP 2): sends the Fish API's documented
    expressiveness knobs — temperature (0-1, "controls expressiveness", default
    0.7; we raise to 0.9), top_p (0-1, default 0.7 -> 0.8), repetition_penalty
    (>1.0 suppresses repeating audio patterns, default 1.2), and prosody
    {speed 0.5-2.0, volume dB, normalize_loudness}. Field names verified against
    https://api.fish.audio/openapi.json (TTSRequest schema).
    """
    body = {
        "text": text,
        "format": "mp3",
        "mp3_bitrate": bitrate,
        "chunk_length": 300,
        "normalize": normalize,
        "latency": "normal",
        "temperature": temperature,
        "top_p": top_p,
        "repetition_penalty": repetition_penalty,
        "prosody": {
            "speed": prosody_speed,
            "volume": prosody_volume,
            "normalize_loudness": prosody_normalize_loudness,
        },
    }
    if voice_id:
        body["reference_id"] = voice_id
    data = json.dumps(body).encode("utf-8")

    last_err = None
    for attempt in range(1, retries + 1):
        # FIX 14: one governor lease per HTTP attempt on the fish provider.
        # A live HTTP 429 feeds report_429 (rate halved 60 s) before the
        # backoff sleep; a clean response feeds report_ok; the lease is
        # released before the backoff so a sleeping retry holds no slot.
        _lease = _gov_tts_acquire()
        try:
            req = urllib.request.Request(
                FISH_URL, data=data, method="POST",
                headers={
                    "Authorization": f"Bearer {api_key}",
                    "Content-Type": "application/json",
                    "model": model,
                },
            )
            try:
                with urllib.request.urlopen(req, timeout=300) as resp:
                    audio = resp.read()
                if not audio or len(audio) < 256:
                    raise RuntimeError(f"empty/tiny audio ({len(audio)} bytes)")
                with open(out_path, "wb") as f:
                    f.write(audio)
                _gov_tts_report("ok")
                return len(audio)
            except urllib.error.HTTPError as e:
                err_body = ""
                try:
                    err_body = e.read().decode("utf-8", "replace")[:300]
                except Exception:
                    pass
                last_err = f"HTTP {e.code}: {err_body}"
                # 429 / 5xx: back off and retry; 4xx (auth/validation): FAIL LOUD now
                if e.code == 429 or 500 <= e.code < 600:
                    if e.code == 429:
                        _gov_tts_report("429")
                    time.sleep(min(20, 5 * attempt))
                    continue
                break
            except Exception as e:  # noqa: BLE001
                last_err = str(e)
                _gov_tts_report("ok")  # a transport failure is not throttling
                time.sleep(min(20, 5 * attempt))
        finally:
            _gov_tts_release(_lease)
    raise RuntimeError(f"Fish Audio synthesis failed for chunk -> {out_path}: {last_err}")


# ----------------------------------------------------------------------------
# ffmpeg helpers
# ----------------------------------------------------------------------------
def ffprobe_duration(path: str) -> float:
    out = subprocess.check_output([
        "ffprobe", "-v", "error", "-show_entries", "format=duration",
        "-of", "default=noprint_wrappers=1:nokey=1", path,
    ]).decode().strip()
    return float(out)


# ----------------------------------------------------------------------------
# MP3 VALIDITY PROBE — FIX-9 / T-10 QC gate. A deliverable that "exists" but is
# not decodable audio is a defect, not an MP3. This proves the file is a REAL MP3:
#   (1) size > 10 KB floor (matches the FIX-9 QC row: "valid MP3 > 10KB");
#   (2) an ID3v2 header (tag 'ID3' at offset 0) — the standard MP3 metadata frame;
#   (3) at least one valid MPEG audio frame header (11-bit frame-sync 0xFFE0)
#       parsed after the ID3 tag (or at offset 0 for tag-less MP3s).
# Returns '' on PASS, or a non-empty reason string on FAIL (fail-loud).
# ----------------------------------------------------------------------------
MP3_MIN_BYTES = 10_000  # 10 KB floor from the FIX-9 QC row


def _is_mp3_frame_sync(b: bytes) -> bool:
    """True iff the two bytes carry a valid MPEG audio frame sync (11-bit 1s)."""
    return (b[0] == 0xFF) and ((b[1] & 0xE0) == 0xE0) and ((b[1] & 0x06) != 0x00)


def verify_mp3(path: str) -> str:
    """Probe an MP3 file for real audio content. Returns '' (PASS) or a reason
    string (FAIL). Never raises: any probe error is a FAIL, never an exception."""
    try:
        if not os.path.exists(path):
            return f"missing file: {path}"
        size = os.path.getsize(path)
        if size < MP3_MIN_BYTES:
            return f"too small: {size} bytes < {MP3_MIN_BYTES} floor"
        with open(path, "rb") as f:
            head = f.read(16)
        if not head:
            return "empty file"
        # ID3v2 header present? tag 'ID3' + major version + 4 syncsafe size bytes.
        offset = 0
        if head.startswith(b"ID3"):
            if len(head) < 10:
                return "truncated ID3v2 header"
            id3_size = ((head[6] & 0x7F) << 21) | ((head[7] & 0x7F) << 14) \
                     | ((head[8] & 0x7F) << 7) | (head[9] & 0x7F)
            offset = 10 + id3_size
        # Read the frame header at (or after) the ID3 tag.
        with open(path, "rb") as f:
            f.seek(offset)
            frame = f.read(4)
        if len(frame) < 4:
            return f"no audio frame after ID3 (frame offset {offset})"
        if not _is_mp3_frame_sync(frame[:2]):
            return (f"no valid MPEG audio frame header at offset {offset} "
                    f"(bytes {frame[:2].hex()}); not decodable audio")
        return ""
    except Exception as exc:  # noqa: BLE001 — any probe error fails closed
        return f"probe error: {exc!r}"


def ffmpeg_concat_normalize(chunk_paths, raw_out, final_out, bitrate):
    list_path = raw_out + ".concat.txt"
    with open(list_path, "w") as f:
        for p in chunk_paths:
            f.write(f"file '{p}'\n")
    # Concat (stream copy where possible; re-encode to be safe across chunks)
    subprocess.check_call([
        "ffmpeg", "-y", "-f", "concat", "-safe", "0", "-i", list_path,
        "-c:a", "libmp3lame", "-b:a", f"{bitrate}k", raw_out,
    ], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    # Loudness-normalize to -16 LUFS (broadcast spoken-word standard)
    subprocess.check_call([
        "ffmpeg", "-y", "-i", raw_out,
        "-af", "loudnorm=I=-16:TP=-1.5:LRA=11",
        "-c:a", "libmp3lame", "-b:a", f"{bitrate}k", final_out,
    ], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


# ----------------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------------
def main():
    ap = argparse.ArgumentParser(description="Full-length presenter-audio synthesis with duration gate.")
    ap.add_argument("--speech", required=True, help="Path to PRESENTERS-SPEECH.md (UNTAGGED — used for the word-count / duration gate)")
    ap.add_argument("--tagged-speech", default=None,
                    help="Path to PRESENTERS-SPEECH-FISH-TAGGED.md. When given, THIS is the "
                         "text synthesized (so [bracket] reader tags reach the API). Falls "
                         "back to --speech if omitted.")
    ap.add_argument("--out", required=True, help="Path to write the final full-length mp3")
    # FIX 114: the key resolves through the canon alias family and must pass
    # the placeholder/shape gate; --api-key (an explicit operator hand-off)
    # still wins over the environment.
    _env_fish_key = resolve_fish_api_key()
    ap.add_argument("--api-key", default=_env_fish_key if _env_fish_key
                    else None)
    ap.add_argument("--voice-id", default=os.environ.get("FISH_AUDIO_VOICE_ID"))
    ap.add_argument("--model", default=MAIN_MODEL_DEFAULT,
                    help="Fish Audio model (HTTP model header). Current PAID production "
                         "model is s2.1-pro (per 30-fish-audio-api-reference); the interim "
                         "s2-pro id was superseded and is NOT a durable default for client "
                         "work. Never default to s2.1-pro-free (no SLA / data-retention / "
                         "client-prod prohibited).")
    ap.add_argument("--bitrate", type=int, default=192)
    ap.add_argument("--wpm", type=float, default=140.0, help="Expected speaking rate for the duration gate")
    ap.add_argument("--min-ratio", type=float, default=0.80,
                    help="Hard floor: audio_sec must be >= min_ratio * expected_sec")
    ap.add_argument("--chunk-chars", type=int, default=280, help="Max chars per Fish request (API cap is 300)")
    ap.add_argument("--workdir", default=None, help="Where to write per-chunk mp3s (default: <out_dir>/_audio_chunks_full)")
    ap.add_argument("--normalize", action="store_true", default=True)
    # ---- WEBINAR FRAMING (Feature L2-H): welcome / Q&A / crescendo close ----
    ap.add_argument("--webinar-intro-outro", action="store_true",
                    help="Prepend the ~5-min WELCOME section before Slide 1 and append "
                         "the ~2-min CHAT Q&A + ~3-min CRESCENDO CLOSE after the last "
                         "slide. Generated by webinar_intro_outro.py, Fish-tagged. The "
                         "on-disk UNTAGGED speech (duration gate) is NOT modified.")
    # ---- EXPRESSIVE AUDIO knobs (GAUNTLET LOOP 2) ----
    ap.add_argument("--temperature", type=float, default=0.9,
                    help="Fish API temperature (0-1). 'Controls expressiveness' — higher is "
                         "more varied. Default 0.9 (OpenAPI default is 0.7).")
    ap.add_argument("--top-p", type=float, default=0.8,
                    help="Fish API top_p (0-1). Nucleus-sampling diversity. Default 0.8.")
    ap.add_argument("--repetition-penalty", type=float, default=1.2,
                    help="Fish API repetition_penalty (>1.0 reduces repeating audio patterns). Default 1.2.")
    ap.add_argument("--prosody-speed", type=float, default=1.25,
                    help="prosody.speed (0.5-2.0). Global speaking-rate multiplier. Default 1.25 "
                         "(Trevor-selected default; medium 1.3 / fast 1.33).")
    ap.add_argument("--prosody-volume", type=float, default=0.0,
                    help="prosody.volume (dB, ~ -20..+20). Default 0.")
    ap.add_argument("--prosody-no-normalize-loudness", action="store_true",
                    help="Set prosody.normalize_loudness=false (S2 family only; default true).")
    # ---- measured silence defaults ----
    ap.add_argument("--pause-short", type=float, default=DEFAULT_PAUSE_SECONDS["short pause"],
                    help="Seconds for [short pause]")
    ap.add_argument("--pause", type=float, default=DEFAULT_PAUSE_SECONDS["pause"],
                    help="Seconds for [pause]/[break]/[PAUSE]")
    ap.add_argument("--pause-long", type=float, default=DEFAULT_PAUSE_SECONDS["long pause"],
                    help="Seconds for [long pause]/[long-break]")
    args = ap.parse_args()

    if not args.api_key:
        sys.exit("FAIL: no Fish Audio API key (set FISH_AUDIO_API_KEY or --api-key).")
    # FIX 114: an explicit --api-key value is gated too — a placeholder handed
    # on the command line never reaches the provider and burns the run.
    if not _fish_key_is_real(args.api_key):
        sys.exit("FAIL: FISH_AUDIO_API_KEY value looks like a placeholder, not a "
                 "real key (FIX 114). Set a real credential and retry.")

    # ---- SPEED PREFERENCE (Trevor-selected presets) ----
    # intake.json carries the client's speech_speed_preference (default/medium/fast).
    # Map to the Fish prosody.speed presets: default=1.25, medium=1.3, fast=1.33.
    # An explicit --prosody-speed on the CLI always wins; otherwise the intake
    # preference (or the built-in 1.25 default) applies.
    if args.prosody_speed == 1.25:  # the built-in default was not overridden
        try:
            _intake_p = Path(args.out).resolve()
            for _cand in (_intake_p.parents[1] / "working" / "copy" / "intake.json",
                          _intake_p.parents[2] / "working" / "copy" / "intake.json"):
                if _cand.is_file():
                    _it = json.loads(_cand.read_text())
                    _pref = str(_it.get("speech_speed_preference", "default")).strip().lower()
                    _SPEED_PRESETS = {"default": 1.25, "medium": 1.3, "fast": 1.33}
                    if _pref in _SPEED_PRESETS:
                        args.prosody_speed = _SPEED_PRESETS[_pref]
                        print(f"[speed] intake speech_speed_preference={_pref!r} -> "
                              f"prosody.speed {args.prosody_speed}")
                    break
        except Exception:  # noqa: BLE001 — intake absence is non-fatal; keep 1.25
            pass

    # ffmpeg presence
    for tool in ("ffmpeg", "ffprobe"):
        if subprocess.call(["which", tool], stdout=subprocess.DEVNULL) != 0:
            sys.exit(f"FAIL: {tool} not found on PATH. Install via 'brew install ffmpeg'.")

    # ---- WEBINAR FRAMING (Feature L2-H): build the welcome / Q&A / crescendo
    # close sections UP FRONT so they feed BOTH the duration gate (their words
    # must count toward expected duration — the audio really is longer) and the
    # synthesis input. Injection is IN MEMORY only; the on-disk UNTAGGED deck
    # (the deck-only timing/word contract for teleprompter / webinar_timing) is
    # never modified.
    framing_sections = []
    if args.webinar_intro_outro:
        import webinar_intro_outro  # local import: same scripts dir
        framing_sections = webinar_intro_outro.build_framing_markdown()
        print(f"[framing] WEBINAR FRAMING enabled: welcome + Q&A + crescendo close "
              f"({webinar_intro_outro.word_count(framing_sections)} framing words)")

    # ---- duration gate input: UNTAGGED speech (tags are not spoken words) ----
    md = open(args.speech).read()
    spoken = extract_spoken(md)
    words = word_count(strip_cues(spoken))
    framing_words = 0
    if args.webinar_intro_outro:
        import webinar_intro_outro  # local import: same scripts dir
        framing_words = webinar_intro_outro.word_count(framing_sections)
        words += framing_words
    expected_sec = words / args.wpm * 60.0
    floor_sec = expected_sec * args.min_ratio
    print(f"[speech] spoken words (untagged gate) = {words} "
          f"(deck {words - framing_words} + framing {framing_words})")
    print(f"[speech] expected duration @ {args.wpm:.0f} wpm = {expected_sec:.1f}s ({expected_sec/60:.2f} min)")
    print(f"[gate]   minimum acceptable duration = {floor_sec:.1f}s ({floor_sec/60:.2f} min)  (>= {args.min_ratio:.0%})")

    # ---- synthesis input: TAGGED speech (bracket reader tags must reach the API) ----
    synth_md_path = args.tagged_speech or args.speech
    synth_md = open(synth_md_path).read()

    # ---- inject the framing INTO the tagged synthesis input (welcome before
    # Slide 1; Q&A + crescendo close after the last slide).
    if args.webinar_intro_outro:
        import webinar_intro_outro  # local import: same scripts dir
        deck_body = webinar_intro_outro.extract_deck_body(synth_md)
        # Safety: extraction must preserve every slide header and never drop or
        # reorder slide content (a corrupt extraction must not be synthesized).
        if len(re.findall(r"(?m)^##\s+Slide\s+\d+\b", deck_body)) != \
                len(re.findall(r"(?m)^##\s+Slide\s+\d+\b", synth_md)):
            sys.exit("FAIL: webinar framing extraction dropped a slide header. "
                     "Refusing to synthesize.")
        synth_md = webinar_intro_outro.inject_framing(synth_md, framing_sections)
        print(f"[framing] injected WEBINAR FRAMING into the synthesis input.")

    synth_spoken = extract_spoken(synth_md)
    if args.tagged_speech and args.tagged_speech != args.speech:
        # Sanity: the tagged text must contain the untagged words. Strip brackets
        # from the tagged spoken text and assert word-for-word containment, else
        # the tagged file is corrupt and we must not ship flat/broken audio.
        # NOTE: with --webinar-intro-outro the comparison uses ONLY the deck body
        # (framing words are intentionally new content, not part of the deck's
        # word-for-word contract).
        import speech_fish_tag  # local import: same scripts dir
        if args.webinar_intro_outro:
            import webinar_intro_outro  # local import: same scripts dir
            deck_spoken = extract_spoken(webinar_intro_outro.extract_deck_body(synth_md))
            deck_ok = speech_fish_tag.verify_strip_equals_source(deck_spoken, spoken)
        else:
            deck_ok = speech_fish_tag.verify_strip_equals_source(synth_spoken, spoken)
        if not deck_ok:
            sys.exit("FAIL: --tagged-speech does not word-for-word match --speech after "
                     "stripping tags. Refuse to synthesize a corrupt tagged file. "
                     "Re-run speech_fish_tag.py and verify.")
        print(f"[tagged] synthesis input = {synth_md_path} "
              f"({len(synth_spoken)} chars, tags verified against untagged speech)")

    # ---- segment into speech + measured silence, then chunk the speech ----
    pause_seconds = {
        "short pause": args.pause_short,
        "pause": args.pause,
        "long pause": args.pause_long,
        "breathe": args.pause,  # breath cue -> beat
    }
    items = segment_pauses(synth_spoken, pause_seconds)

    n_speech = sum(1 for k, _ in items if k == "speech")
    n_silence = sum(1 for k, _ in items if k == "silence")
    total_silence = sum(p for k, p in items if k == "silence")
    print(f"[pause]  {n_silence} measured-silence insertions totalling {total_silence:.1f}s "
          f"({n_speech} speech segments)")

    # Build ordered chunks: speech segments chunked to --chunk-chars, silence
    # segments as exact silent mp3s. Order is preserved for the concat.
    workdir = args.workdir or os.path.join(os.path.dirname(os.path.abspath(args.out)), "_audio_chunks_full")
    os.makedirs(workdir, exist_ok=True)

    speech_segments = [p for k, p in items if k == "speech"]
    speech_chunks: list[str] = []
    for seg in speech_segments:
        speech_chunks.extend(chunk_text(seg, args.chunk_chars))

    total_chars = sum(len(c) for c in speech_chunks)
    synth_norm = re.sub(r"\s+", " ", strip_cues(synth_spoken))
    print(f"[chunk]  {len(speech_chunks)} speech chunks, {total_chars} total chars "
          f"({len(synth_norm)} cue-stripped chars — {total_chars/max(1,len(synth_norm)):.0%} coverage of tagged text)")
    if total_chars < 0.95 * len(synth_norm):
        sys.exit("FAIL: chunking dropped text (coverage < 95%). Aborting before synthesis.")

    # Assemble ordered render plan: interleave speech chunk paths and silence paths.
    # FIX (chunk-drop): a single speech SEGMENT can chunk into MULTIPLE pieces
    # (chunk_text splits on sentence/paragraph boundaries up to --chunk-chars).
    # The old loop consumed ONE chunk per speech segment via next(speech_iter),
    # silently DROPPING every chunk after the first in each segment — the concat
    # was far shorter than the speech and the duration gate tripped. We now
    # expand each segment into its list of chunks and render EVERY chunk in order.
    render_items: list = []      # ("file", path) for concat
    ordered_speech: list = []    # one entry per speech chunk, in original order
    for kind, payload in items:
        if kind == "speech":
            ordered_speech.extend(chunk_text(payload, args.chunk_chars))
        else:
            ordered_speech.append(("silence", payload))
    chunk_index = 0
    n_speech_rendered = 0
    for entry in ordered_speech:
        if isinstance(entry, tuple) and entry[0] == "silence":
            seconds = entry[1]
            sp = os.path.join(workdir, f"silence_{chunk_index:03d}.mp3")
            make_silence_mp3(seconds, sp, args.bitrate)
            _sp_reason = verify_mp3(sp)
            if _sp_reason:
                sys.exit(f"FAIL (MP3 PROBE): silence segment is not a valid MP3 ({_sp_reason}).")
            render_items.append(("file", sp))
            print(f"  [silence {len([r for r in render_items if r[1].startswith('silence_')]):02d}] "
                  f"{seconds:.1f}s -> {os.path.basename(sp)}", flush=True)
        else:
            c = entry
            cp = os.path.join(workdir, f"chunk_{chunk_index:03d}.mp3")
            chunk_index += 1
            n = synth_chunk(c, args.api_key, args.voice_id, args.model, args.bitrate, cp,
                            normalize=args.normalize,
                            temperature=args.temperature, top_p=args.top_p,
                            repetition_penalty=args.repetition_penalty,
                            prosody_speed=args.prosody_speed,
                            prosody_volume=args.prosody_volume,
                            prosody_normalize_loudness=not args.prosody_no_normalize_loudness)
            # FIX-9 MP3 validity probe per chunk — a chunk that is not real audio
            # must fail BEFORE it can poison the concat.
            _mp3_reason = verify_mp3(cp)
            if _mp3_reason:
                sys.exit(f"FAIL (MP3 PROBE): chunk {chunk_index} is not a valid MP3 ({_mp3_reason}). "
                         f"Aborting before concat — a corrupt chunk must never reach the deliverable.")
            render_items.append(("file", cp))
            n_speech_rendered += 1
            print(f"  [{n_speech_rendered}/{len(speech_chunks)}] {len(c)} chars -> {os.path.basename(cp)} ({n:,} bytes)", flush=True)

    chunk_paths = [p for _, p in render_items]
    raw_out = os.path.join(workdir, "concat_raw_full.mp3")
    final_out = args.out
    ffmpeg_concat_normalize(chunk_paths, raw_out, final_out, args.bitrate)

    audio_sec = ffprobe_duration(final_out)
    print(f"[render] final audio duration = {audio_sec:.1f}s ({audio_sec/60:.2f} min)")

    # ---- DURATION SANITY GATE (HARD, FAIL LOUD) ----
    if audio_sec < floor_sec:
        # Do not leave a short file masquerading as the deliverable.
        bad = final_out + ".FAILED-SHORT"
        try:
            os.replace(final_out, bad)
        except OSError:
            bad = final_out
        sys.exit(
            "FAIL (DURATION GATE): rendered audio is "
            f"{audio_sec:.1f}s but the speech needs >= {floor_sec:.1f}s "
            f"({audio_sec/expected_sec:.0%} of the {expected_sec:.1f}s expected). "
            f"The audio does NOT cover the full speech. Short file moved to {bad}. "
            "Re-run synthesis over the ENTIRE speech."
        )

    # ---- FIX-9 MP3 VALIDITY PROBE (HARD, FAIL LOUD) on the FINAL deliverable ----
    # The FIX-9 / T-10 QC gate: audio_mp3 must EXIST, be > 10 KB, and be a VALID,
    # decodable MP3 (parseable header/frame). Size alone is not proof.
    _final_mp3_reason = verify_mp3(final_out)
    if _final_mp3_reason:
        bad = final_out + ".FAILED-NOT-MP3"
        try:
            os.replace(final_out, bad)
        except OSError:
            bad = final_out
        sys.exit(
            "FAIL (MP3 PROBE): the final deliverable is not a valid MP3 "
            f"({_final_mp3_reason}). Moved to {bad}. A non-audio file must never "
            "ship as the presentation audio."
        )
    print(f"[PASS]   audio {audio_sec:.1f}s >= floor {floor_sec:.1f}s "
          f"({audio_sec/expected_sec:.0%} of expected); MP3 validity probe PASS "
          f"({os.path.getsize(final_out):,} bytes, valid MP3). "
          f"Full-length audio OK -> {final_out}")


if __name__ == "__main__":
    main()
